package main

var emojiToCodepoints = map[string][]string{
	// SMILEYS & EMOTION
	// face-smiling
	"Grinning Face":                   []string{"U1F600"},
	"Grinning Face With Big Eyes":     []string{"U1F603"},
	"Grinning Face With Smiling Eyes": []string{"U1F604"},
	"Beaming Face With Smiling Eyes":  []string{"U1F601"},
	"Grinning Squinting Face":         []string{"U1F606"},
	"Grinning Face With Sweat":        []string{"U1F605"},
	"Rolling On The Floor Laughing":   []string{"U1F923"},
	"Face With Tears Of Joy":          []string{"U1F602"},
	"Slightly Smiling Face":           []string{"U1F642"},
	"Upside-Down Face":                []string{"U1F643"},
	"Winking Face":                    []string{"U1F609"},
	"Smiling Face With Smiling Eyes":  []string{"U1F60A"},
	"Smiling Face With Halo":          []string{"U1F607"},
	// face-affection
	"Smiling Face With Hearts":       []string{"U1F970"},
	"Smiling Face With Heart-Eyes":   []string{"U1F60D"},
	"Star-Struck":                    []string{"U1F929"},
	"Face Blowing A Kiss":            []string{"U1F618"},
	"Kissing Face":                   []string{"U1F617"},
	"Smiling Face":                   []string{"U263A"},
	"Kissing Face With Closed Eyes":  []string{"U1F61A"},
	"Kissing Face With Smiling Eyes": []string{"U1F619"},
	// face-tongue
	"Face Savoring Food":         []string{"U1F60B"},
	"Face With Tongue":           []string{"U1F61B"},
	"Winking Face With Tongue":   []string{"U1F61C"},
	"Zany Face":                  []string{"U1F92A"},
	"Squinting Face With Tongue": []string{"U1F61D"},
	"Money-Mouth Face":           []string{"U1F911"},
	// face-hand
	"Hugging Face":              []string{"U1F917"},
	"Face With Hand Over Mouth": []string{"U1F92D"},
	"Shushing Face":             []string{"U1F92B"},
	"Thinking Face":             []string{"U1F914"},
	// face-neutral-skeptical
	"Zipper-Mouth Face":        []string{"U1F910"},
	"Face With Raised Eyebrow": []string{"U1F928"},
	"Neutral Face":             []string{"U1F610"},
	"Expressionless Face":      []string{"U1F611"},
	"Face Without Mouth":       []string{"U1F636"},
	"Smirking Face":            []string{"U1F60F"},
	"Unamused Face":            []string{"U1F612"},
	"Face With Rolling Eyes":   []string{"U1F644"},
	"Grimacing Face":           []string{"U1F62C"},
	"Lying Face":               []string{"U1F925"},
	// face-sleepy
	"Relieved Face": []string{"U1F60C"},
	"Pensive Face":  []string{"U1F614"},
	"Sleepy Face":   []string{"U1F62A"},
	"Drooling Face": []string{"U1F924"},
	"Sleeping Face": []string{"U1F634"},
	// face-unwell
	"Face With Medical Mask": []string{"U1F637"},
	"Face With Thermometer":  []string{"U1F912"},
	"Face With Head-Bandage": []string{"U1F915"},
	"Nauseated Face":         []string{"U1F922"},
	"Face Vomiting":          []string{"U1F92E"},
	"Sneezing Face":          []string{"U1F927"},
	"Hot Face":               []string{"U1F975"},
	"Cold Face":              []string{"U1F976"},
	"Woozy Face":             []string{"U1F974"},
	"Dizzy Face":             []string{"U1F635"},
	"Exploding Head":         []string{"U1F92F"},
	// face-hat
	"Cowboy Hat Face": []string{"U1F920"},
	"Partying Face":   []string{"U1F973"},
	// face-glasses
	"Smiling Face With Sunglasses": []string{"U1F60E"},
	"Nerd Face":                    []string{"U1F913"},
	"Face With Monocle":            []string{"U1F9D0"},
	// face-concerned
	"Confused Face":                 []string{"U1F615"},
	"Worried Face":                  []string{"U1F61F"},
	"Slightly Frowning Face":        []string{"U1F641"},
	"Frowning Face":                 []string{"U2639"},
	"Face With Open Mouth":          []string{"U1F62E"},
	"Hushed Face":                   []string{"U1F62F"},
	"Astonished Face":               []string{"U1F632"},
	"Flushed Face":                  []string{"U1F633"},
	"Pleading Face":                 []string{"U1F97A"},
	"Frowning Face With Open Mouth": []string{"U1F626"},
	"Anguished Face":                []string{"U1F627"},
	"Fearful Face":                  []string{"U1F628"},
	"Anxious Face With Sweat":       []string{"U1F630"},
	"Sad But Relieved Face":         []string{"U1F625"},
	"Crying Face":                   []string{"U1F622"},
	"Loudly Crying Face":            []string{"U1F62D"},
	"Face Screaming In Fear":        []string{"U1F631"},
	"Confounded Face":               []string{"U1F616"},
	"Persevering Face":              []string{"U1F623"},
	"Disappointed Face":             []string{"U1F61E"},
	"Downcast Face With Sweat":      []string{"U1F613"},
	"Weary Face":                    []string{"U1F629"},
	"Tired Face":                    []string{"U1F62B"},
	"Yawning Face":                  []string{"U1F971"},
	// face-negative
	"Face With Steam From Nose":  []string{"U1F624"},
	"Pouting Face":               []string{"U1F621"},
	"Angry Face":                 []string{"U1F620"},
	"Face With Symbols On Mouth": []string{"U1F92C"},
	"Smiling Face With Horns":    []string{"U1F608"},
	"Angry Face With Horns":      []string{"U1F47F"},
	"Skull":                      []string{"U1F480"},
	"Skull And Crossbones":       []string{"U2620"},
	// face-costume
	"Pile Of Poo":   []string{"U1F4A9"},
	"Clown Face":    []string{"U1F921"},
	"Ogre":          []string{"U1F479"},
	"Goblin":        []string{"U1F47A"},
	"Ghost":         []string{"U1F47B"},
	"Alien":         []string{"U1F47D"},
	"Alien Monster": []string{"U1F47E"},
	"Robot":         []string{"U1F916"},
	// cat-face
	"Grinning Cat":                   []string{"U1F63A"},
	"Grinning Cat With Smiling Eyes": []string{"U1F638"},
	"Cat With Tears Of Joy":          []string{"U1F639"},
	"Smiling Cat With Heart-Eyes":    []string{"U1F63B"},
	"Cat With Wry Smile":             []string{"U1F63C"},
	"Kissing Cat":                    []string{"U1F63D"},
	"Weary Cat":                      []string{"U1F640"},
	"Crying Cat":                     []string{"U1F63F"},
	"Pouting Cat":                    []string{"U1F63E"},
	// monkey-face
	"See-No-Evil Monkey":   []string{"U1F648"},
	"Hear-No-Evil Monkey":  []string{"U1F649"},
	"Speak-No-Evil Monkey": []string{"U1F64A"},
	// emotion
	"Kiss Mark":            []string{"U1F48B"},
	"Love Letter":          []string{"U1F48C"},
	"Heart With Arrow":     []string{"U1F498"},
	"Heart With Ribbon":    []string{"U1F49D"},
	"Sparkling Heart":      []string{"U1F496"},
	"Growing Heart":        []string{"U1F497"},
	"Beating Heart":        []string{"U1F493"},
	"Revolving Hearts":     []string{"U1F49E"},
	"Two Hearts":           []string{"U1F495"},
	"Heart Decoration":     []string{"U1F49F"},
	"Heart Exclamation":    []string{"U2763"},
	"Broken Heart":         []string{"U1F494"},
	"Red Heart":            []string{"U2764"},
	"Orange Heart":         []string{"U1F9E1"},
	"Yellow Heart":         []string{"U1F49B"},
	"Green Heart":          []string{"U1F49A"},
	"Blue Heart":           []string{"U1F499"},
	"Purple Heart":         []string{"U1F49C"},
	"Brown Heart":          []string{"U1F90E"},
	"Black Heart":          []string{"U1F5A4"},
	"White Heart":          []string{"U1F90D"},
	"Hundred Points":       []string{"U1F4AF"},
	"Anger Symbol":         []string{"U1F4A2"},
	"Collision":            []string{"U1F4A5"},
	"Dizzy":                []string{"U1F4AB"},
	"Sweat Droplets":       []string{"U1F4A6"},
	"Dashing Away":         []string{"U1F4A8"},
	"Hole":                 []string{"U1F573"},
	"Bomb":                 []string{"U1F4A3"},
	"Speech Balloon":       []string{"U1F4AC"},
	"Eye In Speech Bubble": []string{"U1F441", "UFE0F", "U200D", "U1F5E8", "UFE0F"},
	"Left Speech Bubble":   []string{"U1F5E8"},
	"Right Anger Bubble":   []string{"U1F5EF"},
	"Thought Balloon":      []string{"U1F4AD"},
	"Zzz":                  []string{"U1F4A4"},

	// PEOPLE & BODY
	// hand-fingers-open
	"Waving Hand":               []string{"U1F44B"},
	"Raised Back Of Hand":       []string{"U1F91A"},
	"Hand With Fingers Splayed": []string{"U1F590"},
	"Raised Hand":               []string{"U270B"},
	"Vulcan Salute":             []string{"U1F596"},
	// hand-fingers-partial
	"OK Hand":           []string{"U1F44C"},
	"Pinching Hand":     []string{"U1F90F"},
	"Victory Hand":      []string{"U270C"},
	"Crossed Fingers":   []string{"U1F91E"},
	"Love-You Gesture":  []string{"U1F91F"},
	"Sign Of The Horns": []string{"U1F918"},
	"Call Me Hand":      []string{"U1F919"},
	// hand-single-finger
	"Backhand Index Pointing Left":  []string{"U1F448"},
	"Backhand Index Pointing Right": []string{"U1F449"},
	"Backhand Index Pointing Up":    []string{"U1F446"},
	"Middle Finger":                 []string{"U1F595"},
	"Backhand Index Pointing Down":  []string{"U1F447"},
	"Index Pointing Up":             []string{"U261D"},
	// hand-fingers-closed
	"Thumbs Up":         []string{"U1F44D"},
	"Thumbs Down":       []string{"U1F44E"},
	"Raised Fist":       []string{"U270A"},
	"Oncoming Fist":     []string{"U1F44A"},
	"Left-Facing Fist":  []string{"U1F91B"},
	"Right-Facing Fist": []string{"U1F91C"},
	// hands
	"Clapping Hands":    []string{"U1F44F"},
	"Raising Hands":     []string{"U1F64C"},
	"Open Hands":        []string{"U1F450"},
	"Palms Up Together": []string{"U1F932"},
	"Handshake":         []string{"U1F91D"},
	"Folded Hands":      []string{"U1F64F"},
	// hand-prop
	"Writing Hand": []string{"U270D"},
	"Nail Polish":  []string{"U1F485"},
	"Selfie":       []string{"U1F933"},
	// body-parts
	"Flexed Biceps":        []string{"U1F4AA"},
	"Mechanical Arm":       []string{"U1F9BE"},
	"Mechanical Leg":       []string{"U1F9BF"},
	"Leg":                  []string{"U1F9B5"},
	"Foot":                 []string{"U1F9B6"},
	"Ear":                  []string{"U1F442"},
	"Ear With Hearing Aid": []string{"U1F9BB"},
	"Nose":                 []string{"U1F443"},
	"Brain":                []string{"U1F9E0"},
	"Tooth":                []string{"U1F9B7"},
	"Bone":                 []string{"U1F9B4"},
	"Eyes":                 []string{"U1F440"},
	"Eye":                  []string{"U1F441"},
	"Tongue":               []string{"U1F445"},
	"Mouth":                []string{"U1F444"},
	// person
	"Baby":               []string{"U1F476"},
	"Child":              []string{"U1F9D2"},
	"Boy":                []string{"U1F466"},
	"Girl":               []string{"U1F467"},
	"Person":             []string{"U1F9D1"},
	"Person: Blond Hair": []string{"U1F471"},
	"Man":                []string{"U1F468"},
	"Man: Beard":         []string{"U1F9D4"},
	"Man: Blond Hair":    []string{"U1F471", "U200D", "U2642", "UFE0F"},
	"Man: Red Hair":      []string{"U1F468", "U200D", "U1F9B0"},
	"Man: Curly Hair":    []string{"U1F468", "U200D", "U1F9B1"},
	"Man: White Hair":    []string{"U1F468", "U200D", "U1F9B3"},
	"Man: Bald":          []string{"U1F468", "U200D", "U1F9B2"},
	"Woman":              []string{"U1F469"},
	"Woman: Blond Hair":  []string{"U1F471", "U200D", "U2640", "UFE0F"},
	"Woman: Red Hair":    []string{"U1F469", "U200D", "U1F9B0"},
	"Woman: Curly Hair":  []string{"U1F469", "U200D", "U1F9B1"},
	"Woman: White Hair":  []string{"U1F469", "U200D", "U1F9B3"},
	"Woman: Bald":        []string{"U1F469", "U200D", "U1F9B2"},
	"Older Person":       []string{"U1F9D3"},
	"Old Man":            []string{"U1F474"},
	"Old Woman":          []string{"U1F475"},
	// person-gesture
	"Person Frowning":     []string{"U1F64D"},
	"Man Frowning":        []string{"U1F64D", "U200D", "U2642", "UFE0F"},
	"Woman Frowning":      []string{"U1F64D", "U200D", "U2640", "UFE0F"},
	"Person Pouting":      []string{"U1F64E"},
	"Man Pouting":         []string{"U1F64E", "U200D", "U2642", "UFE0F"},
	"Woman Pouting":       []string{"U1F64E", "U200D", "U2640", "UFE0F"},
	"Person Gesturing NO": []string{"U1F645"},
	"Man Gesturing NO":    []string{"U1F645", "U200D", "U2642", "UFE0F"},
	"Woman Gesturing NO":  []string{"U1F645", "U200D", "U2640", "UFE0F"},
	"Person Gesturing OK": []string{"U1F646"},
	"Man Gesturing OK":    []string{"U1F646", "U200D", "U2642", "UFE0F"},
	"Woman Gesturing OK":  []string{"U1F646", "U200D", "U2640", "UFE0F"},
	"Person Tipping Hand": []string{"U1F481"},
	"Man Tipping Hand":    []string{"U1F481", "U200D", "U2642", "UFE0F"},
	"Woman Tipping Hand":  []string{"U1F481", "U200D", "U2640", "UFE0F"},
	"Person Raising Hand": []string{"U1F64B"},
	"Man Raising Hand":    []string{"U1F64B", "U200D", "U2642", "UFE0F"},
	"Woman Raising Hand":  []string{"U1F64B", "U200D", "U2640", "UFE0F"},
	"Deaf Person":         []string{"U1F9CF"},
	"Deaf Man":            []string{"U1F9CF", "U200D", "U2642", "UFE0F"},
	"Deaf Woman":          []string{"U1F9CF", "U200D", "U2640", "UFE0F"},
	"Person Bowing":       []string{"U1F647"},
	"Man Bowing":          []string{"U1F647", "U200D", "U2642", "UFE0F"},
	"Woman Bowing":        []string{"U1F647", "U200D", "U2640", "UFE0F"},
	"Person Facepalming":  []string{"U1F926"},
	"Man Facepalming":     []string{"U1F926", "U200D", "U2642", "UFE0F"},
	"Woman Facepalming":   []string{"U1F926", "U200D", "U2640", "UFE0F"},
	"Person Shrugging":    []string{"U1F937"},
	"Man Shrugging":       []string{"U1F937", "U200D", "U2642", "UFE0F"},
	"Woman Shrugging":     []string{"U1F937", "U200D", "U2640", "UFE0F"},
	// person-role
	"Man Health Worker":         []string{"U1F468", "U200D", "U2695", "UFE0F"},
	"Woman Health Worker":       []string{"U1F469", "U200D", "U2695", "UFE0F"},
	"Man Student":               []string{"U1F468", "U200D", "U1F393"},
	"Woman Student":             []string{"U1F469", "U200D", "U1F393"},
	"Man Teacher":               []string{"U1F468", "U200D", "U1F3EB"},
	"Woman Teacher":             []string{"U1F469", "U200D", "U1F3EB"},
	"Man Judge":                 []string{"U1F468", "U200D", "U2696", "UFE0F"},
	"Woman Judge":               []string{"U1F469", "U200D", "U2696", "UFE0F"},
	"Man Farmer":                []string{"U1F468", "U200D", "U1F33E"},
	"Woman Farmer":              []string{"U1F469", "U200D", "U1F33E"},
	"Man Cook":                  []string{"U1F468", "U200D", "U1F373"},
	"Woman Cook":                []string{"U1F469", "U200D", "U1F373"},
	"Man Mechanic":              []string{"U1F468", "U200D", "U1F527"},
	"Woman Mechanic":            []string{"U1F469", "U200D", "U1F527"},
	"Man Factory Worker":        []string{"U1F468", "U200D", "U1F3ED"},
	"Woman Factory Worker":      []string{"U1F469", "U200D", "U1F3ED"},
	"Man Office Worker":         []string{"U1F468", "U200D", "U1F4BC"},
	"Woman Office Worker":       []string{"U1F469", "U200D", "U1F4BC"},
	"Man Scientist":             []string{"U1F468", "U200D", "U1F52C"},
	"Woman Scientist":           []string{"U1F469", "U200D", "U1F52C"},
	"Man Technologist":          []string{"U1F468", "U200D", "U1F4BB"},
	"Woman Technologist":        []string{"U1F469", "U200D", "U1F4BB"},
	"Man Singer":                []string{"U1F468", "U200D", "U1F3A4"},
	"Woman Singer":              []string{"U1F469", "U200D", "U1F3A4"},
	"Man Artist":                []string{"U1F468", "U200D", "U1F3A8"},
	"Woman Artist":              []string{"U1F469", "U200D", "U1F3A8"},
	"Man Pilot":                 []string{"U1F468", "U200D", "U2708", "UFE0F"},
	"Woman Pilot":               []string{"U1F469", "U200D", "U2708", "UFE0F"},
	"Man Astronaut":             []string{"U1F468", "U200D", "U1F680"},
	"Woman Astronaut":           []string{"U1F469", "U200D", "U1F680"},
	"Man Firefighter":           []string{"U1F468", "U200D", "U1F692"},
	"Woman Firefighter":         []string{"U1F469", "U200D", "U1F692"},
	"Police Officer":            []string{"U1F46E"},
	"Man Police Officer":        []string{"U1F46E", "U200D", "U2642", "UFE0F"},
	"Woman Police Officer":      []string{"U1F46E", "U200D", "U2640", "UFE0F"},
	"Detective":                 []string{"U1F575"},
	"Man Detective":             []string{"U1F575", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Detective":           []string{"U1F575", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Guard":                     []string{"U1F482"},
	"Man Guard":                 []string{"U1F482", "U200D", "U2642", "UFE0F"},
	"Woman Guard":               []string{"U1F482", "U200D", "U2640", "UFE0F"},
	"Construction Worker":       []string{"U1F477"},
	"Man Construction Worker":   []string{"U1F477", "U200D", "U2642", "UFE0F"},
	"Woman Construction Worker": []string{"U1F477", "U200D", "U2640", "UFE0F"},
	"Prince":                    []string{"U1F934"},
	"Princess":                  []string{"U1F478"},
	"Person Wearing Turban":     []string{"U1F473"},
	"Man Wearing Turban":        []string{"U1F473", "U200D", "U2642", "UFE0F"},
	"Woman Wearing Turban":      []string{"U1F473", "U200D", "U2640", "UFE0F"},
	"Man With Chinese Cap":      []string{"U1F472"},
	"Woman With Headscarf":      []string{"U1F9D5"},
	"Man In Tuxedo":             []string{"U1F935"},
	"Bride With Veil":           []string{"U1F470"},
	"Pregnant Woman":            []string{"U1F930"},
	"Breast-Feeding":            []string{"U1F931"},
	// person-fantasy
	"Baby Angel":         []string{"U1F47C"},
	"Santa Claus":        []string{"U1F385"},
	"Mrs. Claus":         []string{"U1F936"},
	"Superhero":          []string{"U1F9B8"},
	"Man Superhero":      []string{"U1F9B8", "U200D", "U2642", "UFE0F"},
	"Woman Superhero":    []string{"U1F9B8", "U200D", "U2640", "UFE0F"},
	"Supervillain":       []string{"U1F9B9"},
	"Man Supervillain":   []string{"U1F9B9", "U200D", "U2642", "UFE0F"},
	"Woman Supervillain": []string{"U1F9B9", "U200D", "U2640", "UFE0F"},
	"Mage":               []string{"U1F9D9"},
	"Man Mage":           []string{"U1F9D9", "U200D", "U2642", "UFE0F"},
	"Woman Mage":         []string{"U1F9D9", "U200D", "U2640", "UFE0F"},
	"Fairy":              []string{"U1F9DA"},
	"Man Fairy":          []string{"U1F9DA", "U200D", "U2642", "UFE0F"},
	"Woman Fairy":        []string{"U1F9DA", "U200D", "U2640", "UFE0F"},
	"Vampire":            []string{"U1F9DB"},
	"Man Vampire":        []string{"U1F9DB", "U200D", "U2642", "UFE0F"},
	"Woman Vampire":      []string{"U1F9DB", "U200D", "U2640", "UFE0F"},
	"Merperson":          []string{"U1F9DC"},
	"Merman":             []string{"U1F9DC", "U200D", "U2642", "UFE0F"},
	"Mermaid":            []string{"U1F9DC", "U200D", "U2640", "UFE0F"},
	"Elf":                []string{"U1F9DD"},
	"Man Elf":            []string{"U1F9DD", "U200D", "U2642", "UFE0F"},
	"Woman Elf":          []string{"U1F9DD", "U200D", "U2640", "UFE0F"},
	"Genie":              []string{"U1F9DE"},
	"Man Genie":          []string{"U1F9DE", "U200D", "U2642", "UFE0F"},
	"Woman Genie":        []string{"U1F9DE", "U200D", "U2640", "UFE0F"},
	"Zombie":             []string{"U1F9DF"},
	"Man Zombie":         []string{"U1F9DF", "U200D", "U2642", "UFE0F"},
	"Woman Zombie":       []string{"U1F9DF", "U200D", "U2640", "UFE0F"},
	// person-activity
	"Person Getting Massage":        []string{"U1F486"},
	"Man Getting Massage":           []string{"U1F486", "U200D", "U2642", "UFE0F"},
	"Woman Getting Massage":         []string{"U1F486", "U200D", "U2640", "UFE0F"},
	"Person Getting Haircut":        []string{"U1F487"},
	"Man Getting Haircut":           []string{"U1F487", "U200D", "U2642", "UFE0F"},
	"Woman Getting Haircut":         []string{"U1F487", "U200D", "U2640", "UFE0F"},
	"Person Walking":                []string{"U1F6B6"},
	"Man Walking":                   []string{"U1F6B6", "U200D", "U2642", "UFE0F"},
	"Woman Walking":                 []string{"U1F6B6", "U200D", "U2640", "UFE0F"},
	"Person Standing":               []string{"U1F9CD"},
	"Man Standing":                  []string{"U1F9CD", "U200D", "U2642", "UFE0F"},
	"Woman Standing":                []string{"U1F9CD", "U200D", "U2640", "UFE0F"},
	"Person Kneeling":               []string{"U1F9CE"},
	"Man Kneeling":                  []string{"U1F9CE", "U200D", "U2642", "UFE0F"},
	"Woman Kneeling":                []string{"U1F9CE", "U200D", "U2640", "UFE0F"},
	"Man With Probing Cane":         []string{"U1F468", "U200D", "U1F9AF"},
	"Woman With Probing Cane":       []string{"U1F469", "U200D", "U1F9AF"},
	"Man In Motorized Wheelchair":   []string{"U1F468", "U200D", "U1F9BC"},
	"Woman In Motorized Wheelchair": []string{"U1F469", "U200D", "U1F9BC"},
	"Man In Manual Wheelchair":      []string{"U1F468", "U200D", "U1F9BD"},
	"Woman In Manual Wheelchair":    []string{"U1F469", "U200D", "U1F9BD"},
	"Person Running":                []string{"U1F3C3"},
	"Man Running":                   []string{"U1F3C3", "U200D", "U2642", "UFE0F"},
	"Woman Running":                 []string{"U1F3C3", "U200D", "U2640", "UFE0F"},
	"Woman Dancing":                 []string{"U1F483"},
	"Man Dancing":                   []string{"U1F57A"},
	"Man In Suit Levitating":        []string{"U1F574"},
	"People With Bunny Ears":        []string{"U1F46F"},
	"Men With Bunny Ears":           []string{"U1F46F", "U200D", "U2642", "UFE0F"},
	"Women With Bunny Ears":         []string{"U1F46F", "U200D", "U2640", "UFE0F"},
	"Person In Steamy Room":         []string{"U1F9D6"},
	"Man In Steamy Room":            []string{"U1F9D6", "U200D", "U2642", "UFE0F"},
	"Woman In Steamy Room":          []string{"U1F9D6", "U200D", "U2640", "UFE0F"},
	"Person Climbing":               []string{"U1F9D7"},
	"Man Climbing":                  []string{"U1F9D7", "U200D", "U2642", "UFE0F"},
	"Woman Climbing":                []string{"U1F9D7", "U200D", "U2640", "UFE0F"},
	// person-sport
	"Person Fencing":            []string{"U1F93A"},
	"Horse Racing":              []string{"U1F3C7"},
	"Skier":                     []string{"U26F7"},
	"Snowboarder":               []string{"U1F3C2"},
	"Person Golfing":            []string{"U1F3CC"},
	"Man Golfing":               []string{"U1F3CC", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Golfing":             []string{"U1F3CC", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Person Surfing":            []string{"U1F3C4"},
	"Man Surfing":               []string{"U1F3C4", "U200D", "U2642", "UFE0F"},
	"Woman Surfing":             []string{"U1F3C4", "U200D", "U2640", "UFE0F"},
	"Person Rowing Boat":        []string{"U1F6A3"},
	"Man Rowing Boat":           []string{"U1F6A3", "U200D", "U2642", "UFE0F"},
	"Woman Rowing Boat":         []string{"U1F6A3", "U200D", "U2640", "UFE0F"},
	"Person Swimming":           []string{"U1F3CA"},
	"Man Swimming":              []string{"U1F3CA", "U200D", "U2642", "UFE0F"},
	"Woman Swimming":            []string{"U1F3CA", "U200D", "U2640", "UFE0F"},
	"Person Bouncing Ball":      []string{"U26F9"},
	"Man Bouncing Ball":         []string{"U26F9", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Bouncing Ball":       []string{"U26F9", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Person Lifting Weights":    []string{"U1F3CB"},
	"Man Lifting Weights":       []string{"U1F3CB", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Lifting Weights":     []string{"U1F3CB", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Person Biking":             []string{"U1F6B4"},
	"Man Biking":                []string{"U1F6B4", "U200D", "U2642", "UFE0F"},
	"Woman Biking":              []string{"U1F6B4", "U200D", "U2640", "UFE0F"},
	"Person Mountain Biking":    []string{"U1F6B5"},
	"Man Mountain Biking":       []string{"U1F6B5", "U200D", "U2642", "UFE0F"},
	"Woman Mountain Biking":     []string{"U1F6B5", "U200D", "U2640", "UFE0F"},
	"Person Cartwheeling":       []string{"U1F938"},
	"Man Cartwheeling":          []string{"U1F938", "U200D", "U2642", "UFE0F"},
	"Woman Cartwheeling":        []string{"U1F938", "U200D", "U2640", "UFE0F"},
	"People Wrestling":          []string{"U1F93C"},
	"Men Wrestling":             []string{"U1F93C", "U200D", "U2642", "UFE0F"},
	"Women Wrestling":           []string{"U1F93C", "U200D", "U2640", "UFE0F"},
	"Person Playing Water Polo": []string{"U1F93D"},
	"Man Playing Water Polo":    []string{"U1F93D", "U200D", "U2642", "UFE0F"},
	"Woman Playing Water Polo":  []string{"U1F93D", "U200D", "U2640", "UFE0F"},
	"Person Playing Handball":   []string{"U1F93E"},
	"Man Playing Handball":      []string{"U1F93E", "U200D", "U2642", "UFE0F"},
	"Woman Playing Handball":    []string{"U1F93E", "U200D", "U2640", "UFE0F"},
	"Person Juggling":           []string{"U1F939"},
	"Man Juggling":              []string{"U1F939", "U200D", "U2642", "UFE0F"},
	"Woman Juggling":            []string{"U1F939", "U200D", "U2640", "UFE0F"},
	// person-resting
	"Person In Lotus Position": []string{"U1F9D8"},
	"Man In Lotus Position":    []string{"U1F9D8", "U200D", "U2642", "UFE0F"},
	"Woman In Lotus Position":  []string{"U1F9D8", "U200D", "U2640", "UFE0F"},
	"Person Taking Bath":       []string{"U1F6C0"},
	"Person In Bed":            []string{"U1F6CC"},
	// family
	"People Holding Hands":             []string{"U1F9D1", "U200D", "U1F91D", "U200D", "U1F9D1"},
	"Women Holding Hands":              []string{"U1F46D"},
	"Woman And Man Holding Hands":      []string{"U1F46B"},
	"Men Holding Hands":                []string{"U1F46C"},
	"Kiss":                             []string{"U1F48F"},
	"Kiss: Woman, Man":                 []string{"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F48B", "U200D", "U1F468"},
	"Kiss: Man, Man":                   []string{"U1F468", "U200D", "U2764", "UFE0F", "U200D", "U1F48B", "U200D", "U1F468"},
	"Kiss: Woman, Woman":               []string{"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F48B", "U200D", "U1F469"},
	"Couple With Heart":                []string{"U1F491"},
	"Couple With Heart: Woman, Man":    []string{"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F468"},
	"Couple With Heart: Man, Man":      []string{"U1F468", "U200D", "U2764", "UFE0F", "U200D", "U1F468"},
	"Couple With Heart: Woman, Woman":  []string{"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F469"},
	"Family":                           []string{"U1F46A"},
	"Family: Man, Woman, Boy":          []string{"U1F468", "U200D", "U1F469", "U200D", "U1F466"},
	"Family: Man, Woman, Girl":         []string{"U1F468", "U200D", "U1F469", "U200D", "U1F467"},
	"Family: Man, Woman, Girl, Boy":    []string{"U1F468", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Man, Woman, Boy, Boy":     []string{"U1F468", "U200D", "U1F469", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Man, Woman, Girl, Girl":   []string{"U1F468", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Man, Man, Boy":            []string{"U1F468", "U200D", "U1F468", "U200D", "U1F466"},
	"Family: Man, Man, Girl":           []string{"U1F468", "U200D", "U1F468", "U200D", "U1F467"},
	"Family: Man, Man, Girl, Boy":      []string{"U1F468", "U200D", "U1F468", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Man, Man, Boy, Boy":       []string{"U1F468", "U200D", "U1F468", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Man, Man, Girl, Girl":     []string{"U1F468", "U200D", "U1F468", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Woman, Woman, Boy":        []string{"U1F469", "U200D", "U1F469", "U200D", "U1F466"},
	"Family: Woman, Woman, Girl":       []string{"U1F469", "U200D", "U1F469", "U200D", "U1F467"},
	"Family: Woman, Woman, Girl, Boy":  []string{"U1F469", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Woman, Woman, Boy, Boy":   []string{"U1F469", "U200D", "U1F469", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Woman, Woman, Girl, Girl": []string{"U1F469", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Man, Boy":                 []string{"U1F468", "U200D", "U1F466"},
	"Family: Man, Boy, Boy":            []string{"U1F468", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Man, Girl":                []string{"U1F468", "U200D", "U1F467"},
	"Family: Man, Girl, Boy":           []string{"U1F468", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Man, Girl, Girl":          []string{"U1F468", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Woman, Boy":               []string{"U1F469", "U200D", "U1F466"},
	"Family: Woman, Boy, Boy":          []string{"U1F469", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Woman, Girl":              []string{"U1F469", "U200D", "U1F467"},
	"Family: Woman, Girl, Boy":         []string{"U1F469", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Woman, Girl, Girl":        []string{"U1F469", "U200D", "U1F467", "U200D", "U1F467"},
	// person-symbol
	"Speaking Head":       []string{"U1F5E3"},
	"Bust In Silhouette":  []string{"U1F464"},
	"Busts In Silhouette": []string{"U1F465"},
	"Footprints":          []string{"U1F463"},

	// COMPONENT
	// hair-style
	"Red Hair":   []string{"U1F9B0"},
	"Curly Hair": []string{"U1F9B1"},
	"White Hair": []string{"U1F9B3"},
	"Bald":       []string{"U1F9B2"},

	// ANIMALS & NATURE
	// animal-mammal
	"Monkey Face":    []string{"U1F435"},
	"Monkey":         []string{"U1F412"},
	"Gorilla":        []string{"U1F98D"},
	"Orangutan":      []string{"U1F9A7"},
	"Dog Face":       []string{"U1F436"},
	"Dog":            []string{"U1F415"},
	"Guide Dog":      []string{"U1F9AE"},
	"Service Dog":    []string{"U1F415", "U200D", "U1F9BA"},
	"Poodle":         []string{"U1F429"},
	"Wolf":           []string{"U1F43A"},
	"Fox":            []string{"U1F98A"},
	"Raccoon":        []string{"U1F99D"},
	"Cat Face":       []string{"U1F431"},
	"Cat":            []string{"U1F408"},
	"Lion":           []string{"U1F981"},
	"Tiger Face":     []string{"U1F42F"},
	"Tiger":          []string{"U1F405"},
	"Leopard":        []string{"U1F406"},
	"Horse Face":     []string{"U1F434"},
	"Horse":          []string{"U1F40E"},
	"Unicorn":        []string{"U1F984"},
	"Zebra":          []string{"U1F993"},
	"Deer":           []string{"U1F98C"},
	"Cow Face":       []string{"U1F42E"},
	"Ox":             []string{"U1F402"},
	"Water Buffalo":  []string{"U1F403"},
	"Cow":            []string{"U1F404"},
	"Pig Face":       []string{"U1F437"},
	"Pig":            []string{"U1F416"},
	"Boar":           []string{"U1F417"},
	"Pig Nose":       []string{"U1F43D"},
	"Ram":            []string{"U1F40F"},
	"Ewe":            []string{"U1F411"},
	"Goat":           []string{"U1F410"},
	"Camel":          []string{"U1F42A"},
	"Two-Hump Camel": []string{"U1F42B"},
	"Llama":          []string{"U1F999"},
	"Giraffe":        []string{"U1F992"},
	"Elephant":       []string{"U1F418"},
	"Rhinoceros":     []string{"U1F98F"},
	"Hippopotamus":   []string{"U1F99B"},
	"Mouse Face":     []string{"U1F42D"},
	"Mouse":          []string{"U1F401"},
	"Rat":            []string{"U1F400"},
	"Hamster":        []string{"U1F439"},
	"Rabbit Face":    []string{"U1F430"},
	"Rabbit":         []string{"U1F407"},
	"Chipmunk":       []string{"U1F43F"},
	"Hedgehog":       []string{"U1F994"},
	"Bat":            []string{"U1F987"},
	"Bear":           []string{"U1F43B"},
	"Koala":          []string{"U1F428"},
	"Panda":          []string{"U1F43C"},
	"Sloth":          []string{"U1F9A5"},
	"Otter":          []string{"U1F9A6"},
	"Skunk":          []string{"U1F9A8"},
	"Kangaroo":       []string{"U1F998"},
	"Badger":         []string{"U1F9A1"},
	"Paw Prints":     []string{"U1F43E"},
	// animal-bird
	"Turkey [Animal/Food]":    []string{"U1F983"},
	"Chicken":                 []string{"U1F414"},
	"Rooster":                 []string{"U1F413"},
	"Hatching Chick":          []string{"U1F423"},
	"Baby Chick":              []string{"U1F424"},
	"Front-Facing Baby Chick": []string{"U1F425"},
	"Bird":                    []string{"U1F426"},
	"Penguin":                 []string{"U1F427"},
	"Dove":                    []string{"U1F54A"},
	"Eagle":                   []string{"U1F985"},
	"Duck":                    []string{"U1F986"},
	"Swan":                    []string{"U1F9A2"},
	"Owl":                     []string{"U1F989"},
	"Flamingo":                []string{"U1F9A9"},
	"Peacock":                 []string{"U1F99A"},
	"Parrot":                  []string{"U1F99C"},
	// animal-amphibian
	"Frog": []string{"U1F438"},
	// animal-reptile
	"Crocodile":   []string{"U1F40A"},
	"Turtle":      []string{"U1F422"},
	"Lizard":      []string{"U1F98E"},
	"Snake":       []string{"U1F40D"},
	"Dragon Face": []string{"U1F432"},
	"Dragon":      []string{"U1F409"},
	"Sauropod":    []string{"U1F995"},
	"T-Rex":       []string{"U1F996"},
	// animal-marine
	"Spouting Whale": []string{"U1F433"},
	"Whale":          []string{"U1F40B"},
	"Dolphin":        []string{"U1F42C"},
	"Fish":           []string{"U1F41F"},
	"Tropical Fish":  []string{"U1F420"},
	"Blowfish":       []string{"U1F421"},
	"Shark":          []string{"U1F988"},
	"Octopus":        []string{"U1F419"},
	"Spiral Shell":   []string{"U1F41A"},
	// animal-bug
	"Snail":       []string{"U1F40C"},
	"Butterfly":   []string{"U1F98B"},
	"Bug":         []string{"U1F41B"},
	"Ant":         []string{"U1F41C"},
	"Honeybee":    []string{"U1F41D"},
	"Lady Beetle": []string{"U1F41E"},
	"Cricket":     []string{"U1F997"},
	"Spider":      []string{"U1F577"},
	"Spider Web":  []string{"U1F578"},
	"Scorpion":    []string{"U1F982"},
	"Mosquito":    []string{"U1F99F"},
	"Microbe":     []string{"U1F9A0"},
	// plant-flower
	"Bouquet":        []string{"U1F490"},
	"Cherry Blossom": []string{"U1F338"},
	"White Flower":   []string{"U1F4AE"},
	"Rosette":        []string{"U1F3F5"},
	"Rose":           []string{"U1F339"},
	"Wilted Flower":  []string{"U1F940"},
	"Hibiscus":       []string{"U1F33A"},
	"Sunflower":      []string{"U1F33B"},
	"Blossom":        []string{"U1F33C"},
	"Tulip":          []string{"U1F337"},
	// plant-other
	"Seedling":                []string{"U1F331"},
	"Evergreen Tree":          []string{"U1F332"},
	"Deciduous Tree":          []string{"U1F333"},
	"Palm Tree":               []string{"U1F334"},
	"Cactus":                  []string{"U1F335"},
	"Sheaf Of Rice":           []string{"U1F33E"},
	"Herb":                    []string{"U1F33F"},
	"Shamrock":                []string{"U2618"},
	"Four Leaf Clover":        []string{"U1F340"},
	"Maple Leaf":              []string{"U1F341"},
	"Fallen Leaf":             []string{"U1F342"},
	"Leaf Fluttering In Wind": []string{"U1F343"},

	// FOOD & DRINK
	// food-fruit
	"Grapes":      []string{"U1F347"},
	"Melon":       []string{"U1F348"},
	"Watermelon":  []string{"U1F349"},
	"Tangerine":   []string{"U1F34A"},
	"Lemon":       []string{"U1F34B"},
	"Banana":      []string{"U1F34C"},
	"Pineapple":   []string{"U1F34D"},
	"Mango":       []string{"U1F96D"},
	"Red Apple":   []string{"U1F34E"},
	"Green Apple": []string{"U1F34F"},
	"Pear":        []string{"U1F350"},
	"Peach":       []string{"U1F351"},
	"Cherries":    []string{"U1F352"},
	"Strawberry":  []string{"U1F353"},
	"Kiwi Fruit":  []string{"U1F95D"},
	"Tomato":      []string{"U1F345"},
	"Coconut":     []string{"U1F965"},
	// food-vegetable
	"Avocado":     []string{"U1F951"},
	"Eggplant":    []string{"U1F346"},
	"Potato":      []string{"U1F954"},
	"Carrot":      []string{"U1F955"},
	"Ear Of Corn": []string{"U1F33D"},
	"Hot Pepper":  []string{"U1F336"},
	"Cucumber":    []string{"U1F952"},
	"Leafy Green": []string{"U1F96C"},
	"Broccoli":    []string{"U1F966"},
	"Garlic":      []string{"U1F9C4"},
	"Onion":       []string{"U1F9C5"},
	"Mushroom":    []string{"U1F344"},
	"Peanuts":     []string{"U1F95C"},
	"Chestnut":    []string{"U1F330"},
	// food-prepared
	"Bread":               []string{"U1F35E"},
	"Croissant":           []string{"U1F950"},
	"Baguette Bread":      []string{"U1F956"},
	"Pretzel":             []string{"U1F968"},
	"Bagel":               []string{"U1F96F"},
	"Pancakes":            []string{"U1F95E"},
	"Waffle":              []string{"U1F9C7"},
	"Cheese Wedge":        []string{"U1F9C0"},
	"Meat On Bone":        []string{"U1F356"},
	"Poultry Leg":         []string{"U1F357"},
	"Cut Of Meat":         []string{"U1F969"},
	"Bacon":               []string{"U1F953"},
	"Hamburger":           []string{"U1F354"},
	"French Fries":        []string{"U1F35F"},
	"Pizza":               []string{"U1F355"},
	"Hot Dog":             []string{"U1F32D"},
	"Sandwich":            []string{"U1F96A"},
	"Taco":                []string{"U1F32E"},
	"Burrito":             []string{"U1F32F"},
	"Stuffed Flatbread":   []string{"U1F959"},
	"Falafel":             []string{"U1F9C6"},
	"Egg":                 []string{"U1F95A"},
	"Cooking":             []string{"U1F373"},
	"Shallow Pan Of Food": []string{"U1F958"},
	"Pot Of Food":         []string{"U1F372"},
	"Bowl With Spoon":     []string{"U1F963"},
	"Green Salad":         []string{"U1F957"},
	"Popcorn":             []string{"U1F37F"},
	"Butter":              []string{"U1F9C8"},
	"Salt":                []string{"U1F9C2"},
	"Canned Food":         []string{"U1F96B"},
	// food-asian
	"Bento Box":            []string{"U1F371"},
	"Rice Cracker":         []string{"U1F358"},
	"Rice Ball":            []string{"U1F359"},
	"Cooked Rice":          []string{"U1F35A"},
	"Curry Rice":           []string{"U1F35B"},
	"Steaming Bowl":        []string{"U1F35C"},
	"Spaghetti":            []string{"U1F35D"},
	"Roasted Sweet Potato": []string{"U1F360"},
	"Oden":                 []string{"U1F362"},
	"Sushi":                []string{"U1F363"},
	"Fried Shrimp":         []string{"U1F364"},
	"Fish Cake With Swirl": []string{"U1F365"},
	"Moon Cake":            []string{"U1F96E"},
	"Dango":                []string{"U1F361"},
	"Dumpling":             []string{"U1F95F"},
	"Fortune Cookie":       []string{"U1F960"},
	"Takeout Box":          []string{"U1F961"},
	// food-marine
	"Crab":    []string{"U1F980"},
	"Lobster": []string{"U1F99E"},
	"Shrimp":  []string{"U1F990"},
	"Squid":   []string{"U1F991"},
	"Oyster":  []string{"U1F9AA"},
	// food-sweet
	"Soft Ice Cream": []string{"U1F366"},
	"Shaved Ice":     []string{"U1F367"},
	"Ice Cream":      []string{"U1F368"},
	"Doughnut":       []string{"U1F369"},
	"Cookie":         []string{"U1F36A"},
	"Birthday Cake":  []string{"U1F382"},
	"Shortcake":      []string{"U1F370"},
	"Cupcake":        []string{"U1F9C1"},
	"Pie":            []string{"U1F967"},
	"Chocolate Bar":  []string{"U1F36B"},
	"Candy":          []string{"U1F36C"},
	"Lollipop":       []string{"U1F36D"},
	"Custard":        []string{"U1F36E"},
	"Honey Pot":      []string{"U1F36F"},
	// drink
	"Baby Bottle":              []string{"U1F37C"},
	"Glass Of Milk":            []string{"U1F95B"},
	"Hot Beverage":             []string{"U2615"},
	"Teacup Without Handle":    []string{"U1F375"},
	"Sake":                     []string{"U1F376"},
	"Bottle With Popping Cork": []string{"U1F37E"},
	"Wine Glass":               []string{"U1F377"},
	"Cocktail Glass":           []string{"U1F378"},
	"Tropical Drink":           []string{"U1F379"},
	"Beer Mug":                 []string{"U1F37A"},
	"Clinking Beer Mugs":       []string{"U1F37B"},
	"Clinking Glasses":         []string{"U1F942"},
	"Tumbler Glass":            []string{"U1F943"},
	"Cup With Straw":           []string{"U1F964"},
	"Beverage Box":             []string{"U1F9C3"},
	"Mate":                     []string{"U1F9C9"},
	"Ice":                      []string{"U1F9CA"},
	// dishware
	"Chopsticks":                []string{"U1F962"},
	"Fork And Knife With Plate": []string{"U1F37D"},
	"Fork And Knife":            []string{"U1F374"},
	"Spoon":                     []string{"U1F944"},
	"Kitchen Knife":             []string{"U1F52A"},
	"Amphora":                   []string{"U1F3FA"},

	// TRAVEL & PLACES
	// place-map
	"Globe Showing Europe-Africa":  []string{"U1F30D"},
	"Globe Showing Americas":       []string{"U1F30E"},
	"Globe Showing Asia-Australia": []string{"U1F30F"},
	"Globe With Meridians":         []string{"U1F310"},
	"World Map":                    []string{"U1F5FA"},
	"Map Of Japan":                 []string{"U1F5FE"},
	"Compass":                      []string{"U1F9ED"},
	// place-geographic
	"Snow-Capped Mountain": []string{"U1F3D4"},
	"Mountain":             []string{"U26F0"},
	"Volcano":              []string{"U1F30B"},
	"Mount Fuji":           []string{"U1F5FB"},
	"Camping":              []string{"U1F3D5"},
	"Beach With Umbrella":  []string{"U1F3D6"},
	"Desert":               []string{"U1F3DC"},
	"Desert Island":        []string{"U1F3DD"},
	"National Park":        []string{"U1F3DE"},
	// place-building
	"Stadium":               []string{"U1F3DF"},
	"Classical Building":    []string{"U1F3DB"},
	"Building Construction": []string{"U1F3D7"},
	"Brick":                 []string{"U1F9F1"},
	"Houses":                []string{"U1F3D8"},
	"Derelict House":        []string{"U1F3DA"},
	"House":                 []string{"U1F3E0"},
	"House With Garden":     []string{"U1F3E1"},
	"Office Building":       []string{"U1F3E2"},
	"Japanese Post Office":  []string{"U1F3E3"},
	"Post Office":           []string{"U1F3E4"},
	"Hospital":              []string{"U1F3E5"},
	"Bank":                  []string{"U1F3E6"},
	"Hotel":                 []string{"U1F3E8"},
	"Love Hotel":            []string{"U1F3E9"},
	"Convenience Store":     []string{"U1F3EA"},
	"School":                []string{"U1F3EB"},
	"Department Store":      []string{"U1F3EC"},
	"Factory":               []string{"U1F3ED"},
	"Japanese Castle":       []string{"U1F3EF"},
	"Castle":                []string{"U1F3F0"},
	"Wedding":               []string{"U1F492"},
	"Tokyo Tower":           []string{"U1F5FC"},
	"Statue Of Liberty":     []string{"U1F5FD"},
	// place-religious
	"Church":        []string{"U26EA"},
	"Mosque":        []string{"U1F54C"},
	"Hindu Temple":  []string{"U1F6D5"},
	"Synagogue":     []string{"U1F54D"},
	"Shinto Shrine": []string{"U26E9"},
	"Kaaba":         []string{"U1F54B"},
	// place-other
	"Fountain":               []string{"U26F2"},
	"Tent":                   []string{"U26FA"},
	"Foggy":                  []string{"U1F301"},
	"Night With Stars":       []string{"U1F303"},
	"Cityscape":              []string{"U1F3D9"},
	"Sunrise Over Mountains": []string{"U1F304"},
	"Sunrise":                []string{"U1F305"},
	"Cityscape At Dusk":      []string{"U1F306"},
	"Sunset":                 []string{"U1F307"},
	"Bridge At Night":        []string{"U1F309"},
	"Hot Springs":            []string{"U2668"},
	"Carousel Horse":         []string{"U1F3A0"},
	"Ferris Wheel":           []string{"U1F3A1"},
	"Roller Coaster":         []string{"U1F3A2"},
	"Barber Pole":            []string{"U1F488"},
	"Circus Tent":            []string{"U1F3AA"},
	// transport-ground
	"Locomotive":               []string{"U1F682"},
	"Railway Car":              []string{"U1F683"},
	"High-Speed Train":         []string{"U1F684"},
	"Bullet Train":             []string{"U1F685"},
	"Train":                    []string{"U1F686"},
	"Metro":                    []string{"U1F687"},
	"Light Rail":               []string{"U1F688"},
	"Station":                  []string{"U1F689"},
	"Tram":                     []string{"U1F68A"},
	"Monorail":                 []string{"U1F69D"},
	"Mountain Railway":         []string{"U1F69E"},
	"Tram Car":                 []string{"U1F68B"},
	"Bus":                      []string{"U1F68C"},
	"Oncoming Bus":             []string{"U1F68D"},
	"Trolleybus":               []string{"U1F68E"},
	"Minibus":                  []string{"U1F690"},
	"Ambulance":                []string{"U1F691"},
	"Fire Engine":              []string{"U1F692"},
	"Police Car":               []string{"U1F693"},
	"Oncoming Police Car":      []string{"U1F694"},
	"Taxi":                     []string{"U1F695"},
	"Oncoming Taxi":            []string{"U1F696"},
	"Automobile":               []string{"U1F697"},
	"Oncoming Automobile":      []string{"U1F698"},
	"Sport Utility Vehicle":    []string{"U1F699"},
	"Delivery Truck":           []string{"U1F69A"},
	"Articulated Lorry":        []string{"U1F69B"},
	"Tractor":                  []string{"U1F69C"},
	"Racing Car":               []string{"U1F3CE"},
	"Motorcycle":               []string{"U1F3CD"},
	"Motor Scooter":            []string{"U1F6F5"},
	"Manual Wheelchair":        []string{"U1F9BD"},
	"Motorized Wheelchair":     []string{"U1F9BC"},
	"Auto Rickshaw":            []string{"U1F6FA"},
	"Bicycle":                  []string{"U1F6B2"},
	"Kick Scooter":             []string{"U1F6F4"},
	"Skateboard":               []string{"U1F6F9"},
	"Bus Stop":                 []string{"U1F68F"},
	"Motorway":                 []string{"U1F6E3"},
	"Railway Track":            []string{"U1F6E4"},
	"Oil Drum":                 []string{"U1F6E2"},
	"Fuel Pump":                []string{"U26FD"},
	"Police Car Light":         []string{"U1F6A8"},
	"Horizontal Traffic Light": []string{"U1F6A5"},
	"Vertical Traffic Light":   []string{"U1F6A6"},
	"Stop Sign":                []string{"U1F6D1"},
	"Construction":             []string{"U1F6A7"},
	// transport-water
	"Anchor":         []string{"U2693"},
	"Sailboat":       []string{"U26F5"},
	"Canoe":          []string{"U1F6F6"},
	"Speedboat":      []string{"U1F6A4"},
	"Passenger Ship": []string{"U1F6F3"},
	"Ferry":          []string{"U26F4"},
	"Motor Boat":     []string{"U1F6E5"},
	"Ship":           []string{"U1F6A2"},
	// transport-air
	"Airplane":           []string{"U2708"},
	"Small Airplane":     []string{"U1F6E9"},
	"Airplane Departure": []string{"U1F6EB"},
	"Airplane Arrival":   []string{"U1F6EC"},
	"Parachute":          []string{"U1FA82"},
	"Seat":               []string{"U1F4BA"},
	"Helicopter":         []string{"U1F681"},
	"Suspension Railway": []string{"U1F69F"},
	"Mountain Cableway":  []string{"U1F6A0"},
	"Aerial Tramway":     []string{"U1F6A1"},
	"Satellite":          []string{"U1F6F0"},
	"Rocket":             []string{"U1F680"},
	"Flying Saucer":      []string{"U1F6F8"},
	// hotel
	"Bellhop Bell": []string{"U1F6CE"},
	"Luggage":      []string{"U1F9F3"},
	// time
	"Hourglass Done":     []string{"U231B"},
	"Hourglass Not Done": []string{"U23F3"},
	"Watch":              []string{"U231A"},
	"Alarm Clock":        []string{"U23F0"},
	"Stopwatch":          []string{"U23F1"},
	"Timer Clock":        []string{"U23F2"},
	"Mantelpiece Clock":  []string{"U1F570"},
	"Twelve O’Clock":     []string{"U1F55B"},
	"Twelve-Thirty":      []string{"U1F567"},
	"One O’Clock":        []string{"U1F550"},
	"One-Thirty":         []string{"U1F55C"},
	"Two O’Clock":        []string{"U1F551"},
	"Two-Thirty":         []string{"U1F55D"},
	"Three O’Clock":      []string{"U1F552"},
	"Three-Thirty":       []string{"U1F55E"},
	"Four O’Clock":       []string{"U1F553"},
	"Four-Thirty":        []string{"U1F55F"},
	"Five O’Clock":       []string{"U1F554"},
	"Five-Thirty":        []string{"U1F560"},
	"Six O’Clock":        []string{"U1F555"},
	"Six-Thirty":         []string{"U1F561"},
	"Seven O’Clock":      []string{"U1F556"},
	"Seven-Thirty":       []string{"U1F562"},
	"Eight O’Clock":      []string{"U1F557"},
	"Eight-Thirty":       []string{"U1F563"},
	"Nine O’Clock":       []string{"U1F558"},
	"Nine-Thirty":        []string{"U1F564"},
	"Ten O’Clock":        []string{"U1F559"},
	"Ten-Thirty":         []string{"U1F565"},
	"Eleven O’Clock":     []string{"U1F55A"},
	"Eleven-Thirty":      []string{"U1F566"},
	// sky-and-weather
	"New Moon":                      []string{"U1F311"},
	"Waxing Crescent Moon":          []string{"U1F312"},
	"First Quarter Moon":            []string{"U1F313"},
	"Waxing Gibbous Moon":           []string{"U1F314"},
	"Full Moon":                     []string{"U1F315"},
	"Waning Gibbous Moon":           []string{"U1F316"},
	"Last Quarter Moon":             []string{"U1F317"},
	"Waning Crescent Moon":          []string{"U1F318"},
	"Crescent Moon":                 []string{"U1F319"},
	"New Moon Face":                 []string{"U1F31A"},
	"First Quarter Moon Face":       []string{"U1F31B"},
	"Last Quarter Moon Face":        []string{"U1F31C"},
	"Thermometer":                   []string{"U1F321"},
	"Sun":                           []string{"U2600"},
	"Full Moon Face":                []string{"U1F31D"},
	"Sun With Face":                 []string{"U1F31E"},
	"Ringed Planet":                 []string{"U1FA90"},
	"Star":                          []string{"U2B50"},
	"Glowing Star":                  []string{"U1F31F"},
	"Shooting Star":                 []string{"U1F320"},
	"Milky Way":                     []string{"U1F30C"},
	"Cloud":                         []string{"U2601"},
	"Sun Behind Cloud":              []string{"U26C5"},
	"Cloud With Lightning And Rain": []string{"U26C8"},
	"Sun Behind Small Cloud":        []string{"U1F324"},
	"Sun Behind Large Cloud":        []string{"U1F325"},
	"Sun Behind Rain Cloud":         []string{"U1F326"},
	"Cloud With Rain":               []string{"U1F327"},
	"Cloud With Snow":               []string{"U1F328"},
	"Cloud With Lightning":          []string{"U1F329"},
	"Tornado":                       []string{"U1F32A"},
	"Fog":                           []string{"U1F32B"},
	"Wind Face":                     []string{"U1F32C"},
	"Cyclone":                       []string{"U1F300"},
	"Rainbow":                       []string{"U1F308"},
	"Closed Umbrella":               []string{"U1F302"},
	"Umbrella":                      []string{"U2602"},
	"Umbrella With Rain Drops":      []string{"U2614"},
	"Umbrella On Ground":            []string{"U26F1"},
	"High Voltage":                  []string{"U26A1"},
	"Snowflake":                     []string{"U2744"},
	"Snowman":                       []string{"U2603"},
	"Snowman Without Snow":          []string{"U26C4"},
	"Comet":                         []string{"U2604"},
	"Fire":                          []string{"U1F525"},
	"Droplet":                       []string{"U1F4A7"},
	"Water Wave":                    []string{"U1F30A"},

	// Activities
	// event
	"Jack-O-Lantern":        []string{"U1F383"},
	"Christmas Tree":        []string{"U1F384"},
	"Fireworks":             []string{"U1F386"},
	"Sparkler":              []string{"U1F387"},
	"Firecracker":           []string{"U1F9E8"},
	"Sparkles":              []string{"U2728"},
	"Balloon":               []string{"U1F388"},
	"Party Popper":          []string{"U1F389"},
	"Confetti Ball":         []string{"U1F38A"},
	"Tanabata Tree":         []string{"U1F38B"},
	"Pine Decoration":       []string{"U1F38D"},
	"Japanese Dolls":        []string{"U1F38E"},
	"Carp Streamer":         []string{"U1F38F"},
	"Wind Chime":            []string{"U1F390"},
	"Moon Viewing Ceremony": []string{"U1F391"},
	"Red Envelope":          []string{"U1F9E7"},
	"Ribbon":                []string{"U1F380"},
	"Wrapped Gift":          []string{"U1F381"},
	"Reminder Ribbon":       []string{"U1F397"},
	"Admission Tickets":     []string{"U1F39F"},
	"Ticket":                []string{"U1F3AB"},
	// award-medal
	"Military Medal":  []string{"U1F396"},
	"Trophy":          []string{"U1F3C6"},
	"Sports Medal":    []string{"U1F3C5"},
	"1st Place Medal": []string{"U1F947"},
	"2nd Place Medal": []string{"U1F948"},
	"3rd Place Medal": []string{"U1F949"},
	// sport
	"Soccer Ball":          []string{"U26BD"},
	"Baseball":             []string{"U26BE"},
	"Softball":             []string{"U1F94E"},
	"Basketball":           []string{"U1F3C0"},
	"Volleyball":           []string{"U1F3D0"},
	"American Football":    []string{"U1F3C8"},
	"Rugby Football":       []string{"U1F3C9"},
	"Tennis":               []string{"U1F3BE"},
	"Flying Disc":          []string{"U1F94F"},
	"Bowling":              []string{"U1F3B3"},
	"Cricket Game":         []string{"U1F3CF"},
	"Field Hockey":         []string{"U1F3D1"},
	"Ice Hockey":           []string{"U1F3D2"},
	"Lacrosse":             []string{"U1F94D"},
	"Ping Pong":            []string{"U1F3D3"},
	"Badminton":            []string{"U1F3F8"},
	"Boxing Glove":         []string{"U1F94A"},
	"Martial Arts Uniform": []string{"U1F94B"},
	"Goal Net":             []string{"U1F945"},
	"Flag In Hole":         []string{"U26F3"},
	"Ice Skate":            []string{"U26F8"},
	"Fishing Pole":         []string{"U1F3A3"},
	"Diving Mask":          []string{"U1F93F"},
	"Running Shirt":        []string{"U1F3BD"},
	"Skis":                 []string{"U1F3BF"},
	"Sled":                 []string{"U1F6F7"},
	"Curling Stone":        []string{"U1F94C"},
	// game
	"Direct Hit":           []string{"U1F3AF"},
	"Yo-Yo":                []string{"U1FA80"},
	"Kite":                 []string{"U1FA81"},
	"Pool 8 Ball":          []string{"U1F3B1"},
	"Crystal Ball":         []string{"U1F52E"},
	"Nazar Amulet":         []string{"U1F9FF"},
	"Video Game":           []string{"U1F3AE"},
	"Joystick":             []string{"U1F579"},
	"Slot Machine":         []string{"U1F3B0"},
	"Game Die":             []string{"U1F3B2"},
	"Puzzle Piece":         []string{"U1F9E9"},
	"Teddy Bear":           []string{"U1F9F8"},
	"Spade Suit":           []string{"U2660"},
	"Heart Suit":           []string{"U2665"},
	"Diamond Suit":         []string{"U2666"},
	"Club Suit":            []string{"U2663"},
	"Chess Pawn":           []string{"U265F"},
	"Joker":                []string{"U1F0CF"},
	"Mahjong Red Dragon":   []string{"U1F004"},
	"Flower Playing Cards": []string{"U1F3B4"},
	// arts-and-crafts
	"Performing Arts": []string{"U1F3AD"},
	"Framed Picture":  []string{"U1F5BC"},
	"Artist Palette":  []string{"U1F3A8"},
	"Thread":          []string{"U1F9F5"},
	"Yarn":            []string{"U1F9F6"},

	// OBJECTS
	// clothing
	"Glasses":                []string{"U1F453"},
	"Sunglasses":             []string{"U1F576"},
	"Goggles":                []string{"U1F97D"},
	"Lab Coat":               []string{"U1F97C"},
	"Safety Vest":            []string{"U1F9BA"},
	"Necktie":                []string{"U1F454"},
	"T-Shirt":                []string{"U1F455"},
	"Jeans":                  []string{"U1F456"},
	"Scarf":                  []string{"U1F9E3"},
	"Gloves":                 []string{"U1F9E4"},
	"Coat":                   []string{"U1F9E5"},
	"Socks":                  []string{"U1F9E6"},
	"Dress":                  []string{"U1F457"},
	"Kimono":                 []string{"U1F458"},
	"Sari":                   []string{"U1F97B"},
	"One-Piece Swimsuit":     []string{"U1FA71"},
	"Briefs":                 []string{"U1FA72"},
	"Shorts":                 []string{"U1FA73"},
	"Bikini":                 []string{"U1F459"},
	"Woman’s Clothes":        []string{"U1F45A"},
	"Purse":                  []string{"U1F45B"},
	"Handbag":                []string{"U1F45C"},
	"Clutch Bag":             []string{"U1F45D"},
	"Shopping Bags":          []string{"U1F6CD"},
	"Backpack":               []string{"U1F392"},
	"Man’s Shoe":             []string{"U1F45E"},
	"Running Shoe":           []string{"U1F45F"},
	"Hiking Boot":            []string{"U1F97E"},
	"Flat Shoe":              []string{"U1F97F"},
	"High-Heeled Shoe":       []string{"U1F460"},
	"Woman’s Sandal":         []string{"U1F461"},
	"Ballet Shoes":           []string{"U1FA70"},
	"Woman’s Boot":           []string{"U1F462"},
	"Crown":                  []string{"U1F451"},
	"Woman’s Hat":            []string{"U1F452"},
	"Top Hat":                []string{"U1F3A9"},
	"Graduation Cap":         []string{"U1F393"},
	"Billed Cap":             []string{"U1F9E2"},
	"Rescue Worker’s Helmet": []string{"U26D1"},
	"Prayer Beads":           []string{"U1F4FF"},
	"Lipstick":               []string{"U1F484"},
	"Ring":                   []string{"U1F48D"},
	"Gem Stone":              []string{"U1F48E"},
	// sound
	"Muted Speaker":         []string{"U1F507"},
	"Speaker Low Volume":    []string{"U1F508"},
	"Speaker Medium Volume": []string{"U1F509"},
	"Speaker High Volume":   []string{"U1F50A"},
	"Loudspeaker":           []string{"U1F4E2"},
	"Megaphone":             []string{"U1F4E3"},
	"Postal Horn":           []string{"U1F4EF"},
	"Bell":                  []string{"U1F514"},
	"Bell With Slash":       []string{"U1F515"},
	// music
	"Musical Score":     []string{"U1F3BC"},
	"Musical Note":      []string{"U1F3B5"},
	"Musical Notes":     []string{"U1F3B6"},
	"Studio Microphone": []string{"U1F399"},
	"Level Slider":      []string{"U1F39A"},
	"Control Knobs":     []string{"U1F39B"},
	"Microphone":        []string{"U1F3A4"},
	"Headphone":         []string{"U1F3A7"},
	"Radio":             []string{"U1F4FB"},
	// musical-instrument
	"Saxophone":        []string{"U1F3B7"},
	"Guitar":           []string{"U1F3B8"},
	"Musical Keyboard": []string{"U1F3B9"},
	"Trumpet":          []string{"U1F3BA"},
	"Violin":           []string{"U1F3BB"},
	"Banjo":            []string{"U1FA95"},
	"Drum":             []string{"U1F941"},
	// phone
	"Mobile Phone":            []string{"U1F4F1"},
	"Mobile Phone With Arrow": []string{"U1F4F2"},
	"Telephone":               []string{"U260E"},
	"Telephone Receiver":      []string{"U1F4DE"},
	"Pager":                   []string{"U1F4DF"},
	"Fax Machine":             []string{"U1F4E0"},
	// computer
	"Battery":          []string{"U1F50B"},
	"Electric Plug":    []string{"U1F50C"},
	"Laptop Computer":  []string{"U1F4BB"},
	"Desktop Computer": []string{"U1F5A5"},
	"Printer":          []string{"U1F5A8"},
	"Keyboard":         []string{"U2328"},
	"Computer Mouse":   []string{"U1F5B1"},
	"Trackball":        []string{"U1F5B2"},
	"Computer Disk":    []string{"U1F4BD"},
	"Floppy Disk":      []string{"U1F4BE"},
	"Optical Disk":     []string{"U1F4BF"},
	"Dvd":              []string{"U1F4C0"},
	"Abacus":           []string{"U1F9EE"},
	// light-and-video
	"Movie Camera":                  []string{"U1F3A5"},
	"Film Frames":                   []string{"U1F39E"},
	"Film Projector":                []string{"U1F4FD"},
	"Clapper Board":                 []string{"U1F3AC"},
	"Television":                    []string{"U1F4FA"},
	"Camera":                        []string{"U1F4F7"},
	"Camera With Flash":             []string{"U1F4F8"},
	"Video Camera":                  []string{"U1F4F9"},
	"Videocassette":                 []string{"U1F4FC"},
	"Magnifying Glass Tilted Left":  []string{"U1F50D"},
	"Magnifying Glass Tilted Right": []string{"U1F50E"},
	"Candle":                        []string{"U1F56F"},
	"Light Bulb":                    []string{"U1F4A1"},
	"Flashlight":                    []string{"U1F526"},
	"Red Paper Lantern":             []string{"U1F3EE"},
	"Diya Lamp":                     []string{"U1FA94"},
	// book-paper
	"Notebook With Decorative Cover": []string{"U1F4D4"},
	"Closed Book":                    []string{"U1F4D5"},
	"Open Book":                      []string{"U1F4D6"},
	"Green Book":                     []string{"U1F4D7"},
	"Blue Book":                      []string{"U1F4D8"},
	"Orange Book":                    []string{"U1F4D9"},
	"Books":                          []string{"U1F4DA"},
	"Notebook":                       []string{"U1F4D3"},
	"Ledger":                         []string{"U1F4D2"},
	"Page With Curl":                 []string{"U1F4C3"},
	"Scroll":                         []string{"U1F4DC"},
	"Page Facing Up":                 []string{"U1F4C4"},
	"Newspaper":                      []string{"U1F4F0"},
	"Rolled-Up Newspaper":            []string{"U1F5DE"},
	"Bookmark Tabs":                  []string{"U1F4D1"},
	"Bookmark":                       []string{"U1F516"},
	"Label":                          []string{"U1F3F7"},
	// money
	"Money Bag":                 []string{"U1F4B0"},
	"Yen Banknote":              []string{"U1F4B4"},
	"Dollar Banknote":           []string{"U1F4B5"},
	"Euro Banknote":             []string{"U1F4B6"},
	"Pound Banknote":            []string{"U1F4B7"},
	"Money With Wings":          []string{"U1F4B8"},
	"Credit Card":               []string{"U1F4B3"},
	"Receipt":                   []string{"U1F9FE"},
	"Chart Increasing With Yen": []string{"U1F4B9"},
	"Currency Exchange":         []string{"U1F4B1"},
	"Heavy Dollar Sign":         []string{"U1F4B2"},
	// mail
	"Envelope":                         []string{"U2709"},
	"E-Mail":                           []string{"U1F4E7"},
	"Incoming Envelope":                []string{"U1F4E8"},
	"Envelope With Arrow":              []string{"U1F4E9"},
	"Outbox Tray":                      []string{"U1F4E4"},
	"Inbox Tray":                       []string{"U1F4E5"},
	"Package":                          []string{"U1F4E6"},
	"Closed Mailbox With Raised Flag":  []string{"U1F4EB"},
	"Closed Mailbox With Lowered Flag": []string{"U1F4EA"},
	"Open Mailbox With Raised Flag":    []string{"U1F4EC"},
	"Open Mailbox With Lowered Flag":   []string{"U1F4ED"},
	"Postbox":                          []string{"U1F4EE"},
	"Ballot Box With Ballot":           []string{"U1F5F3"},
	// writing
	"Pencil":       []string{"U270F"},
	"Black Nib":    []string{"U2712"},
	"Fountain Pen": []string{"U1F58B"},
	"Pen":          []string{"U1F58A"},
	"Paintbrush":   []string{"U1F58C"},
	"Crayon":       []string{"U1F58D"},
	"Memo":         []string{"U1F4DD"},
	// office
	"Briefcase":           []string{"U1F4BC"},
	"File Folder":         []string{"U1F4C1"},
	"Open File Folder":    []string{"U1F4C2"},
	"Card Index Dividers": []string{"U1F5C2"},
	"Calendar":            []string{"U1F4C5"},
	"Tear-Off Calendar":   []string{"U1F4C6"},
	"Spiral Notepad":      []string{"U1F5D2"},
	"Spiral Calendar":     []string{"U1F5D3"},
	"Card Index":          []string{"U1F4C7"},
	"Chart Increasing":    []string{"U1F4C8"},
	"Chart Decreasing":    []string{"U1F4C9"},
	"Bar Chart":           []string{"U1F4CA"},
	"Clipboard":           []string{"U1F4CB"},
	"Pushpin":             []string{"U1F4CC"},
	"Round Pushpin":       []string{"U1F4CD"},
	"Paperclip":           []string{"U1F4CE"},
	"Linked Paperclips":   []string{"U1F587"},
	"Straight Ruler":      []string{"U1F4CF"},
	"Triangular Ruler":    []string{"U1F4D0"},
	"Scissors":            []string{"U2702"},
	"Card File Box":       []string{"U1F5C3"},
	"File Cabinet":        []string{"U1F5C4"},
	"Wastebasket":         []string{"U1F5D1"},
	// lock
	"Locked":          []string{"U1F512"},
	"Unlocked":        []string{"U1F513"},
	"Locked With Pen": []string{"U1F50F"},
	"Locked With Key": []string{"U1F510"},
	"Key":             []string{"U1F511"},
	"Old Key":         []string{"U1F5DD"},
	// tool
	"Hammer":            []string{"U1F528"},
	"Axe":               []string{"U1FA93"},
	"Pick":              []string{"U26CF"},
	"Hammer And Pick":   []string{"U2692"},
	"Hammer And Wrench": []string{"U1F6E0"},
	"Dagger":            []string{"U1F5E1"},
	"Crossed Swords":    []string{"U2694"},
	"Pistol":            []string{"U1F52B"},
	"Bow And Arrow":     []string{"U1F3F9"},
	"Shield":            []string{"U1F6E1"},
	"Wrench":            []string{"U1F527"},
	"Nut And Bolt":      []string{"U1F529"},
	"Gear":              []string{"U2699"},
	"Clamp":             []string{"U1F5DC"},
	"Balance Scale":     []string{"U2696"},
	"Probing Cane":      []string{"U1F9AF"},
	"Link":              []string{"U1F517"},
	"Chains":            []string{"U26D3"},
	"Toolbox":           []string{"U1F9F0"},
	"Magnet":            []string{"U1F9F2"},
	// science
	"Alembic":           []string{"U2697"},
	"Test Tube":         []string{"U1F9EA"},
	"Petri Dish":        []string{"U1F9EB"},
	"Dna":               []string{"U1F9EC"},
	"Microscope":        []string{"U1F52C"},
	"Telescope":         []string{"U1F52D"},
	"Satellite Antenna": []string{"U1F4E1"},
	// medical
	"Syringe":          []string{"U1F489"},
	"Drop Of Blood":    []string{"U1FA78"},
	"Pill":             []string{"U1F48A"},
	"Adhesive Bandage": []string{"U1FA79"},
	"Stethoscope":      []string{"U1FA7A"},
	// household
	"Door":              []string{"U1F6AA"},
	"Bed":               []string{"U1F6CF"},
	"Couch And Lamp":    []string{"U1F6CB"},
	"Chair":             []string{"U1FA91"},
	"Toilet":            []string{"U1F6BD"},
	"Shower":            []string{"U1F6BF"},
	"Bathtub":           []string{"U1F6C1"},
	"Razor":             []string{"U1FA92"},
	"Lotion Bottle":     []string{"U1F9F4"},
	"Safety Pin":        []string{"U1F9F7"},
	"Broom":             []string{"U1F9F9"},
	"Basket":            []string{"U1F9FA"},
	"Roll Of Paper":     []string{"U1F9FB"},
	"Soap":              []string{"U1F9FC"},
	"Sponge":            []string{"U1F9FD"},
	"Fire Extinguisher": []string{"U1F9EF"},
	"Shopping Cart":     []string{"U1F6D2"},
	// other-object
	"Cigarette":   []string{"U1F6AC"},
	"Coffin":      []string{"U26B0"},
	"Funeral Urn": []string{"U26B1"},
	"Moai":        []string{"U1F5FF"},

	// SYMBOLS
	// transport-sign
	"ATM Sign":           []string{"U1F3E7"},
	"Litter In Bin Sign": []string{"U1F6AE"},
	"Potable Water":      []string{"U1F6B0"},
	"Wheelchair Symbol":  []string{"U267F"},
	"Men’s Room":         []string{"U1F6B9"},
	"Women’s Room":       []string{"U1F6BA"},
	"Restroom":           []string{"U1F6BB"},
	"Baby Symbol":        []string{"U1F6BC"},
	"Water Closet":       []string{"U1F6BE"},
	"Passport Control":   []string{"U1F6C2"},
	"Customs":            []string{"U1F6C3"},
	"Baggage Claim":      []string{"U1F6C4"},
	"Left Luggage":       []string{"U1F6C5"},
	// warning
	"Warning":               []string{"U26A0"},
	"Children Crossing":     []string{"U1F6B8"},
	"No Entry":              []string{"U26D4"},
	"Prohibited":            []string{"U1F6AB"},
	"No Bicycles":           []string{"U1F6B3"},
	"No Smoking":            []string{"U1F6AD"},
	"No Littering":          []string{"U1F6AF"},
	"Non-Potable Water":     []string{"U1F6B1"},
	"No Pedestrians":        []string{"U1F6B7"},
	"No Mobile Phones":      []string{"U1F4F5"},
	"No One Under Eighteen": []string{"U1F51E"},
	"Radioactive":           []string{"U2622"},
	"Biohazard":             []string{"U2623"},
	// arrow
	"Up Arrow":                       []string{"U2B06"},
	"Up-Right Arrow":                 []string{"U2197"},
	"Right Arrow":                    []string{"U27A1"},
	"Down-Right Arrow":               []string{"U2198"},
	"Down Arrow":                     []string{"U2B07"},
	"Down-Left Arrow":                []string{"U2199"},
	"Left Arrow":                     []string{"U2B05"},
	"Up-Left Arrow":                  []string{"U2196"},
	"Up-Down Arrow":                  []string{"U2195"},
	"Left-Right Arrow":               []string{"U2194"},
	"Right Arrow Curving Left":       []string{"U21A9"},
	"Left Arrow Curving Right":       []string{"U21AA"},
	"Right Arrow Curving Up":         []string{"U2934"},
	"Right Arrow Curving Down":       []string{"U2935"},
	"Clockwise Vertical Arrows":      []string{"U1F503"},
	"Counterclockwise Arrows Button": []string{"U1F504"},
	"BACK Arrow":                     []string{"U1F519"},
	"END Arrow":                      []string{"U1F51A"},
	"ON! Arrow":                      []string{"U1F51B"},
	"SOON Arrow":                     []string{"U1F51C"},
	"TOP Arrow":                      []string{"U1F51D"},
	// religion
	"Place Of Worship":        []string{"U1F6D0"},
	"Atom Symbol":             []string{"U269B"},
	"Om":                      []string{"U1F549"},
	"Star Of David":           []string{"U2721"},
	"Wheel Of Dharma":         []string{"U2638"},
	"Yin Yang":                []string{"U262F"},
	"Latin Cross":             []string{"U271D"},
	"Orthodox Cross":          []string{"U2626"},
	"Star And Crescent":       []string{"U262A"},
	"Peace Symbol":            []string{"U262E"},
	"Menorah":                 []string{"U1F54E"},
	"Dotted Six-Pointed Star": []string{"U1F52F"},
	// zodiac
	"Aries":       []string{"U2648"},
	"Taurus":      []string{"U2649"},
	"Gemini":      []string{"U264A"},
	"Cancer":      []string{"U264B"},
	"Leo":         []string{"U264C"},
	"Virgo":       []string{"U264D"},
	"Libra":       []string{"U264E"},
	"Scorpio":     []string{"U264F"},
	"Sagittarius": []string{"U2650"},
	"Capricorn":   []string{"U2651"},
	"Aquarius":    []string{"U2652"},
	"Pisces":      []string{"U2653"},
	"Ophiuchus":   []string{"U26CE"},
	// av-symbol
	"Shuffle Tracks Button": []string{"U1F500"},
	"Repeat Button":         []string{"U1F501"},
	"Repeat Single Button":  []string{"U1F502"},
	"Play Button":           []string{"U25B6"},
	"Fast-Forward Button":   []string{"U23E9"},
	"Next Track Button":     []string{"U23ED"},
	"Play Or Pause Button":  []string{"U23EF"},
	"Reverse Button":        []string{"U25C0"},
	"Fast Reverse Button":   []string{"U23EA"},
	"Last Track Button":     []string{"U23EE"},
	"Upwards Button":        []string{"U1F53C"},
	"Fast Up Button":        []string{"U23EB"},
	"Downwards Button":      []string{"U1F53D"},
	"Fast Down Button":      []string{"U23EC"},
	"Pause Button":          []string{"U23F8"},
	"Stop Button":           []string{"U23F9"},
	"Record Button":         []string{"U23FA"},
	"Eject Button":          []string{"U23CF"},
	"Cinema":                []string{"U1F3A6"},
	"Dim Button":            []string{"U1F505"},
	"Bright Button":         []string{"U1F506"},
	"Antenna Bars":          []string{"U1F4F6"},
	"Vibration Mode":        []string{"U1F4F3"},
	"Mobile Phone Off":      []string{"U1F4F4"},
	// gender
	"Female Sign": []string{"U2640"},
	"Male Sign":   []string{"U2642"},
	// other-symbol
	"Medical Symbol":               []string{"U2695"},
	"Infinity":                     []string{"U267E"},
	"Recycling Symbol":             []string{"U267B"},
	"Fleur-De-Lis":                 []string{"U269C"},
	"Trident Emblem":               []string{"U1F531"},
	"Name Badge":                   []string{"U1F4DB"},
	"Japanese Symbol For Beginner": []string{"U1F530"},
	"Hollow Red Circle":            []string{"U2B55"},
	"Check Mark Button":            []string{"U2705"},
	"Check Box With Check":         []string{"U2611"},
	"Check Mark":                   []string{"U2714"},
	"Multiplication Sign":          []string{"U2716"},
	"Cross Mark":                   []string{"U274C"},
	"Cross Mark Button":            []string{"U274E"},
	"Plus Sign":                    []string{"U2795"},
	"Minus Sign":                   []string{"U2796"},
	"Division Sign":                []string{"U2797"},
	"Curly Loop":                   []string{"U27B0"},
	"Double Curly Loop":            []string{"U27BF"},
	"Part Alternation Mark":        []string{"U303D"},
	"Eight-Spoked Asterisk":        []string{"U2733"},
	"Eight-Pointed Star":           []string{"U2734"},
	"Sparkle":                      []string{"U2747"},
	"Double Exclamation Mark":      []string{"U203C"},
	"Exclamation Question Mark":    []string{"U2049"},
	"Question Mark":                []string{"U2753"},
	"White Question Mark":          []string{"U2754"},
	"White Exclamation Mark":       []string{"U2755"},
	"Exclamation Mark":             []string{"U2757"},
	"Wavy Dash":                    []string{"U3030"},
	"Copyright":                    []string{"U00A9"},
	"Registered":                   []string{"U00AE"},
	"Trade Mark":                   []string{"U2122"},
	// keycap
	"Keycap: #":  []string{"U0023", "UFE0F", "U20E3"},
	"Keycap: *":  []string{"U002A", "UFE0F", "U20E3"},
	"Keycap: 0":  []string{"U0030", "UFE0F", "U20E3"},
	"Keycap: 1":  []string{"U0031", "UFE0F", "U20E3"},
	"Keycap: 2":  []string{"U0032", "UFE0F", "U20E3"},
	"Keycap: 3":  []string{"U0033", "UFE0F", "U20E3"},
	"Keycap: 4":  []string{"U0034", "UFE0F", "U20E3"},
	"Keycap: 5":  []string{"U0035", "UFE0F", "U20E3"},
	"Keycap: 6":  []string{"U0036", "UFE0F", "U20E3"},
	"Keycap: 7":  []string{"U0037", "UFE0F", "U20E3"},
	"Keycap: 8":  []string{"U0038", "UFE0F", "U20E3"},
	"Keycap: 9":  []string{"U0039", "UFE0F", "U20E3"},
	"Keycap: 10": []string{"U1F51F"},
	// alphanum
	"Input Latin Uppercase":            []string{"U1F520"},
	"Input Latin Lowercase":            []string{"U1F521"},
	"Input Numbers":                    []string{"U1F522"},
	"Input Symbols":                    []string{"U1F523"},
	"Input Latin Letters":              []string{"U1F524"},
	"A Button (Blood Type)":            []string{"U1F170"},
	"AB Button (Blood Type)":           []string{"U1F18E"},
	"B Button (Blood Type)":            []string{"U1F171"},
	"CL Button":                        []string{"U1F191"},
	"COOL Button":                      []string{"U1F192"},
	"FREE Button":                      []string{"U1F193"},
	"Information":                      []string{"U2139"},
	"ID Button":                        []string{"U1F194"},
	"Circled M":                        []string{"U24C2"},
	"NEW Button":                       []string{"U1F195"},
	"NG Button":                        []string{"U1F196"},
	"O Button (Blood Type)":            []string{"U1F17E"},
	"OK Button":                        []string{"U1F197"},
	"P Button":                         []string{"U1F17F"},
	"SOS Button":                       []string{"U1F198"},
	"UP! Button":                       []string{"U1F199"},
	"VS Button":                        []string{"U1F19A"},
	"Japanese “here” Button":           []string{"U1F201"},
	"Japanese “service Charge” Button": []string{"U1F202"},
	"Japanese “monthly Amount” Button": []string{"U1F237"},
	"Japanese “not Free Of Charge” Button": []string{"U1F236"},
	"Japanese “reserved” Button":           []string{"U1F22F"},
	"Japanese “bargain” Button":            []string{"U1F250"},
	"Japanese “discount” Button":           []string{"U1F239"},
	"Japanese “free Of Charge” Button":     []string{"U1F21A"},
	"Japanese “prohibited” Button":         []string{"U1F232"},
	"Japanese “acceptable” Button":         []string{"U1F251"},
	"Japanese “application” Button":        []string{"U1F238"},
	"Japanese “passing Grade” Button":      []string{"U1F234"},
	"Japanese “vacancy” Button":            []string{"U1F233"},
	"Japanese “congratulations” Button":    []string{"U3297"},
	"Japanese “secret” Button":             []string{"U3299"},
	"Japanese “open For Business” Button":  []string{"U1F23A"},
	"Japanese “no Vacancy” Button":         []string{"U1F235"},
	// geometric
	"Red Circle":                []string{"U1F534"},
	"Orange Circle":             []string{"U1F7E0"},
	"Yellow Circle":             []string{"U1F7E1"},
	"Green Circle":              []string{"U1F7E2"},
	"Blue Circle":               []string{"U1F535"},
	"Purple Circle":             []string{"U1F7E3"},
	"Brown Circle":              []string{"U1F7E4"},
	"Black Circle":              []string{"U26AB"},
	"White Circle":              []string{"U26AA"},
	"Red Square":                []string{"U1F7E5"},
	"Orange Square":             []string{"U1F7E7"},
	"Yellow Square":             []string{"U1F7E8"},
	"Green Square":              []string{"U1F7E9"},
	"Blue Square":               []string{"U1F7E6"},
	"Purple Square":             []string{"U1F7EA"},
	"Brown Square":              []string{"U1F7EB"},
	"Black Large Square":        []string{"U2B1B"},
	"White Large Square":        []string{"U2B1C"},
	"Black Medium Square":       []string{"U25FC"},
	"White Medium Square":       []string{"U25FB"},
	"Black Medium-Small Square": []string{"U25FE"},
	"White Medium-Small Square": []string{"U25FD"},
	"Black Small Square":        []string{"U25AA"},
	"White Small Square":        []string{"U25AB"},
	"Large Orange Diamond":      []string{"U1F536"},
	"Large Blue Diamond":        []string{"U1F537"},
	"Small Orange Diamond":      []string{"U1F538"},
	"Small Blue Diamond":        []string{"U1F539"},
	"Red Triangle Pointed Up":   []string{"U1F53A"},
	"Red Triangle Pointed Down": []string{"U1F53B"},
	"Diamond With A Dot":        []string{"U1F4A0"},
	"Radio Button":              []string{"U1F518"},
	"White Square Button":       []string{"U1F533"},
	"Black Square Button":       []string{"U1F532"},

	// FLAGS
	// flag
	"Chequered Flag":  []string{"U1F3C1"},
	"Triangular Flag": []string{"U1F6A9"},
	"Crossed Flags":   []string{"U1F38C"},
	"Black Flag":      []string{"U1F3F4"},
	"White Flag":      []string{"U1F3F3"},
	"Rainbow Flag":    []string{"U1F3F3", "UFE0F", "U200D", "U1F308"},
	"Pirate Flag":     []string{"U1F3F4", "U200D", "U2620", "UFE0F"},
	// country-flag
	"Ascension Island":                       []string{"U1F1E6", "U1F1E8"},
	"Andorra":                                []string{"U1F1E6", "U1F1E9"},
	"United Arab Emirates":                   []string{"U1F1E6", "U1F1EA"},
	"Afghanistan":                            []string{"U1F1E6", "U1F1EB"},
	"Antigua & Barbuda":                      []string{"U1F1E6", "U1F1EC"},
	"Anguilla":                               []string{"U1F1E6", "U1F1EE"},
	"Albania":                                []string{"U1F1E6", "U1F1F1"},
	"Armenia":                                []string{"U1F1E6", "U1F1F2"},
	"Angola":                                 []string{"U1F1E6", "U1F1F4"},
	"Antarctica":                             []string{"U1F1E6", "U1F1F6"},
	"Argentina":                              []string{"U1F1E6", "U1F1F7"},
	"American Samoa":                         []string{"U1F1E6", "U1F1F8"},
	"Austria":                                []string{"U1F1E6", "U1F1F9"},
	"Australia":                              []string{"U1F1E6", "U1F1FA"},
	"Aruba":                                  []string{"U1F1E6", "U1F1FC"},
	"Åland Islands":                          []string{"U1F1E6", "U1F1FD"},
	"Azerbaijan":                             []string{"U1F1E6", "U1F1FF"},
	"Bosnia & Herzegovina":                   []string{"U1F1E7", "U1F1E6"},
	"Barbados":                               []string{"U1F1E7", "U1F1E7"},
	"Bangladesh":                             []string{"U1F1E7", "U1F1E9"},
	"Belgium":                                []string{"U1F1E7", "U1F1EA"},
	"Burkina Faso":                           []string{"U1F1E7", "U1F1EB"},
	"Bulgaria":                               []string{"U1F1E7", "U1F1EC"},
	"Bahrain":                                []string{"U1F1E7", "U1F1ED"},
	"Burundi":                                []string{"U1F1E7", "U1F1EE"},
	"Benin":                                  []string{"U1F1E7", "U1F1EF"},
	"St. Barthélemy":                         []string{"U1F1E7", "U1F1F1"},
	"Bermuda":                                []string{"U1F1E7", "U1F1F2"},
	"Brunei":                                 []string{"U1F1E7", "U1F1F3"},
	"Bolivia":                                []string{"U1F1E7", "U1F1F4"},
	"Caribbean Netherlands":                  []string{"U1F1E7", "U1F1F6"},
	"Brazil":                                 []string{"U1F1E7", "U1F1F7"},
	"Bahamas":                                []string{"U1F1E7", "U1F1F8"},
	"Bhutan":                                 []string{"U1F1E7", "U1F1F9"},
	"Bouvet Island":                          []string{"U1F1E7", "U1F1FB"},
	"Botswana":                               []string{"U1F1E7", "U1F1FC"},
	"Belarus":                                []string{"U1F1E7", "U1F1FE"},
	"Belize":                                 []string{"U1F1E7", "U1F1FF"},
	"Canada":                                 []string{"U1F1E8", "U1F1E6"},
	"Cocos (Keeling) Islands":                []string{"U1F1E8", "U1F1E8"},
	"Congo - Kinshasa":                       []string{"U1F1E8", "U1F1E9"},
	"Central African Republic":               []string{"U1F1E8", "U1F1EB"},
	"Congo - Brazzaville":                    []string{"U1F1E8", "U1F1EC"},
	"Switzerland":                            []string{"U1F1E8", "U1F1ED"},
	"Côte D’Ivoire":                          []string{"U1F1E8", "U1F1EE"},
	"Cook Islands":                           []string{"U1F1E8", "U1F1F0"},
	"Chile":                                  []string{"U1F1E8", "U1F1F1"},
	"Cameroon":                               []string{"U1F1E8", "U1F1F2"},
	"China":                                  []string{"U1F1E8", "U1F1F3"},
	"Colombia":                               []string{"U1F1E8", "U1F1F4"},
	"Clipperton Island":                      []string{"U1F1E8", "U1F1F5"},
	"Costa Rica":                             []string{"U1F1E8", "U1F1F7"},
	"Cuba":                                   []string{"U1F1E8", "U1F1FA"},
	"Cape Verde":                             []string{"U1F1E8", "U1F1FB"},
	"Curaçao":                                []string{"U1F1E8", "U1F1FC"},
	"Christmas Island":                       []string{"U1F1E8", "U1F1FD"},
	"Cyprus":                                 []string{"U1F1E8", "U1F1FE"},
	"Czechia":                                []string{"U1F1E8", "U1F1FF"},
	"Germany":                                []string{"U1F1E9", "U1F1EA"},
	"Diego Garcia":                           []string{"U1F1E9", "U1F1EC"},
	"Djibouti":                               []string{"U1F1E9", "U1F1EF"},
	"Denmark":                                []string{"U1F1E9", "U1F1F0"},
	"Dominica":                               []string{"U1F1E9", "U1F1F2"},
	"Dominican Republic":                     []string{"U1F1E9", "U1F1F4"},
	"Algeria":                                []string{"U1F1E9", "U1F1FF"},
	"Ceuta & Melilla":                        []string{"U1F1EA", "U1F1E6"},
	"Ecuador":                                []string{"U1F1EA", "U1F1E8"},
	"Estonia":                                []string{"U1F1EA", "U1F1EA"},
	"Egypt":                                  []string{"U1F1EA", "U1F1EC"},
	"Western Sahara":                         []string{"U1F1EA", "U1F1ED"},
	"Eritrea":                                []string{"U1F1EA", "U1F1F7"},
	"Spain":                                  []string{"U1F1EA", "U1F1F8"},
	"Ethiopia":                               []string{"U1F1EA", "U1F1F9"},
	"European Union":                         []string{"U1F1EA", "U1F1FA"},
	"Finland":                                []string{"U1F1EB", "U1F1EE"},
	"Fiji":                                   []string{"U1F1EB", "U1F1EF"},
	"Falkland Islands":                       []string{"U1F1EB", "U1F1F0"},
	"Micronesia":                             []string{"U1F1EB", "U1F1F2"},
	"Faroe Islands":                          []string{"U1F1EB", "U1F1F4"},
	"France":                                 []string{"U1F1EB", "U1F1F7"},
	"Gabon":                                  []string{"U1F1EC", "U1F1E6"},
	"United Kingdom":                         []string{"U1F1EC", "U1F1E7"},
	"Grenada":                                []string{"U1F1EC", "U1F1E9"},
	"Georgia":                                []string{"U1F1EC", "U1F1EA"},
	"French Guiana":                          []string{"U1F1EC", "U1F1EB"},
	"Guernsey":                               []string{"U1F1EC", "U1F1EC"},
	"Ghana":                                  []string{"U1F1EC", "U1F1ED"},
	"Gibraltar":                              []string{"U1F1EC", "U1F1EE"},
	"Greenland":                              []string{"U1F1EC", "U1F1F1"},
	"Gambia":                                 []string{"U1F1EC", "U1F1F2"},
	"Guinea":                                 []string{"U1F1EC", "U1F1F3"},
	"Guadeloupe":                             []string{"U1F1EC", "U1F1F5"},
	"Equatorial Guinea":                      []string{"U1F1EC", "U1F1F6"},
	"Greece":                                 []string{"U1F1EC", "U1F1F7"},
	"South Georgia & South Sandwich Islands": []string{"U1F1EC", "U1F1F8"},
	"Guatemala":                              []string{"U1F1EC", "U1F1F9"},
	"Guam":                                   []string{"U1F1EC", "U1F1FA"},
	"Guinea-Bissau":                          []string{"U1F1EC", "U1F1FC"},
	"Guyana":                                 []string{"U1F1EC", "U1F1FE"},
	"Hong Kong SAR China":                    []string{"U1F1ED", "U1F1F0"},
	"Heard & McDonald Islands":               []string{"U1F1ED", "U1F1F2"},
	"Honduras":                               []string{"U1F1ED", "U1F1F3"},
	"Croatia":                                []string{"U1F1ED", "U1F1F7"},
	"Haiti":                                  []string{"U1F1ED", "U1F1F9"},
	"Hungary":                                []string{"U1F1ED", "U1F1FA"},
	"Canary Islands":                         []string{"U1F1EE", "U1F1E8"},
	"Indonesia":                              []string{"U1F1EE", "U1F1E9"},
	"Ireland":                                []string{"U1F1EE", "U1F1EA"},
	"Israel":                                 []string{"U1F1EE", "U1F1F1"},
	"Isle Of Man":                            []string{"U1F1EE", "U1F1F2"},
	"India":                                  []string{"U1F1EE", "U1F1F3"},
	"British Indian Ocean Territory":         []string{"U1F1EE", "U1F1F4"},
	"Iraq":                                   []string{"U1F1EE", "U1F1F6"},
	"Iran":                                   []string{"U1F1EE", "U1F1F7"},
	"Iceland":                                []string{"U1F1EE", "U1F1F8"},
	"Italy":                                  []string{"U1F1EE", "U1F1F9"},
	"Jersey":                                 []string{"U1F1EF", "U1F1EA"},
	"Jamaica":                                []string{"U1F1EF", "U1F1F2"},
	"Jordan":                                 []string{"U1F1EF", "U1F1F4"},
	"Japan":                                  []string{"U1F1EF", "U1F1F5"},
	"Kenya":                                  []string{"U1F1F0", "U1F1EA"},
	"Kyrgyzstan":                             []string{"U1F1F0", "U1F1EC"},
	"Cambodia":                               []string{"U1F1F0", "U1F1ED"},
	"Kiribati":                               []string{"U1F1F0", "U1F1EE"},
	"Comoros":                                []string{"U1F1F0", "U1F1F2"},
	"St. Kitts & Nevis":                      []string{"U1F1F0", "U1F1F3"},
	"North Korea":                            []string{"U1F1F0", "U1F1F5"},
	"South Korea":                            []string{"U1F1F0", "U1F1F7"},
	"Kuwait":                                 []string{"U1F1F0", "U1F1FC"},
	"Cayman Islands":                         []string{"U1F1F0", "U1F1FE"},
	"Kazakhstan":                             []string{"U1F1F0", "U1F1FF"},
	"Laos":                                   []string{"U1F1F1", "U1F1E6"},
	"Lebanon":                                []string{"U1F1F1", "U1F1E7"},
	"St. Lucia":                              []string{"U1F1F1", "U1F1E8"},
	"Liechtenstein":                          []string{"U1F1F1", "U1F1EE"},
	"Sri Lanka":                              []string{"U1F1F1", "U1F1F0"},
	"Liberia":                                []string{"U1F1F1", "U1F1F7"},
	"Lesotho":                                []string{"U1F1F1", "U1F1F8"},
	"Lithuania":                              []string{"U1F1F1", "U1F1F9"},
	"Luxembourg":                             []string{"U1F1F1", "U1F1FA"},
	"Latvia":                                 []string{"U1F1F1", "U1F1FB"},
	"Libya":                                  []string{"U1F1F1", "U1F1FE"},
	"Morocco":                                []string{"U1F1F2", "U1F1E6"},
	"Monaco":                                 []string{"U1F1F2", "U1F1E8"},
	"Moldova":                                []string{"U1F1F2", "U1F1E9"},
	"Montenegro":                             []string{"U1F1F2", "U1F1EA"},
	"St. Martin":                             []string{"U1F1F2", "U1F1EB"},
	"Madagascar":                             []string{"U1F1F2", "U1F1EC"},
	"Marshall Islands":                       []string{"U1F1F2", "U1F1ED"},
	"North Macedonia":                        []string{"U1F1F2", "U1F1F0"},
	"Mali":                                   []string{"U1F1F2", "U1F1F1"},
	"Myanmar (Burma)":                        []string{"U1F1F2", "U1F1F2"},
	"Mongolia":                               []string{"U1F1F2", "U1F1F3"},
	"Macao SAR China":                        []string{"U1F1F2", "U1F1F4"},
	"Northern Mariana Islands":               []string{"U1F1F2", "U1F1F5"},
	"Martinique":                             []string{"U1F1F2", "U1F1F6"},
	"Mauritania":                             []string{"U1F1F2", "U1F1F7"},
	"Montserrat":                             []string{"U1F1F2", "U1F1F8"},
	"Malta":                                  []string{"U1F1F2", "U1F1F9"},
	"Mauritius":                              []string{"U1F1F2", "U1F1FA"},
	"Maldives":                               []string{"U1F1F2", "U1F1FB"},
	"Malawi":                                 []string{"U1F1F2", "U1F1FC"},
	"Mexico":                                 []string{"U1F1F2", "U1F1FD"},
	"Malaysia":                               []string{"U1F1F2", "U1F1FE"},
	"Mozambique":                             []string{"U1F1F2", "U1F1FF"},
	"Namibia":                                []string{"U1F1F3", "U1F1E6"},
	"New Caledonia":                          []string{"U1F1F3", "U1F1E8"},
	"Niger":                                  []string{"U1F1F3", "U1F1EA"},
	"Norfolk Island":                         []string{"U1F1F3", "U1F1EB"},
	"Nigeria":                                []string{"U1F1F3", "U1F1EC"},
	"Nicaragua":                              []string{"U1F1F3", "U1F1EE"},
	"Netherlands":                            []string{"U1F1F3", "U1F1F1"},
	"Norway":                                 []string{"U1F1F3", "U1F1F4"},
	"Nepal":                                  []string{"U1F1F3", "U1F1F5"},
	"Nauru":                                  []string{"U1F1F3", "U1F1F7"},
	"Niue":                                   []string{"U1F1F3", "U1F1FA"},
	"New Zealand":                            []string{"U1F1F3", "U1F1FF"},
	"Oman":                                   []string{"U1F1F4", "U1F1F2"},
	"Panama":                                 []string{"U1F1F5", "U1F1E6"},
	"Peru":                                   []string{"U1F1F5", "U1F1EA"},
	"French Polynesia":                       []string{"U1F1F5", "U1F1EB"},
	"Papua New Guinea":                       []string{"U1F1F5", "U1F1EC"},
	"Philippines":                            []string{"U1F1F5", "U1F1ED"},
	"Pakistan":                               []string{"U1F1F5", "U1F1F0"},
	"Poland":                                 []string{"U1F1F5", "U1F1F1"},
	"St. Pierre & Miquelon":                  []string{"U1F1F5", "U1F1F2"},
	"Pitcairn Islands":                       []string{"U1F1F5", "U1F1F3"},
	"Puerto Rico":                            []string{"U1F1F5", "U1F1F7"},
	"Palestinian Territories":                []string{"U1F1F5", "U1F1F8"},
	"Portugal":                               []string{"U1F1F5", "U1F1F9"},
	"Palau":                                  []string{"U1F1F5", "U1F1FC"},
	"Paraguay":                               []string{"U1F1F5", "U1F1FE"},
	"Qatar":                                  []string{"U1F1F6", "U1F1E6"},
	"Réunion":                                []string{"U1F1F7", "U1F1EA"},
	"Romania":                                []string{"U1F1F7", "U1F1F4"},
	"Serbia":                                 []string{"U1F1F7", "U1F1F8"},
	"Russia":                                 []string{"U1F1F7", "U1F1FA"},
	"Rwanda":                                 []string{"U1F1F7", "U1F1FC"},
	"Saudi Arabia":                           []string{"U1F1F8", "U1F1E6"},
	"Solomon Islands":                        []string{"U1F1F8", "U1F1E7"},
	"Seychelles":                             []string{"U1F1F8", "U1F1E8"},
	"Sudan":                                  []string{"U1F1F8", "U1F1E9"},
	"Sweden":                                 []string{"U1F1F8", "U1F1EA"},
	"Singapore":                              []string{"U1F1F8", "U1F1EC"},
	"St. Helena":                             []string{"U1F1F8", "U1F1ED"},
	"Slovenia":                               []string{"U1F1F8", "U1F1EE"},
	"Svalbard & Jan Mayen":                   []string{"U1F1F8", "U1F1EF"},
	"Slovakia":                               []string{"U1F1F8", "U1F1F0"},
	"Sierra Leone":                           []string{"U1F1F8", "U1F1F1"},
	"San Marino":                             []string{"U1F1F8", "U1F1F2"},
	"Senegal":                                []string{"U1F1F8", "U1F1F3"},
	"Somalia":                                []string{"U1F1F8", "U1F1F4"},
	"Suriname":                               []string{"U1F1F8", "U1F1F7"},
	"South Sudan":                            []string{"U1F1F8", "U1F1F8"},
	"São Tomé & Príncipe":                    []string{"U1F1F8", "U1F1F9"},
	"El Salvador":                            []string{"U1F1F8", "U1F1FB"},
	"Sint Maarten":                           []string{"U1F1F8", "U1F1FD"},
	"Syria":                                  []string{"U1F1F8", "U1F1FE"},
	"Eswatini":                               []string{"U1F1F8", "U1F1FF"},
	"Tristan Da Cunha":                       []string{"U1F1F9", "U1F1E6"},
	"Turks & Caicos Islands":                 []string{"U1F1F9", "U1F1E8"},
	"Chad":                                   []string{"U1F1F9", "U1F1E9"},
	"French Southern Territories":            []string{"U1F1F9", "U1F1EB"},
	"Togo":                                   []string{"U1F1F9", "U1F1EC"},
	"Thailand":                               []string{"U1F1F9", "U1F1ED"},
	"Tajikistan":                             []string{"U1F1F9", "U1F1EF"},
	"Tokelau":                                []string{"U1F1F9", "U1F1F0"},
	"Timor-Leste":                            []string{"U1F1F9", "U1F1F1"},
	"Turkmenistan":                           []string{"U1F1F9", "U1F1F2"},
	"Tunisia":                                []string{"U1F1F9", "U1F1F3"},
	"Tonga":                                  []string{"U1F1F9", "U1F1F4"},
	"Turkey [Flag]":                          []string{"U1F1F9", "U1F1F7"},
	"Trinidad & Tobago":                      []string{"U1F1F9", "U1F1F9"},
	"Tuvalu":                                 []string{"U1F1F9", "U1F1FB"},
	"Taiwan":                                 []string{"U1F1F9", "U1F1FC"},
	"Tanzania":                               []string{"U1F1F9", "U1F1FF"},
	"Ukraine":                                []string{"U1F1FA", "U1F1E6"},
	"Uganda":                                 []string{"U1F1FA", "U1F1EC"},
	"U.S. Outlying Islands":                  []string{"U1F1FA", "U1F1F2"},
	"United Nations":                         []string{"U1F1FA", "U1F1F3"},
	"United States":                          []string{"U1F1FA", "U1F1F8"},
	"Uruguay":                                []string{"U1F1FA", "U1F1FE"},
	"Uzbekistan":                             []string{"U1F1FA", "U1F1FF"},
	"Vatican City":                           []string{"U1F1FB", "U1F1E6"},
	"St. Vincent & Grenadines":               []string{"U1F1FB", "U1F1E8"},
	"Venezuela":                              []string{"U1F1FB", "U1F1EA"},
	"British Virgin Islands":                 []string{"U1F1FB", "U1F1EC"},
	"U.S. Virgin Islands":                    []string{"U1F1FB", "U1F1EE"},
	"Vietnam":                                []string{"U1F1FB", "U1F1F3"},
	"Vanuatu":                                []string{"U1F1FB", "U1F1FA"},
	"Wallis & Futuna":                        []string{"U1F1FC", "U1F1EB"},
	"Samoa":                                  []string{"U1F1FC", "U1F1F8"},
	"Kosovo":                                 []string{"U1F1FD", "U1F1F0"},
	"Yemen":                                  []string{"U1F1FE", "U1F1EA"},
	"Mayotte":                                []string{"U1F1FE", "U1F1F9"},
	"South Africa":                           []string{"U1F1FF", "U1F1E6"},
	"Zambia":                                 []string{"U1F1FF", "U1F1F2"},
	"Zimbabwe":                               []string{"U1F1FF", "U1F1FC"},
	"England":                                []string{"U1F3F4", "UE0067", "UE0062", "UE0065", "UE006E", "UE0067", "UE007F"},
	"Scotland":                               []string{"U1F3F4", "UE0067", "UE0062", "UE0073", "UE0063", "UE0074", "UE007F"},
	"Wales":                                  []string{"U1F3F4", "UE0067", "UE0062", "UE0077", "UE006C", "UE0073", "UE007F"},

	// SKIN TONES
	"Light Skin Tone":        []string{"U1F3FB"},
	"Medium-Light Skin Tone": []string{"U1F3FC"},
	"Medium Skin Tone":       []string{"U1F3FD"},
	"Medium-Dark Skin Tone":  []string{"U1F3FE"},
	"Dark Skin Tone":         []string{"U1F3FF"},

	// MODIFIERS
	"Zero-Width Joiner": []string{"U200D"},
	"Emoji Style":       []string{"UFE0F"},
	"Text Style":        []string{"UFE0E"},
}
