package main

var emojiToCodepoints = map[string][]string{
	// SMILEYS & EMOTION
	// face-smiling
	"Grinning Face":                   {"U1F600"},
	"Grinning Face With Big Eyes":     {"U1F603"},
	"Grinning Face With Smiling Eyes": {"U1F604"},
	"Beaming Face With Smiling Eyes":  {"U1F601"},
	"Grinning Squinting Face":         {"U1F606"},
	"Grinning Face With Sweat":        {"U1F605"},
	"Rolling On The Floor Laughing":   {"U1F923"},
	"Face With Tears Of Joy":          {"U1F602"},
	"Slightly Smiling Face":           {"U1F642"},
	"Upside-Down Face":                {"U1F643"},
	"Winking Face":                    {"U1F609"},
	"Smiling Face With Smiling Eyes":  {"U1F60A"},
	"Smiling Face With Halo":          {"U1F607"},
	// face-affection
	"Smiling Face With Hearts":       {"U1F970"},
	"Smiling Face With Heart-Eyes":   {"U1F60D"},
	"Star-Struck":                    {"U1F929"},
	"Face Blowing A Kiss":            {"U1F618"},
	"Kissing Face":                   {"U1F617"},
	"Smiling Face":                   {"U263A"},
	"Kissing Face With Closed Eyes":  {"U1F61A"},
	"Kissing Face With Smiling Eyes": {"U1F619"},
	// face-tongue
	"Face Savoring Food":         {"U1F60B"},
	"Face With Tongue":           {"U1F61B"},
	"Winking Face With Tongue":   {"U1F61C"},
	"Zany Face":                  {"U1F92A"},
	"Squinting Face With Tongue": {"U1F61D"},
	"Money-Mouth Face":           {"U1F911"},
	// face-hand
	"Hugging Face":              {"U1F917"},
	"Face With Hand Over Mouth": {"U1F92D"},
	"Shushing Face":             {"U1F92B"},
	"Thinking Face":             {"U1F914"},
	// face-neutral-skeptical
	"Zipper-Mouth Face":        {"U1F910"},
	"Face With Raised Eyebrow": {"U1F928"},
	"Neutral Face":             {"U1F610"},
	"Expressionless Face":      {"U1F611"},
	"Face Without Mouth":       {"U1F636"},
	"Smirking Face":            {"U1F60F"},
	"Unamused Face":            {"U1F612"},
	"Face With Rolling Eyes":   {"U1F644"},
	"Grimacing Face":           {"U1F62C"},
	"Lying Face":               {"U1F925"},
	// face-sleepy
	"Relieved Face": {"U1F60C"},
	"Pensive Face":  {"U1F614"},
	"Sleepy Face":   {"U1F62A"},
	"Drooling Face": {"U1F924"},
	"Sleeping Face": {"U1F634"},
	// face-unwell
	"Face With Medical Mask": {"U1F637"},
	"Face With Thermometer":  {"U1F912"},
	"Face With Head-Bandage": {"U1F915"},
	"Nauseated Face":         {"U1F922"},
	"Face Vomiting":          {"U1F92E"},
	"Sneezing Face":          {"U1F927"},
	"Hot Face":               {"U1F975"},
	"Cold Face":              {"U1F976"},
	"Woozy Face":             {"U1F974"},
	"Dizzy Face":             {"U1F635"},
	"Exploding Head":         {"U1F92F"},
	// face-hat
	"Cowboy Hat Face": {"U1F920"},
	"Partying Face":   {"U1F973"},
	// face-glasses
	"Smiling Face With Sunglasses": {"U1F60E"},
	"Nerd Face":                    {"U1F913"},
	"Face With Monocle":            {"U1F9D0"},
	// face-concerned
	"Confused Face":                 {"U1F615"},
	"Worried Face":                  {"U1F61F"},
	"Slightly Frowning Face":        {"U1F641"},
	"Frowning Face":                 {"U2639"},
	"Face With Open Mouth":          {"U1F62E"},
	"Hushed Face":                   {"U1F62F"},
	"Astonished Face":               {"U1F632"},
	"Flushed Face":                  {"U1F633"},
	"Pleading Face":                 {"U1F97A"},
	"Frowning Face With Open Mouth": {"U1F626"},
	"Anguished Face":                {"U1F627"},
	"Fearful Face":                  {"U1F628"},
	"Anxious Face With Sweat":       {"U1F630"},
	"Sad But Relieved Face":         {"U1F625"},
	"Crying Face":                   {"U1F622"},
	"Loudly Crying Face":            {"U1F62D"},
	"Face Screaming In Fear":        {"U1F631"},
	"Confounded Face":               {"U1F616"},
	"Persevering Face":              {"U1F623"},
	"Disappointed Face":             {"U1F61E"},
	"Downcast Face With Sweat":      {"U1F613"},
	"Weary Face":                    {"U1F629"},
	"Tired Face":                    {"U1F62B"},
	"Yawning Face":                  {"U1F971"},
	// face-negative
	"Face With Steam From Nose":  {"U1F624"},
	"Pouting Face":               {"U1F621"},
	"Angry Face":                 {"U1F620"},
	"Face With Symbols On Mouth": {"U1F92C"},
	"Smiling Face With Horns":    {"U1F608"},
	"Angry Face With Horns":      {"U1F47F"},
	"Skull":                      {"U1F480"},
	"Skull And Crossbones":       {"U2620"},
	// face-costume
	"Pile Of Poo":   {"U1F4A9"},
	"Clown Face":    {"U1F921"},
	"Ogre":          {"U1F479"},
	"Goblin":        {"U1F47A"},
	"Ghost":         {"U1F47B"},
	"Alien":         {"U1F47D"},
	"Alien Monster": {"U1F47E"},
	"Robot":         {"U1F916"},
	// cat-face
	"Grinning Cat":                   {"U1F63A"},
	"Grinning Cat With Smiling Eyes": {"U1F638"},
	"Cat With Tears Of Joy":          {"U1F639"},
	"Smiling Cat With Heart-Eyes":    {"U1F63B"},
	"Cat With Wry Smile":             {"U1F63C"},
	"Kissing Cat":                    {"U1F63D"},
	"Weary Cat":                      {"U1F640"},
	"Crying Cat":                     {"U1F63F"},
	"Pouting Cat":                    {"U1F63E"},
	// monkey-face
	"See-No-Evil Monkey":   {"U1F648"},
	"Hear-No-Evil Monkey":  {"U1F649"},
	"Speak-No-Evil Monkey": {"U1F64A"},
	// emotion
	"Kiss Mark":            {"U1F48B"},
	"Love Letter":          {"U1F48C"},
	"Heart With Arrow":     {"U1F498"},
	"Heart With Ribbon":    {"U1F49D"},
	"Sparkling Heart":      {"U1F496"},
	"Growing Heart":        {"U1F497"},
	"Beating Heart":        {"U1F493"},
	"Revolving Hearts":     {"U1F49E"},
	"Two Hearts":           {"U1F495"},
	"Heart Decoration":     {"U1F49F"},
	"Heart Exclamation":    {"U2763"},
	"Broken Heart":         {"U1F494"},
	"Red Heart":            {"U2764"},
	"Orange Heart":         {"U1F9E1"},
	"Yellow Heart":         {"U1F49B"},
	"Green Heart":          {"U1F49A"},
	"Blue Heart":           {"U1F499"},
	"Purple Heart":         {"U1F49C"},
	"Brown Heart":          {"U1F90E"},
	"Black Heart":          {"U1F5A4"},
	"White Heart":          {"U1F90D"},
	"Hundred Points":       {"U1F4AF"},
	"Anger Symbol":         {"U1F4A2"},
	"Collision":            {"U1F4A5"},
	"Dizzy":                {"U1F4AB"},
	"Sweat Droplets":       {"U1F4A6"},
	"Dashing Away":         {"U1F4A8"},
	"Hole":                 {"U1F573"},
	"Bomb":                 {"U1F4A3"},
	"Speech Balloon":       {"U1F4AC"},
	"Eye In Speech Bubble": {"U1F441", "UFE0F", "U200D", "U1F5E8", "UFE0F"},
	"Left Speech Bubble":   {"U1F5E8"},
	"Right Anger Bubble":   {"U1F5EF"},
	"Thought Balloon":      {"U1F4AD"},
	"Zzz":                  {"U1F4A4"},

	// PEOPLE & BODY
	// hand-fingers-open
	"Waving Hand":               {"U1F44B"},
	"Raised Back Of Hand":       {"U1F91A"},
	"Hand With Fingers Splayed": {"U1F590"},
	"Raised Hand":               {"U270B"},
	"Vulcan Salute":             {"U1F596"},
	// hand-fingers-partial
	"OK Hand":           {"U1F44C"},
	"Pinching Hand":     {"U1F90F"},
	"Victory Hand":      {"U270C"},
	"Crossed Fingers":   {"U1F91E"},
	"Love-You Gesture":  {"U1F91F"},
	"Sign Of The Horns": {"U1F918"},
	"Call Me Hand":      {"U1F919"},
	// hand-single-finger
	"Backhand Index Pointing Left":  {"U1F448"},
	"Backhand Index Pointing Right": {"U1F449"},
	"Backhand Index Pointing Up":    {"U1F446"},
	"Middle Finger":                 {"U1F595"},
	"Backhand Index Pointing Down":  {"U1F447"},
	"Index Pointing Up":             {"U261D"},
	// hand-fingers-closed
	"Thumbs Up":         {"U1F44D"},
	"Thumbs Down":       {"U1F44E"},
	"Raised Fist":       {"U270A"},
	"Oncoming Fist":     {"U1F44A"},
	"Left-Facing Fist":  {"U1F91B"},
	"Right-Facing Fist": {"U1F91C"},
	// hands
	"Clapping Hands":    {"U1F44F"},
	"Raising Hands":     {"U1F64C"},
	"Open Hands":        {"U1F450"},
	"Palms Up Together": {"U1F932"},
	"Handshake":         {"U1F91D"},
	"Folded Hands":      {"U1F64F"},
	// hand-prop
	"Writing Hand": {"U270D"},
	"Nail Polish":  {"U1F485"},
	"Selfie":       {"U1F933"},
	// body-parts
	"Flexed Biceps":        {"U1F4AA"},
	"Mechanical Arm":       {"U1F9BE"},
	"Mechanical Leg":       {"U1F9BF"},
	"Leg":                  {"U1F9B5"},
	"Foot":                 {"U1F9B6"},
	"Ear":                  {"U1F442"},
	"Ear With Hearing Aid": {"U1F9BB"},
	"Nose":                 {"U1F443"},
	"Brain":                {"U1F9E0"},
	"Tooth":                {"U1F9B7"},
	"Bone":                 {"U1F9B4"},
	"Eyes":                 {"U1F440"},
	"Eye":                  {"U1F441"},
	"Tongue":               {"U1F445"},
	"Mouth":                {"U1F444"},
	// person
	"Baby":               {"U1F476"},
	"Child":              {"U1F9D2"},
	"Boy":                {"U1F466"},
	"Girl":               {"U1F467"},
	"Person":             {"U1F9D1"},
	"Person: Blond Hair": {"U1F471"},
	"Man":                {"U1F468"},
	"Man: Beard":         {"U1F9D4"},
	"Man: Blond Hair":    {"U1F471", "U200D", "U2642", "UFE0F"},
	"Man: Red Hair":      {"U1F468", "U200D", "U1F9B0"},
	"Man: Curly Hair":    {"U1F468", "U200D", "U1F9B1"},
	"Man: White Hair":    {"U1F468", "U200D", "U1F9B3"},
	"Man: Bald":          {"U1F468", "U200D", "U1F9B2"},
	"Woman":              {"U1F469"},
	"Woman: Blond Hair":  {"U1F471", "U200D", "U2640", "UFE0F"},
	"Woman: Red Hair":    {"U1F469", "U200D", "U1F9B0"},
	"Woman: Curly Hair":  {"U1F469", "U200D", "U1F9B1"},
	"Woman: White Hair":  {"U1F469", "U200D", "U1F9B3"},
	"Woman: Bald":        {"U1F469", "U200D", "U1F9B2"},
	"Older Person":       {"U1F9D3"},
	"Old Man":            {"U1F474"},
	"Old Woman":          {"U1F475"},
	// person-gesture
	"Person Frowning":     {"U1F64D"},
	"Man Frowning":        {"U1F64D", "U200D", "U2642", "UFE0F"},
	"Woman Frowning":      {"U1F64D", "U200D", "U2640", "UFE0F"},
	"Person Pouting":      {"U1F64E"},
	"Man Pouting":         {"U1F64E", "U200D", "U2642", "UFE0F"},
	"Woman Pouting":       {"U1F64E", "U200D", "U2640", "UFE0F"},
	"Person Gesturing NO": {"U1F645"},
	"Man Gesturing NO":    {"U1F645", "U200D", "U2642", "UFE0F"},
	"Woman Gesturing NO":  {"U1F645", "U200D", "U2640", "UFE0F"},
	"Person Gesturing OK": {"U1F646"},
	"Man Gesturing OK":    {"U1F646", "U200D", "U2642", "UFE0F"},
	"Woman Gesturing OK":  {"U1F646", "U200D", "U2640", "UFE0F"},
	"Person Tipping Hand": {"U1F481"},
	"Man Tipping Hand":    {"U1F481", "U200D", "U2642", "UFE0F"},
	"Woman Tipping Hand":  {"U1F481", "U200D", "U2640", "UFE0F"},
	"Person Raising Hand": {"U1F64B"},
	"Man Raising Hand":    {"U1F64B", "U200D", "U2642", "UFE0F"},
	"Woman Raising Hand":  {"U1F64B", "U200D", "U2640", "UFE0F"},
	"Deaf Person":         {"U1F9CF"},
	"Deaf Man":            {"U1F9CF", "U200D", "U2642", "UFE0F"},
	"Deaf Woman":          {"U1F9CF", "U200D", "U2640", "UFE0F"},
	"Person Bowing":       {"U1F647"},
	"Man Bowing":          {"U1F647", "U200D", "U2642", "UFE0F"},
	"Woman Bowing":        {"U1F647", "U200D", "U2640", "UFE0F"},
	"Person Facepalming":  {"U1F926"},
	"Man Facepalming":     {"U1F926", "U200D", "U2642", "UFE0F"},
	"Woman Facepalming":   {"U1F926", "U200D", "U2640", "UFE0F"},
	"Person Shrugging":    {"U1F937"},
	"Man Shrugging":       {"U1F937", "U200D", "U2642", "UFE0F"},
	"Woman Shrugging":     {"U1F937", "U200D", "U2640", "UFE0F"},
	// person-role
	"Man Health Worker":         {"U1F468", "U200D", "U2695", "UFE0F"},
	"Woman Health Worker":       {"U1F469", "U200D", "U2695", "UFE0F"},
	"Man Student":               {"U1F468", "U200D", "U1F393"},
	"Woman Student":             {"U1F469", "U200D", "U1F393"},
	"Man Teacher":               {"U1F468", "U200D", "U1F3EB"},
	"Woman Teacher":             {"U1F469", "U200D", "U1F3EB"},
	"Man Judge":                 {"U1F468", "U200D", "U2696", "UFE0F"},
	"Woman Judge":               {"U1F469", "U200D", "U2696", "UFE0F"},
	"Man Farmer":                {"U1F468", "U200D", "U1F33E"},
	"Woman Farmer":              {"U1F469", "U200D", "U1F33E"},
	"Man Cook":                  {"U1F468", "U200D", "U1F373"},
	"Woman Cook":                {"U1F469", "U200D", "U1F373"},
	"Man Mechanic":              {"U1F468", "U200D", "U1F527"},
	"Woman Mechanic":            {"U1F469", "U200D", "U1F527"},
	"Man Factory Worker":        {"U1F468", "U200D", "U1F3ED"},
	"Woman Factory Worker":      {"U1F469", "U200D", "U1F3ED"},
	"Man Office Worker":         {"U1F468", "U200D", "U1F4BC"},
	"Woman Office Worker":       {"U1F469", "U200D", "U1F4BC"},
	"Man Scientist":             {"U1F468", "U200D", "U1F52C"},
	"Woman Scientist":           {"U1F469", "U200D", "U1F52C"},
	"Man Technologist":          {"U1F468", "U200D", "U1F4BB"},
	"Woman Technologist":        {"U1F469", "U200D", "U1F4BB"},
	"Man Singer":                {"U1F468", "U200D", "U1F3A4"},
	"Woman Singer":              {"U1F469", "U200D", "U1F3A4"},
	"Man Artist":                {"U1F468", "U200D", "U1F3A8"},
	"Woman Artist":              {"U1F469", "U200D", "U1F3A8"},
	"Man Pilot":                 {"U1F468", "U200D", "U2708", "UFE0F"},
	"Woman Pilot":               {"U1F469", "U200D", "U2708", "UFE0F"},
	"Man Astronaut":             {"U1F468", "U200D", "U1F680"},
	"Woman Astronaut":           {"U1F469", "U200D", "U1F680"},
	"Man Firefighter":           {"U1F468", "U200D", "U1F692"},
	"Woman Firefighter":         {"U1F469", "U200D", "U1F692"},
	"Police Officer":            {"U1F46E"},
	"Man Police Officer":        {"U1F46E", "U200D", "U2642", "UFE0F"},
	"Woman Police Officer":      {"U1F46E", "U200D", "U2640", "UFE0F"},
	"Detective":                 {"U1F575"},
	"Man Detective":             {"U1F575", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Detective":           {"U1F575", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Guard":                     {"U1F482"},
	"Man Guard":                 {"U1F482", "U200D", "U2642", "UFE0F"},
	"Woman Guard":               {"U1F482", "U200D", "U2640", "UFE0F"},
	"Construction Worker":       {"U1F477"},
	"Man Construction Worker":   {"U1F477", "U200D", "U2642", "UFE0F"},
	"Woman Construction Worker": {"U1F477", "U200D", "U2640", "UFE0F"},
	"Prince":                    {"U1F934"},
	"Princess":                  {"U1F478"},
	"Person Wearing Turban":     {"U1F473"},
	"Man Wearing Turban":        {"U1F473", "U200D", "U2642", "UFE0F"},
	"Woman Wearing Turban":      {"U1F473", "U200D", "U2640", "UFE0F"},
	"Man With Chinese Cap":      {"U1F472"},
	"Woman With Headscarf":      {"U1F9D5"},
	"Man In Tuxedo":             {"U1F935"},
	"Bride With Veil":           {"U1F470"},
	"Pregnant Woman":            {"U1F930"},
	"Breast-Feeding":            {"U1F931"},
	// person-fantasy
	"Baby Angel":         {"U1F47C"},
	"Santa Claus":        {"U1F385"},
	"Mrs. Claus":         {"U1F936"},
	"Superhero":          {"U1F9B8"},
	"Man Superhero":      {"U1F9B8", "U200D", "U2642", "UFE0F"},
	"Woman Superhero":    {"U1F9B8", "U200D", "U2640", "UFE0F"},
	"Supervillain":       {"U1F9B9"},
	"Man Supervillain":   {"U1F9B9", "U200D", "U2642", "UFE0F"},
	"Woman Supervillain": {"U1F9B9", "U200D", "U2640", "UFE0F"},
	"Mage":               {"U1F9D9"},
	"Man Mage":           {"U1F9D9", "U200D", "U2642", "UFE0F"},
	"Woman Mage":         {"U1F9D9", "U200D", "U2640", "UFE0F"},
	"Fairy":              {"U1F9DA"},
	"Man Fairy":          {"U1F9DA", "U200D", "U2642", "UFE0F"},
	"Woman Fairy":        {"U1F9DA", "U200D", "U2640", "UFE0F"},
	"Vampire":            {"U1F9DB"},
	"Man Vampire":        {"U1F9DB", "U200D", "U2642", "UFE0F"},
	"Woman Vampire":      {"U1F9DB", "U200D", "U2640", "UFE0F"},
	"Merperson":          {"U1F9DC"},
	"Merman":             {"U1F9DC", "U200D", "U2642", "UFE0F"},
	"Mermaid":            {"U1F9DC", "U200D", "U2640", "UFE0F"},
	"Elf":                {"U1F9DD"},
	"Man Elf":            {"U1F9DD", "U200D", "U2642", "UFE0F"},
	"Woman Elf":          {"U1F9DD", "U200D", "U2640", "UFE0F"},
	"Genie":              {"U1F9DE"},
	"Man Genie":          {"U1F9DE", "U200D", "U2642", "UFE0F"},
	"Woman Genie":        {"U1F9DE", "U200D", "U2640", "UFE0F"},
	"Zombie":             {"U1F9DF"},
	"Man Zombie":         {"U1F9DF", "U200D", "U2642", "UFE0F"},
	"Woman Zombie":       {"U1F9DF", "U200D", "U2640", "UFE0F"},
	// person-activity
	"Person Getting Massage":        {"U1F486"},
	"Man Getting Massage":           {"U1F486", "U200D", "U2642", "UFE0F"},
	"Woman Getting Massage":         {"U1F486", "U200D", "U2640", "UFE0F"},
	"Person Getting Haircut":        {"U1F487"},
	"Man Getting Haircut":           {"U1F487", "U200D", "U2642", "UFE0F"},
	"Woman Getting Haircut":         {"U1F487", "U200D", "U2640", "UFE0F"},
	"Person Walking":                {"U1F6B6"},
	"Man Walking":                   {"U1F6B6", "U200D", "U2642", "UFE0F"},
	"Woman Walking":                 {"U1F6B6", "U200D", "U2640", "UFE0F"},
	"Person Standing":               {"U1F9CD"},
	"Man Standing":                  {"U1F9CD", "U200D", "U2642", "UFE0F"},
	"Woman Standing":                {"U1F9CD", "U200D", "U2640", "UFE0F"},
	"Person Kneeling":               {"U1F9CE"},
	"Man Kneeling":                  {"U1F9CE", "U200D", "U2642", "UFE0F"},
	"Woman Kneeling":                {"U1F9CE", "U200D", "U2640", "UFE0F"},
	"Man With Probing Cane":         {"U1F468", "U200D", "U1F9AF"},
	"Woman With Probing Cane":       {"U1F469", "U200D", "U1F9AF"},
	"Man In Motorized Wheelchair":   {"U1F468", "U200D", "U1F9BC"},
	"Woman In Motorized Wheelchair": {"U1F469", "U200D", "U1F9BC"},
	"Man In Manual Wheelchair":      {"U1F468", "U200D", "U1F9BD"},
	"Woman In Manual Wheelchair":    {"U1F469", "U200D", "U1F9BD"},
	"Person Running":                {"U1F3C3"},
	"Man Running":                   {"U1F3C3", "U200D", "U2642", "UFE0F"},
	"Woman Running":                 {"U1F3C3", "U200D", "U2640", "UFE0F"},
	"Woman Dancing":                 {"U1F483"},
	"Man Dancing":                   {"U1F57A"},
	"Man In Suit Levitating":        {"U1F574"},
	"People With Bunny Ears":        {"U1F46F"},
	"Men With Bunny Ears":           {"U1F46F", "U200D", "U2642", "UFE0F"},
	"Women With Bunny Ears":         {"U1F46F", "U200D", "U2640", "UFE0F"},
	"Person In Steamy Room":         {"U1F9D6"},
	"Man In Steamy Room":            {"U1F9D6", "U200D", "U2642", "UFE0F"},
	"Woman In Steamy Room":          {"U1F9D6", "U200D", "U2640", "UFE0F"},
	"Person Climbing":               {"U1F9D7"},
	"Man Climbing":                  {"U1F9D7", "U200D", "U2642", "UFE0F"},
	"Woman Climbing":                {"U1F9D7", "U200D", "U2640", "UFE0F"},
	// person-sport
	"Person Fencing":            {"U1F93A"},
	"Horse Racing":              {"U1F3C7"},
	"Skier":                     {"U26F7"},
	"Snowboarder":               {"U1F3C2"},
	"Person Golfing":            {"U1F3CC"},
	"Man Golfing":               {"U1F3CC", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Golfing":             {"U1F3CC", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Person Surfing":            {"U1F3C4"},
	"Man Surfing":               {"U1F3C4", "U200D", "U2642", "UFE0F"},
	"Woman Surfing":             {"U1F3C4", "U200D", "U2640", "UFE0F"},
	"Person Rowing Boat":        {"U1F6A3"},
	"Man Rowing Boat":           {"U1F6A3", "U200D", "U2642", "UFE0F"},
	"Woman Rowing Boat":         {"U1F6A3", "U200D", "U2640", "UFE0F"},
	"Person Swimming":           {"U1F3CA"},
	"Man Swimming":              {"U1F3CA", "U200D", "U2642", "UFE0F"},
	"Woman Swimming":            {"U1F3CA", "U200D", "U2640", "UFE0F"},
	"Person Bouncing Ball":      {"U26F9"},
	"Man Bouncing Ball":         {"U26F9", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Bouncing Ball":       {"U26F9", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Person Lifting Weights":    {"U1F3CB"},
	"Man Lifting Weights":       {"U1F3CB", "UFE0F", "U200D", "U2642", "UFE0F"},
	"Woman Lifting Weights":     {"U1F3CB", "UFE0F", "U200D", "U2640", "UFE0F"},
	"Person Biking":             {"U1F6B4"},
	"Man Biking":                {"U1F6B4", "U200D", "U2642", "UFE0F"},
	"Woman Biking":              {"U1F6B4", "U200D", "U2640", "UFE0F"},
	"Person Mountain Biking":    {"U1F6B5"},
	"Man Mountain Biking":       {"U1F6B5", "U200D", "U2642", "UFE0F"},
	"Woman Mountain Biking":     {"U1F6B5", "U200D", "U2640", "UFE0F"},
	"Person Cartwheeling":       {"U1F938"},
	"Man Cartwheeling":          {"U1F938", "U200D", "U2642", "UFE0F"},
	"Woman Cartwheeling":        {"U1F938", "U200D", "U2640", "UFE0F"},
	"People Wrestling":          {"U1F93C"},
	"Men Wrestling":             {"U1F93C", "U200D", "U2642", "UFE0F"},
	"Women Wrestling":           {"U1F93C", "U200D", "U2640", "UFE0F"},
	"Person Playing Water Polo": {"U1F93D"},
	"Man Playing Water Polo":    {"U1F93D", "U200D", "U2642", "UFE0F"},
	"Woman Playing Water Polo":  {"U1F93D", "U200D", "U2640", "UFE0F"},
	"Person Playing Handball":   {"U1F93E"},
	"Man Playing Handball":      {"U1F93E", "U200D", "U2642", "UFE0F"},
	"Woman Playing Handball":    {"U1F93E", "U200D", "U2640", "UFE0F"},
	"Person Juggling":           {"U1F939"},
	"Man Juggling":              {"U1F939", "U200D", "U2642", "UFE0F"},
	"Woman Juggling":            {"U1F939", "U200D", "U2640", "UFE0F"},
	// person-resting
	"Person In Lotus Position": {"U1F9D8"},
	"Man In Lotus Position":    {"U1F9D8", "U200D", "U2642", "UFE0F"},
	"Woman In Lotus Position":  {"U1F9D8", "U200D", "U2640", "UFE0F"},
	"Person Taking Bath":       {"U1F6C0"},
	"Person In Bed":            {"U1F6CC"},
	// family
	"People Holding Hands":             {"U1F9D1", "U200D", "U1F91D", "U200D", "U1F9D1"},
	"Women Holding Hands":              {"U1F46D"},
	"Woman And Man Holding Hands":      {"U1F46B"},
	"Men Holding Hands":                {"U1F46C"},
	"Kiss":                             {"U1F48F"},
	"Kiss: Woman, Man":                 {"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F48B", "U200D", "U1F468"},
	"Kiss: Man, Man":                   {"U1F468", "U200D", "U2764", "UFE0F", "U200D", "U1F48B", "U200D", "U1F468"},
	"Kiss: Woman, Woman":               {"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F48B", "U200D", "U1F469"},
	"Couple With Heart":                {"U1F491"},
	"Couple With Heart: Woman, Man":    {"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F468"},
	"Couple With Heart: Man, Man":      {"U1F468", "U200D", "U2764", "UFE0F", "U200D", "U1F468"},
	"Couple With Heart: Woman, Woman":  {"U1F469", "U200D", "U2764", "UFE0F", "U200D", "U1F469"},
	"Family":                           {"U1F46A"},
	"Family: Man, Woman, Boy":          {"U1F468", "U200D", "U1F469", "U200D", "U1F466"},
	"Family: Man, Woman, Girl":         {"U1F468", "U200D", "U1F469", "U200D", "U1F467"},
	"Family: Man, Woman, Girl, Boy":    {"U1F468", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Man, Woman, Boy, Boy":     {"U1F468", "U200D", "U1F469", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Man, Woman, Girl, Girl":   {"U1F468", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Man, Man, Boy":            {"U1F468", "U200D", "U1F468", "U200D", "U1F466"},
	"Family: Man, Man, Girl":           {"U1F468", "U200D", "U1F468", "U200D", "U1F467"},
	"Family: Man, Man, Girl, Boy":      {"U1F468", "U200D", "U1F468", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Man, Man, Boy, Boy":       {"U1F468", "U200D", "U1F468", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Man, Man, Girl, Girl":     {"U1F468", "U200D", "U1F468", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Woman, Woman, Boy":        {"U1F469", "U200D", "U1F469", "U200D", "U1F466"},
	"Family: Woman, Woman, Girl":       {"U1F469", "U200D", "U1F469", "U200D", "U1F467"},
	"Family: Woman, Woman, Girl, Boy":  {"U1F469", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Woman, Woman, Boy, Boy":   {"U1F469", "U200D", "U1F469", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Woman, Woman, Girl, Girl": {"U1F469", "U200D", "U1F469", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Man, Boy":                 {"U1F468", "U200D", "U1F466"},
	"Family: Man, Boy, Boy":            {"U1F468", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Man, Girl":                {"U1F468", "U200D", "U1F467"},
	"Family: Man, Girl, Boy":           {"U1F468", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Man, Girl, Girl":          {"U1F468", "U200D", "U1F467", "U200D", "U1F467"},
	"Family: Woman, Boy":               {"U1F469", "U200D", "U1F466"},
	"Family: Woman, Boy, Boy":          {"U1F469", "U200D", "U1F466", "U200D", "U1F466"},
	"Family: Woman, Girl":              {"U1F469", "U200D", "U1F467"},
	"Family: Woman, Girl, Boy":         {"U1F469", "U200D", "U1F467", "U200D", "U1F466"},
	"Family: Woman, Girl, Girl":        {"U1F469", "U200D", "U1F467", "U200D", "U1F467"},
	// person-symbol
	"Speaking Head":       {"U1F5E3"},
	"Bust In Silhouette":  {"U1F464"},
	"Busts In Silhouette": {"U1F465"},
	"Footprints":          {"U1F463"},

	// COMPONENT
	// hair-style
	"Red Hair":   {"U1F9B0"},
	"Curly Hair": {"U1F9B1"},
	"White Hair": {"U1F9B3"},
	"Bald":       {"U1F9B2"},

	// ANIMALS & NATURE
	// animal-mammal
	"Monkey Face":    {"U1F435"},
	"Monkey":         {"U1F412"},
	"Gorilla":        {"U1F98D"},
	"Orangutan":      {"U1F9A7"},
	"Dog Face":       {"U1F436"},
	"Dog":            {"U1F415"},
	"Guide Dog":      {"U1F9AE"},
	"Service Dog":    {"U1F415", "U200D", "U1F9BA"},
	"Poodle":         {"U1F429"},
	"Wolf":           {"U1F43A"},
	"Fox":            {"U1F98A"},
	"Raccoon":        {"U1F99D"},
	"Cat Face":       {"U1F431"},
	"Cat":            {"U1F408"},
	"Lion":           {"U1F981"},
	"Tiger Face":     {"U1F42F"},
	"Tiger":          {"U1F405"},
	"Leopard":        {"U1F406"},
	"Horse Face":     {"U1F434"},
	"Horse":          {"U1F40E"},
	"Unicorn":        {"U1F984"},
	"Zebra":          {"U1F993"},
	"Deer":           {"U1F98C"},
	"Cow Face":       {"U1F42E"},
	"Ox":             {"U1F402"},
	"Water Buffalo":  {"U1F403"},
	"Cow":            {"U1F404"},
	"Pig Face":       {"U1F437"},
	"Pig":            {"U1F416"},
	"Boar":           {"U1F417"},
	"Pig Nose":       {"U1F43D"},
	"Ram":            {"U1F40F"},
	"Ewe":            {"U1F411"},
	"Goat":           {"U1F410"},
	"Camel":          {"U1F42A"},
	"Two-Hump Camel": {"U1F42B"},
	"Llama":          {"U1F999"},
	"Giraffe":        {"U1F992"},
	"Elephant":       {"U1F418"},
	"Rhinoceros":     {"U1F98F"},
	"Hippopotamus":   {"U1F99B"},
	"Mouse Face":     {"U1F42D"},
	"Mouse":          {"U1F401"},
	"Rat":            {"U1F400"},
	"Hamster":        {"U1F439"},
	"Rabbit Face":    {"U1F430"},
	"Rabbit":         {"U1F407"},
	"Chipmunk":       {"U1F43F"},
	"Hedgehog":       {"U1F994"},
	"Bat":            {"U1F987"},
	"Bear":           {"U1F43B"},
	"Koala":          {"U1F428"},
	"Panda":          {"U1F43C"},
	"Sloth":          {"U1F9A5"},
	"Otter":          {"U1F9A6"},
	"Skunk":          {"U1F9A8"},
	"Kangaroo":       {"U1F998"},
	"Badger":         {"U1F9A1"},
	"Paw Prints":     {"U1F43E"},
	// animal-bird
	"Turkey [Animal/Food]":    {"U1F983"},
	"Chicken":                 {"U1F414"},
	"Rooster":                 {"U1F413"},
	"Hatching Chick":          {"U1F423"},
	"Baby Chick":              {"U1F424"},
	"Front-Facing Baby Chick": {"U1F425"},
	"Bird":                    {"U1F426"},
	"Penguin":                 {"U1F427"},
	"Dove":                    {"U1F54A"},
	"Eagle":                   {"U1F985"},
	"Duck":                    {"U1F986"},
	"Swan":                    {"U1F9A2"},
	"Owl":                     {"U1F989"},
	"Flamingo":                {"U1F9A9"},
	"Peacock":                 {"U1F99A"},
	"Parrot":                  {"U1F99C"},
	// animal-amphibian
	"Frog": {"U1F438"},
	// animal-reptile
	"Crocodile":   {"U1F40A"},
	"Turtle":      {"U1F422"},
	"Lizard":      {"U1F98E"},
	"Snake":       {"U1F40D"},
	"Dragon Face": {"U1F432"},
	"Dragon":      {"U1F409"},
	"Sauropod":    {"U1F995"},
	"T-Rex":       {"U1F996"},
	// animal-marine
	"Spouting Whale": {"U1F433"},
	"Whale":          {"U1F40B"},
	"Dolphin":        {"U1F42C"},
	"Fish":           {"U1F41F"},
	"Tropical Fish":  {"U1F420"},
	"Blowfish":       {"U1F421"},
	"Shark":          {"U1F988"},
	"Octopus":        {"U1F419"},
	"Spiral Shell":   {"U1F41A"},
	// animal-bug
	"Snail":       {"U1F40C"},
	"Butterfly":   {"U1F98B"},
	"Bug":         {"U1F41B"},
	"Ant":         {"U1F41C"},
	"Honeybee":    {"U1F41D"},
	"Lady Beetle": {"U1F41E"},
	"Cricket":     {"U1F997"},
	"Spider":      {"U1F577"},
	"Spider Web":  {"U1F578"},
	"Scorpion":    {"U1F982"},
	"Mosquito":    {"U1F99F"},
	"Microbe":     {"U1F9A0"},
	// plant-flower
	"Bouquet":        {"U1F490"},
	"Cherry Blossom": {"U1F338"},
	"White Flower":   {"U1F4AE"},
	"Rosette":        {"U1F3F5"},
	"Rose":           {"U1F339"},
	"Wilted Flower":  {"U1F940"},
	"Hibiscus":       {"U1F33A"},
	"Sunflower":      {"U1F33B"},
	"Blossom":        {"U1F33C"},
	"Tulip":          {"U1F337"},
	// plant-other
	"Seedling":                {"U1F331"},
	"Evergreen Tree":          {"U1F332"},
	"Deciduous Tree":          {"U1F333"},
	"Palm Tree":               {"U1F334"},
	"Cactus":                  {"U1F335"},
	"Sheaf Of Rice":           {"U1F33E"},
	"Herb":                    {"U1F33F"},
	"Shamrock":                {"U2618"},
	"Four Leaf Clover":        {"U1F340"},
	"Maple Leaf":              {"U1F341"},
	"Fallen Leaf":             {"U1F342"},
	"Leaf Fluttering In Wind": {"U1F343"},

	// FOOD & DRINK
	// food-fruit
	"Grapes":      {"U1F347"},
	"Melon":       {"U1F348"},
	"Watermelon":  {"U1F349"},
	"Tangerine":   {"U1F34A"},
	"Lemon":       {"U1F34B"},
	"Banana":      {"U1F34C"},
	"Pineapple":   {"U1F34D"},
	"Mango":       {"U1F96D"},
	"Red Apple":   {"U1F34E"},
	"Green Apple": {"U1F34F"},
	"Pear":        {"U1F350"},
	"Peach":       {"U1F351"},
	"Cherries":    {"U1F352"},
	"Strawberry":  {"U1F353"},
	"Kiwi Fruit":  {"U1F95D"},
	"Tomato":      {"U1F345"},
	"Coconut":     {"U1F965"},
	// food-vegetable
	"Avocado":     {"U1F951"},
	"Eggplant":    {"U1F346"},
	"Potato":      {"U1F954"},
	"Carrot":      {"U1F955"},
	"Ear Of Corn": {"U1F33D"},
	"Hot Pepper":  {"U1F336"},
	"Cucumber":    {"U1F952"},
	"Leafy Green": {"U1F96C"},
	"Broccoli":    {"U1F966"},
	"Garlic":      {"U1F9C4"},
	"Onion":       {"U1F9C5"},
	"Mushroom":    {"U1F344"},
	"Peanuts":     {"U1F95C"},
	"Chestnut":    {"U1F330"},
	// food-prepared
	"Bread":               {"U1F35E"},
	"Croissant":           {"U1F950"},
	"Baguette Bread":      {"U1F956"},
	"Pretzel":             {"U1F968"},
	"Bagel":               {"U1F96F"},
	"Pancakes":            {"U1F95E"},
	"Waffle":              {"U1F9C7"},
	"Cheese Wedge":        {"U1F9C0"},
	"Meat On Bone":        {"U1F356"},
	"Poultry Leg":         {"U1F357"},
	"Cut Of Meat":         {"U1F969"},
	"Bacon":               {"U1F953"},
	"Hamburger":           {"U1F354"},
	"French Fries":        {"U1F35F"},
	"Pizza":               {"U1F355"},
	"Hot Dog":             {"U1F32D"},
	"Sandwich":            {"U1F96A"},
	"Taco":                {"U1F32E"},
	"Burrito":             {"U1F32F"},
	"Stuffed Flatbread":   {"U1F959"},
	"Falafel":             {"U1F9C6"},
	"Egg":                 {"U1F95A"},
	"Cooking":             {"U1F373"},
	"Shallow Pan Of Food": {"U1F958"},
	"Pot Of Food":         {"U1F372"},
	"Bowl With Spoon":     {"U1F963"},
	"Green Salad":         {"U1F957"},
	"Popcorn":             {"U1F37F"},
	"Butter":              {"U1F9C8"},
	"Salt":                {"U1F9C2"},
	"Canned Food":         {"U1F96B"},
	// food-asian
	"Bento Box":            {"U1F371"},
	"Rice Cracker":         {"U1F358"},
	"Rice Ball":            {"U1F359"},
	"Cooked Rice":          {"U1F35A"},
	"Curry Rice":           {"U1F35B"},
	"Steaming Bowl":        {"U1F35C"},
	"Spaghetti":            {"U1F35D"},
	"Roasted Sweet Potato": {"U1F360"},
	"Oden":                 {"U1F362"},
	"Sushi":                {"U1F363"},
	"Fried Shrimp":         {"U1F364"},
	"Fish Cake With Swirl": {"U1F365"},
	"Moon Cake":            {"U1F96E"},
	"Dango":                {"U1F361"},
	"Dumpling":             {"U1F95F"},
	"Fortune Cookie":       {"U1F960"},
	"Takeout Box":          {"U1F961"},
	// food-marine
	"Crab":    {"U1F980"},
	"Lobster": {"U1F99E"},
	"Shrimp":  {"U1F990"},
	"Squid":   {"U1F991"},
	"Oyster":  {"U1F9AA"},
	// food-sweet
	"Soft Ice Cream": {"U1F366"},
	"Shaved Ice":     {"U1F367"},
	"Ice Cream":      {"U1F368"},
	"Doughnut":       {"U1F369"},
	"Cookie":         {"U1F36A"},
	"Birthday Cake":  {"U1F382"},
	"Shortcake":      {"U1F370"},
	"Cupcake":        {"U1F9C1"},
	"Pie":            {"U1F967"},
	"Chocolate Bar":  {"U1F36B"},
	"Candy":          {"U1F36C"},
	"Lollipop":       {"U1F36D"},
	"Custard":        {"U1F36E"},
	"Honey Pot":      {"U1F36F"},
	// drink
	"Baby Bottle":              {"U1F37C"},
	"Glass Of Milk":            {"U1F95B"},
	"Hot Beverage":             {"U2615"},
	"Teacup Without Handle":    {"U1F375"},
	"Sake":                     {"U1F376"},
	"Bottle With Popping Cork": {"U1F37E"},
	"Wine Glass":               {"U1F377"},
	"Cocktail Glass":           {"U1F378"},
	"Tropical Drink":           {"U1F379"},
	"Beer Mug":                 {"U1F37A"},
	"Clinking Beer Mugs":       {"U1F37B"},
	"Clinking Glasses":         {"U1F942"},
	"Tumbler Glass":            {"U1F943"},
	"Cup With Straw":           {"U1F964"},
	"Beverage Box":             {"U1F9C3"},
	"Mate":                     {"U1F9C9"},
	"Ice":                      {"U1F9CA"},
	// dishware
	"Chopsticks":                {"U1F962"},
	"Fork And Knife With Plate": {"U1F37D"},
	"Fork And Knife":            {"U1F374"},
	"Spoon":                     {"U1F944"},
	"Kitchen Knife":             {"U1F52A"},
	"Amphora":                   {"U1F3FA"},

	// TRAVEL & PLACES
	// place-map
	"Globe Showing Europe-Africa":  {"U1F30D"},
	"Globe Showing Americas":       {"U1F30E"},
	"Globe Showing Asia-Australia": {"U1F30F"},
	"Globe With Meridians":         {"U1F310"},
	"World Map":                    {"U1F5FA"},
	"Map Of Japan":                 {"U1F5FE"},
	"Compass":                      {"U1F9ED"},
	// place-geographic
	"Snow-Capped Mountain": {"U1F3D4"},
	"Mountain":             {"U26F0"},
	"Volcano":              {"U1F30B"},
	"Mount Fuji":           {"U1F5FB"},
	"Camping":              {"U1F3D5"},
	"Beach With Umbrella":  {"U1F3D6"},
	"Desert":               {"U1F3DC"},
	"Desert Island":        {"U1F3DD"},
	"National Park":        {"U1F3DE"},
	// place-building
	"Stadium":               {"U1F3DF"},
	"Classical Building":    {"U1F3DB"},
	"Building Construction": {"U1F3D7"},
	"Brick":                 {"U1F9F1"},
	"Houses":                {"U1F3D8"},
	"Derelict House":        {"U1F3DA"},
	"House":                 {"U1F3E0"},
	"House With Garden":     {"U1F3E1"},
	"Office Building":       {"U1F3E2"},
	"Japanese Post Office":  {"U1F3E3"},
	"Post Office":           {"U1F3E4"},
	"Hospital":              {"U1F3E5"},
	"Bank":                  {"U1F3E6"},
	"Hotel":                 {"U1F3E8"},
	"Love Hotel":            {"U1F3E9"},
	"Convenience Store":     {"U1F3EA"},
	"School":                {"U1F3EB"},
	"Department Store":      {"U1F3EC"},
	"Factory":               {"U1F3ED"},
	"Japanese Castle":       {"U1F3EF"},
	"Castle":                {"U1F3F0"},
	"Wedding":               {"U1F492"},
	"Tokyo Tower":           {"U1F5FC"},
	"Statue Of Liberty":     {"U1F5FD"},
	// place-religious
	"Church":        {"U26EA"},
	"Mosque":        {"U1F54C"},
	"Hindu Temple":  {"U1F6D5"},
	"Synagogue":     {"U1F54D"},
	"Shinto Shrine": {"U26E9"},
	"Kaaba":         {"U1F54B"},
	// place-other
	"Fountain":               {"U26F2"},
	"Tent":                   {"U26FA"},
	"Foggy":                  {"U1F301"},
	"Night With Stars":       {"U1F303"},
	"Cityscape":              {"U1F3D9"},
	"Sunrise Over Mountains": {"U1F304"},
	"Sunrise":                {"U1F305"},
	"Cityscape At Dusk":      {"U1F306"},
	"Sunset":                 {"U1F307"},
	"Bridge At Night":        {"U1F309"},
	"Hot Springs":            {"U2668"},
	"Carousel Horse":         {"U1F3A0"},
	"Ferris Wheel":           {"U1F3A1"},
	"Roller Coaster":         {"U1F3A2"},
	"Barber Pole":            {"U1F488"},
	"Circus Tent":            {"U1F3AA"},
	// transport-ground
	"Locomotive":               {"U1F682"},
	"Railway Car":              {"U1F683"},
	"High-Speed Train":         {"U1F684"},
	"Bullet Train":             {"U1F685"},
	"Train":                    {"U1F686"},
	"Metro":                    {"U1F687"},
	"Light Rail":               {"U1F688"},
	"Station":                  {"U1F689"},
	"Tram":                     {"U1F68A"},
	"Monorail":                 {"U1F69D"},
	"Mountain Railway":         {"U1F69E"},
	"Tram Car":                 {"U1F68B"},
	"Bus":                      {"U1F68C"},
	"Oncoming Bus":             {"U1F68D"},
	"Trolleybus":               {"U1F68E"},
	"Minibus":                  {"U1F690"},
	"Ambulance":                {"U1F691"},
	"Fire Engine":              {"U1F692"},
	"Police Car":               {"U1F693"},
	"Oncoming Police Car":      {"U1F694"},
	"Taxi":                     {"U1F695"},
	"Oncoming Taxi":            {"U1F696"},
	"Automobile":               {"U1F697"},
	"Oncoming Automobile":      {"U1F698"},
	"Sport Utility Vehicle":    {"U1F699"},
	"Delivery Truck":           {"U1F69A"},
	"Articulated Lorry":        {"U1F69B"},
	"Tractor":                  {"U1F69C"},
	"Racing Car":               {"U1F3CE"},
	"Motorcycle":               {"U1F3CD"},
	"Motor Scooter":            {"U1F6F5"},
	"Manual Wheelchair":        {"U1F9BD"},
	"Motorized Wheelchair":     {"U1F9BC"},
	"Auto Rickshaw":            {"U1F6FA"},
	"Bicycle":                  {"U1F6B2"},
	"Kick Scooter":             {"U1F6F4"},
	"Skateboard":               {"U1F6F9"},
	"Bus Stop":                 {"U1F68F"},
	"Motorway":                 {"U1F6E3"},
	"Railway Track":            {"U1F6E4"},
	"Oil Drum":                 {"U1F6E2"},
	"Fuel Pump":                {"U26FD"},
	"Police Car Light":         {"U1F6A8"},
	"Horizontal Traffic Light": {"U1F6A5"},
	"Vertical Traffic Light":   {"U1F6A6"},
	"Stop Sign":                {"U1F6D1"},
	"Construction":             {"U1F6A7"},
	// transport-water
	"Anchor":         {"U2693"},
	"Sailboat":       {"U26F5"},
	"Canoe":          {"U1F6F6"},
	"Speedboat":      {"U1F6A4"},
	"Passenger Ship": {"U1F6F3"},
	"Ferry":          {"U26F4"},
	"Motor Boat":     {"U1F6E5"},
	"Ship":           {"U1F6A2"},
	// transport-air
	"Airplane":           {"U2708"},
	"Small Airplane":     {"U1F6E9"},
	"Airplane Departure": {"U1F6EB"},
	"Airplane Arrival":   {"U1F6EC"},
	"Parachute":          {"U1FA82"},
	"Seat":               {"U1F4BA"},
	"Helicopter":         {"U1F681"},
	"Suspension Railway": {"U1F69F"},
	"Mountain Cableway":  {"U1F6A0"},
	"Aerial Tramway":     {"U1F6A1"},
	"Satellite":          {"U1F6F0"},
	"Rocket":             {"U1F680"},
	"Flying Saucer":      {"U1F6F8"},
	// hotel
	"Bellhop Bell": {"U1F6CE"},
	"Luggage":      {"U1F9F3"},
	// time
	"Hourglass Done":     {"U231B"},
	"Hourglass Not Done": {"U23F3"},
	"Watch":              {"U231A"},
	"Alarm Clock":        {"U23F0"},
	"Stopwatch":          {"U23F1"},
	"Timer Clock":        {"U23F2"},
	"Mantelpiece Clock":  {"U1F570"},
	"Twelve O’Clock":     {"U1F55B"},
	"Twelve-Thirty":      {"U1F567"},
	"One O’Clock":        {"U1F550"},
	"One-Thirty":         {"U1F55C"},
	"Two O’Clock":        {"U1F551"},
	"Two-Thirty":         {"U1F55D"},
	"Three O’Clock":      {"U1F552"},
	"Three-Thirty":       {"U1F55E"},
	"Four O’Clock":       {"U1F553"},
	"Four-Thirty":        {"U1F55F"},
	"Five O’Clock":       {"U1F554"},
	"Five-Thirty":        {"U1F560"},
	"Six O’Clock":        {"U1F555"},
	"Six-Thirty":         {"U1F561"},
	"Seven O’Clock":      {"U1F556"},
	"Seven-Thirty":       {"U1F562"},
	"Eight O’Clock":      {"U1F557"},
	"Eight-Thirty":       {"U1F563"},
	"Nine O’Clock":       {"U1F558"},
	"Nine-Thirty":        {"U1F564"},
	"Ten O’Clock":        {"U1F559"},
	"Ten-Thirty":         {"U1F565"},
	"Eleven O’Clock":     {"U1F55A"},
	"Eleven-Thirty":      {"U1F566"},
	// sky-and-weather
	"New Moon":                      {"U1F311"},
	"Waxing Crescent Moon":          {"U1F312"},
	"First Quarter Moon":            {"U1F313"},
	"Waxing Gibbous Moon":           {"U1F314"},
	"Full Moon":                     {"U1F315"},
	"Waning Gibbous Moon":           {"U1F316"},
	"Last Quarter Moon":             {"U1F317"},
	"Waning Crescent Moon":          {"U1F318"},
	"Crescent Moon":                 {"U1F319"},
	"New Moon Face":                 {"U1F31A"},
	"First Quarter Moon Face":       {"U1F31B"},
	"Last Quarter Moon Face":        {"U1F31C"},
	"Thermometer":                   {"U1F321"},
	"Sun":                           {"U2600"},
	"Full Moon Face":                {"U1F31D"},
	"Sun With Face":                 {"U1F31E"},
	"Ringed Planet":                 {"U1FA90"},
	"Star":                          {"U2B50"},
	"Glowing Star":                  {"U1F31F"},
	"Shooting Star":                 {"U1F320"},
	"Milky Way":                     {"U1F30C"},
	"Cloud":                         {"U2601"},
	"Sun Behind Cloud":              {"U26C5"},
	"Cloud With Lightning And Rain": {"U26C8"},
	"Sun Behind Small Cloud":        {"U1F324"},
	"Sun Behind Large Cloud":        {"U1F325"},
	"Sun Behind Rain Cloud":         {"U1F326"},
	"Cloud With Rain":               {"U1F327"},
	"Cloud With Snow":               {"U1F328"},
	"Cloud With Lightning":          {"U1F329"},
	"Tornado":                       {"U1F32A"},
	"Fog":                           {"U1F32B"},
	"Wind Face":                     {"U1F32C"},
	"Cyclone":                       {"U1F300"},
	"Rainbow":                       {"U1F308"},
	"Closed Umbrella":               {"U1F302"},
	"Umbrella":                      {"U2602"},
	"Umbrella With Rain Drops":      {"U2614"},
	"Umbrella On Ground":            {"U26F1"},
	"High Voltage":                  {"U26A1"},
	"Snowflake":                     {"U2744"},
	"Snowman":                       {"U2603"},
	"Snowman Without Snow":          {"U26C4"},
	"Comet":                         {"U2604"},
	"Fire":                          {"U1F525"},
	"Droplet":                       {"U1F4A7"},
	"Water Wave":                    {"U1F30A"},

	// Activities
	// event
	"Jack-O-Lantern":        {"U1F383"},
	"Christmas Tree":        {"U1F384"},
	"Fireworks":             {"U1F386"},
	"Sparkler":              {"U1F387"},
	"Firecracker":           {"U1F9E8"},
	"Sparkles":              {"U2728"},
	"Balloon":               {"U1F388"},
	"Party Popper":          {"U1F389"},
	"Confetti Ball":         {"U1F38A"},
	"Tanabata Tree":         {"U1F38B"},
	"Pine Decoration":       {"U1F38D"},
	"Japanese Dolls":        {"U1F38E"},
	"Carp Streamer":         {"U1F38F"},
	"Wind Chime":            {"U1F390"},
	"Moon Viewing Ceremony": {"U1F391"},
	"Red Envelope":          {"U1F9E7"},
	"Ribbon":                {"U1F380"},
	"Wrapped Gift":          {"U1F381"},
	"Reminder Ribbon":       {"U1F397"},
	"Admission Tickets":     {"U1F39F"},
	"Ticket":                {"U1F3AB"},
	// award-medal
	"Military Medal":  {"U1F396"},
	"Trophy":          {"U1F3C6"},
	"Sports Medal":    {"U1F3C5"},
	"1st Place Medal": {"U1F947"},
	"2nd Place Medal": {"U1F948"},
	"3rd Place Medal": {"U1F949"},
	// sport
	"Soccer Ball":          {"U26BD"},
	"Baseball":             {"U26BE"},
	"Softball":             {"U1F94E"},
	"Basketball":           {"U1F3C0"},
	"Volleyball":           {"U1F3D0"},
	"American Football":    {"U1F3C8"},
	"Rugby Football":       {"U1F3C9"},
	"Tennis":               {"U1F3BE"},
	"Flying Disc":          {"U1F94F"},
	"Bowling":              {"U1F3B3"},
	"Cricket Game":         {"U1F3CF"},
	"Field Hockey":         {"U1F3D1"},
	"Ice Hockey":           {"U1F3D2"},
	"Lacrosse":             {"U1F94D"},
	"Ping Pong":            {"U1F3D3"},
	"Badminton":            {"U1F3F8"},
	"Boxing Glove":         {"U1F94A"},
	"Martial Arts Uniform": {"U1F94B"},
	"Goal Net":             {"U1F945"},
	"Flag In Hole":         {"U26F3"},
	"Ice Skate":            {"U26F8"},
	"Fishing Pole":         {"U1F3A3"},
	"Diving Mask":          {"U1F93F"},
	"Running Shirt":        {"U1F3BD"},
	"Skis":                 {"U1F3BF"},
	"Sled":                 {"U1F6F7"},
	"Curling Stone":        {"U1F94C"},
	// game
	"Direct Hit":           {"U1F3AF"},
	"Yo-Yo":                {"U1FA80"},
	"Kite":                 {"U1FA81"},
	"Pool 8 Ball":          {"U1F3B1"},
	"Crystal Ball":         {"U1F52E"},
	"Nazar Amulet":         {"U1F9FF"},
	"Video Game":           {"U1F3AE"},
	"Joystick":             {"U1F579"},
	"Slot Machine":         {"U1F3B0"},
	"Game Die":             {"U1F3B2"},
	"Puzzle Piece":         {"U1F9E9"},
	"Teddy Bear":           {"U1F9F8"},
	"Spade Suit":           {"U2660"},
	"Heart Suit":           {"U2665"},
	"Diamond Suit":         {"U2666"},
	"Club Suit":            {"U2663"},
	"Chess Pawn":           {"U265F"},
	"Joker":                {"U1F0CF"},
	"Mahjong Red Dragon":   {"U1F004"},
	"Flower Playing Cards": {"U1F3B4"},
	// arts-and-crafts
	"Performing Arts": {"U1F3AD"},
	"Framed Picture":  {"U1F5BC"},
	"Artist Palette":  {"U1F3A8"},
	"Thread":          {"U1F9F5"},
	"Yarn":            {"U1F9F6"},

	// OBJECTS
	// clothing
	"Glasses":                {"U1F453"},
	"Sunglasses":             {"U1F576"},
	"Goggles":                {"U1F97D"},
	"Lab Coat":               {"U1F97C"},
	"Safety Vest":            {"U1F9BA"},
	"Necktie":                {"U1F454"},
	"T-Shirt":                {"U1F455"},
	"Jeans":                  {"U1F456"},
	"Scarf":                  {"U1F9E3"},
	"Gloves":                 {"U1F9E4"},
	"Coat":                   {"U1F9E5"},
	"Socks":                  {"U1F9E6"},
	"Dress":                  {"U1F457"},
	"Kimono":                 {"U1F458"},
	"Sari":                   {"U1F97B"},
	"One-Piece Swimsuit":     {"U1FA71"},
	"Briefs":                 {"U1FA72"},
	"Shorts":                 {"U1FA73"},
	"Bikini":                 {"U1F459"},
	"Woman’s Clothes":        {"U1F45A"},
	"Purse":                  {"U1F45B"},
	"Handbag":                {"U1F45C"},
	"Clutch Bag":             {"U1F45D"},
	"Shopping Bags":          {"U1F6CD"},
	"Backpack":               {"U1F392"},
	"Man’s Shoe":             {"U1F45E"},
	"Running Shoe":           {"U1F45F"},
	"Hiking Boot":            {"U1F97E"},
	"Flat Shoe":              {"U1F97F"},
	"High-Heeled Shoe":       {"U1F460"},
	"Woman’s Sandal":         {"U1F461"},
	"Ballet Shoes":           {"U1FA70"},
	"Woman’s Boot":           {"U1F462"},
	"Crown":                  {"U1F451"},
	"Woman’s Hat":            {"U1F452"},
	"Top Hat":                {"U1F3A9"},
	"Graduation Cap":         {"U1F393"},
	"Billed Cap":             {"U1F9E2"},
	"Rescue Worker’s Helmet": {"U26D1"},
	"Prayer Beads":           {"U1F4FF"},
	"Lipstick":               {"U1F484"},
	"Ring":                   {"U1F48D"},
	"Gem Stone":              {"U1F48E"},
	// sound
	"Muted Speaker":         {"U1F507"},
	"Speaker Low Volume":    {"U1F508"},
	"Speaker Medium Volume": {"U1F509"},
	"Speaker High Volume":   {"U1F50A"},
	"Loudspeaker":           {"U1F4E2"},
	"Megaphone":             {"U1F4E3"},
	"Postal Horn":           {"U1F4EF"},
	"Bell":                  {"U1F514"},
	"Bell With Slash":       {"U1F515"},
	// music
	"Musical Score":     {"U1F3BC"},
	"Musical Note":      {"U1F3B5"},
	"Musical Notes":     {"U1F3B6"},
	"Studio Microphone": {"U1F399"},
	"Level Slider":      {"U1F39A"},
	"Control Knobs":     {"U1F39B"},
	"Microphone":        {"U1F3A4"},
	"Headphone":         {"U1F3A7"},
	"Radio":             {"U1F4FB"},
	// musical-instrument
	"Saxophone":        {"U1F3B7"},
	"Guitar":           {"U1F3B8"},
	"Musical Keyboard": {"U1F3B9"},
	"Trumpet":          {"U1F3BA"},
	"Violin":           {"U1F3BB"},
	"Banjo":            {"U1FA95"},
	"Drum":             {"U1F941"},
	// phone
	"Mobile Phone":            {"U1F4F1"},
	"Mobile Phone With Arrow": {"U1F4F2"},
	"Telephone":               {"U260E"},
	"Telephone Receiver":      {"U1F4DE"},
	"Pager":                   {"U1F4DF"},
	"Fax Machine":             {"U1F4E0"},
	// computer
	"Battery":          {"U1F50B"},
	"Electric Plug":    {"U1F50C"},
	"Laptop Computer":  {"U1F4BB"},
	"Desktop Computer": {"U1F5A5"},
	"Printer":          {"U1F5A8"},
	"Keyboard":         {"U2328"},
	"Computer Mouse":   {"U1F5B1"},
	"Trackball":        {"U1F5B2"},
	"Computer Disk":    {"U1F4BD"},
	"Floppy Disk":      {"U1F4BE"},
	"Optical Disk":     {"U1F4BF"},
	"Dvd":              {"U1F4C0"},
	"Abacus":           {"U1F9EE"},
	// light-and-video
	"Movie Camera":                  {"U1F3A5"},
	"Film Frames":                   {"U1F39E"},
	"Film Projector":                {"U1F4FD"},
	"Clapper Board":                 {"U1F3AC"},
	"Television":                    {"U1F4FA"},
	"Camera":                        {"U1F4F7"},
	"Camera With Flash":             {"U1F4F8"},
	"Video Camera":                  {"U1F4F9"},
	"Videocassette":                 {"U1F4FC"},
	"Magnifying Glass Tilted Left":  {"U1F50D"},
	"Magnifying Glass Tilted Right": {"U1F50E"},
	"Candle":                        {"U1F56F"},
	"Light Bulb":                    {"U1F4A1"},
	"Flashlight":                    {"U1F526"},
	"Red Paper Lantern":             {"U1F3EE"},
	"Diya Lamp":                     {"U1FA94"},
	// book-paper
	"Notebook With Decorative Cover": {"U1F4D4"},
	"Closed Book":                    {"U1F4D5"},
	"Open Book":                      {"U1F4D6"},
	"Green Book":                     {"U1F4D7"},
	"Blue Book":                      {"U1F4D8"},
	"Orange Book":                    {"U1F4D9"},
	"Books":                          {"U1F4DA"},
	"Notebook":                       {"U1F4D3"},
	"Ledger":                         {"U1F4D2"},
	"Page With Curl":                 {"U1F4C3"},
	"Scroll":                         {"U1F4DC"},
	"Page Facing Up":                 {"U1F4C4"},
	"Newspaper":                      {"U1F4F0"},
	"Rolled-Up Newspaper":            {"U1F5DE"},
	"Bookmark Tabs":                  {"U1F4D1"},
	"Bookmark":                       {"U1F516"},
	"Label":                          {"U1F3F7"},
	// money
	"Money Bag":                 {"U1F4B0"},
	"Yen Banknote":              {"U1F4B4"},
	"Dollar Banknote":           {"U1F4B5"},
	"Euro Banknote":             {"U1F4B6"},
	"Pound Banknote":            {"U1F4B7"},
	"Money With Wings":          {"U1F4B8"},
	"Credit Card":               {"U1F4B3"},
	"Receipt":                   {"U1F9FE"},
	"Chart Increasing With Yen": {"U1F4B9"},
	"Currency Exchange":         {"U1F4B1"},
	"Heavy Dollar Sign":         {"U1F4B2"},
	// mail
	"Envelope":                         {"U2709"},
	"E-Mail":                           {"U1F4E7"},
	"Incoming Envelope":                {"U1F4E8"},
	"Envelope With Arrow":              {"U1F4E9"},
	"Outbox Tray":                      {"U1F4E4"},
	"Inbox Tray":                       {"U1F4E5"},
	"Package":                          {"U1F4E6"},
	"Closed Mailbox With Raised Flag":  {"U1F4EB"},
	"Closed Mailbox With Lowered Flag": {"U1F4EA"},
	"Open Mailbox With Raised Flag":    {"U1F4EC"},
	"Open Mailbox With Lowered Flag":   {"U1F4ED"},
	"Postbox":                          {"U1F4EE"},
	"Ballot Box With Ballot":           {"U1F5F3"},
	// writing
	"Pencil":       {"U270F"},
	"Black Nib":    {"U2712"},
	"Fountain Pen": {"U1F58B"},
	"Pen":          {"U1F58A"},
	"Paintbrush":   {"U1F58C"},
	"Crayon":       {"U1F58D"},
	"Memo":         {"U1F4DD"},
	// office
	"Briefcase":           {"U1F4BC"},
	"File Folder":         {"U1F4C1"},
	"Open File Folder":    {"U1F4C2"},
	"Card Index Dividers": {"U1F5C2"},
	"Calendar":            {"U1F4C5"},
	"Tear-Off Calendar":   {"U1F4C6"},
	"Spiral Notepad":      {"U1F5D2"},
	"Spiral Calendar":     {"U1F5D3"},
	"Card Index":          {"U1F4C7"},
	"Chart Increasing":    {"U1F4C8"},
	"Chart Decreasing":    {"U1F4C9"},
	"Bar Chart":           {"U1F4CA"},
	"Clipboard":           {"U1F4CB"},
	"Pushpin":             {"U1F4CC"},
	"Round Pushpin":       {"U1F4CD"},
	"Paperclip":           {"U1F4CE"},
	"Linked Paperclips":   {"U1F587"},
	"Straight Ruler":      {"U1F4CF"},
	"Triangular Ruler":    {"U1F4D0"},
	"Scissors":            {"U2702"},
	"Card File Box":       {"U1F5C3"},
	"File Cabinet":        {"U1F5C4"},
	"Wastebasket":         {"U1F5D1"},
	// lock
	"Locked":          {"U1F512"},
	"Unlocked":        {"U1F513"},
	"Locked With Pen": {"U1F50F"},
	"Locked With Key": {"U1F510"},
	"Key":             {"U1F511"},
	"Old Key":         {"U1F5DD"},
	// tool
	"Hammer":            {"U1F528"},
	"Axe":               {"U1FA93"},
	"Pick":              {"U26CF"},
	"Hammer And Pick":   {"U2692"},
	"Hammer And Wrench": {"U1F6E0"},
	"Dagger":            {"U1F5E1"},
	"Crossed Swords":    {"U2694"},
	"Pistol":            {"U1F52B"},
	"Bow And Arrow":     {"U1F3F9"},
	"Shield":            {"U1F6E1"},
	"Wrench":            {"U1F527"},
	"Nut And Bolt":      {"U1F529"},
	"Gear":              {"U2699"},
	"Clamp":             {"U1F5DC"},
	"Balance Scale":     {"U2696"},
	"Probing Cane":      {"U1F9AF"},
	"Link":              {"U1F517"},
	"Chains":            {"U26D3"},
	"Toolbox":           {"U1F9F0"},
	"Magnet":            {"U1F9F2"},
	// science
	"Alembic":           {"U2697"},
	"Test Tube":         {"U1F9EA"},
	"Petri Dish":        {"U1F9EB"},
	"Dna":               {"U1F9EC"},
	"Microscope":        {"U1F52C"},
	"Telescope":         {"U1F52D"},
	"Satellite Antenna": {"U1F4E1"},
	// medical
	"Syringe":          {"U1F489"},
	"Drop Of Blood":    {"U1FA78"},
	"Pill":             {"U1F48A"},
	"Adhesive Bandage": {"U1FA79"},
	"Stethoscope":      {"U1FA7A"},
	// household
	"Door":              {"U1F6AA"},
	"Bed":               {"U1F6CF"},
	"Couch And Lamp":    {"U1F6CB"},
	"Chair":             {"U1FA91"},
	"Toilet":            {"U1F6BD"},
	"Shower":            {"U1F6BF"},
	"Bathtub":           {"U1F6C1"},
	"Razor":             {"U1FA92"},
	"Lotion Bottle":     {"U1F9F4"},
	"Safety Pin":        {"U1F9F7"},
	"Broom":             {"U1F9F9"},
	"Basket":            {"U1F9FA"},
	"Roll Of Paper":     {"U1F9FB"},
	"Soap":              {"U1F9FC"},
	"Sponge":            {"U1F9FD"},
	"Fire Extinguisher": {"U1F9EF"},
	"Shopping Cart":     {"U1F6D2"},
	// other-object
	"Cigarette":   {"U1F6AC"},
	"Coffin":      {"U26B0"},
	"Funeral Urn": {"U26B1"},
	"Moai":        {"U1F5FF"},

	// SYMBOLS
	// transport-sign
	"ATM Sign":           {"U1F3E7"},
	"Litter In Bin Sign": {"U1F6AE"},
	"Potable Water":      {"U1F6B0"},
	"Wheelchair Symbol":  {"U267F"},
	"Men’s Room":         {"U1F6B9"},
	"Women’s Room":       {"U1F6BA"},
	"Restroom":           {"U1F6BB"},
	"Baby Symbol":        {"U1F6BC"},
	"Water Closet":       {"U1F6BE"},
	"Passport Control":   {"U1F6C2"},
	"Customs":            {"U1F6C3"},
	"Baggage Claim":      {"U1F6C4"},
	"Left Luggage":       {"U1F6C5"},
	// warning
	"Warning":               {"U26A0"},
	"Children Crossing":     {"U1F6B8"},
	"No Entry":              {"U26D4"},
	"Prohibited":            {"U1F6AB"},
	"No Bicycles":           {"U1F6B3"},
	"No Smoking":            {"U1F6AD"},
	"No Littering":          {"U1F6AF"},
	"Non-Potable Water":     {"U1F6B1"},
	"No Pedestrians":        {"U1F6B7"},
	"No Mobile Phones":      {"U1F4F5"},
	"No One Under Eighteen": {"U1F51E"},
	"Radioactive":           {"U2622"},
	"Biohazard":             {"U2623"},
	// arrow
	"Up Arrow":                       {"U2B06"},
	"Up-Right Arrow":                 {"U2197"},
	"Right Arrow":                    {"U27A1"},
	"Down-Right Arrow":               {"U2198"},
	"Down Arrow":                     {"U2B07"},
	"Down-Left Arrow":                {"U2199"},
	"Left Arrow":                     {"U2B05"},
	"Up-Left Arrow":                  {"U2196"},
	"Up-Down Arrow":                  {"U2195"},
	"Left-Right Arrow":               {"U2194"},
	"Right Arrow Curving Left":       {"U21A9"},
	"Left Arrow Curving Right":       {"U21AA"},
	"Right Arrow Curving Up":         {"U2934"},
	"Right Arrow Curving Down":       {"U2935"},
	"Clockwise Vertical Arrows":      {"U1F503"},
	"Counterclockwise Arrows Button": {"U1F504"},
	"BACK Arrow":                     {"U1F519"},
	"END Arrow":                      {"U1F51A"},
	"ON! Arrow":                      {"U1F51B"},
	"SOON Arrow":                     {"U1F51C"},
	"TOP Arrow":                      {"U1F51D"},
	// religion
	"Place Of Worship":        {"U1F6D0"},
	"Atom Symbol":             {"U269B"},
	"Om":                      {"U1F549"},
	"Star Of David":           {"U2721"},
	"Wheel Of Dharma":         {"U2638"},
	"Yin Yang":                {"U262F"},
	"Latin Cross":             {"U271D"},
	"Orthodox Cross":          {"U2626"},
	"Star And Crescent":       {"U262A"},
	"Peace Symbol":            {"U262E"},
	"Menorah":                 {"U1F54E"},
	"Dotted Six-Pointed Star": {"U1F52F"},
	// zodiac
	"Aries":       {"U2648"},
	"Taurus":      {"U2649"},
	"Gemini":      {"U264A"},
	"Cancer":      {"U264B"},
	"Leo":         {"U264C"},
	"Virgo":       {"U264D"},
	"Libra":       {"U264E"},
	"Scorpio":     {"U264F"},
	"Sagittarius": {"U2650"},
	"Capricorn":   {"U2651"},
	"Aquarius":    {"U2652"},
	"Pisces":      {"U2653"},
	"Ophiuchus":   {"U26CE"},
	// av-symbol
	"Shuffle Tracks Button": {"U1F500"},
	"Repeat Button":         {"U1F501"},
	"Repeat Single Button":  {"U1F502"},
	"Play Button":           {"U25B6"},
	"Fast-Forward Button":   {"U23E9"},
	"Next Track Button":     {"U23ED"},
	"Play Or Pause Button":  {"U23EF"},
	"Reverse Button":        {"U25C0"},
	"Fast Reverse Button":   {"U23EA"},
	"Last Track Button":     {"U23EE"},
	"Upwards Button":        {"U1F53C"},
	"Fast Up Button":        {"U23EB"},
	"Downwards Button":      {"U1F53D"},
	"Fast Down Button":      {"U23EC"},
	"Pause Button":          {"U23F8"},
	"Stop Button":           {"U23F9"},
	"Record Button":         {"U23FA"},
	"Eject Button":          {"U23CF"},
	"Cinema":                {"U1F3A6"},
	"Dim Button":            {"U1F505"},
	"Bright Button":         {"U1F506"},
	"Antenna Bars":          {"U1F4F6"},
	"Vibration Mode":        {"U1F4F3"},
	"Mobile Phone Off":      {"U1F4F4"},
	// gender
	"Female Sign": {"U2640"},
	"Male Sign":   {"U2642"},
	// other-symbol
	"Medical Symbol":               {"U2695"},
	"Infinity":                     {"U267E"},
	"Recycling Symbol":             {"U267B"},
	"Fleur-De-Lis":                 {"U269C"},
	"Trident Emblem":               {"U1F531"},
	"Name Badge":                   {"U1F4DB"},
	"Japanese Symbol For Beginner": {"U1F530"},
	"Hollow Red Circle":            {"U2B55"},
	"Check Mark Button":            {"U2705"},
	"Check Box With Check":         {"U2611"},
	"Check Mark":                   {"U2714"},
	"Multiplication Sign":          {"U2716"},
	"Cross Mark":                   {"U274C"},
	"Cross Mark Button":            {"U274E"},
	"Plus Sign":                    {"U2795"},
	"Minus Sign":                   {"U2796"},
	"Division Sign":                {"U2797"},
	"Curly Loop":                   {"U27B0"},
	"Double Curly Loop":            {"U27BF"},
	"Part Alternation Mark":        {"U303D"},
	"Eight-Spoked Asterisk":        {"U2733"},
	"Eight-Pointed Star":           {"U2734"},
	"Sparkle":                      {"U2747"},
	"Double Exclamation Mark":      {"U203C"},
	"Exclamation Question Mark":    {"U2049"},
	"Question Mark":                {"U2753"},
	"White Question Mark":          {"U2754"},
	"White Exclamation Mark":       {"U2755"},
	"Exclamation Mark":             {"U2757"},
	"Wavy Dash":                    {"U3030"},
	"Copyright":                    {"U00A9"},
	"Registered":                   {"U00AE"},
	"Trade Mark":                   {"U2122"},
	// keycap
	"Keycap: #":  {"U0023", "UFE0F", "U20E3"},
	"Keycap: *":  {"U002A", "UFE0F", "U20E3"},
	"Keycap: 0":  {"U0030", "UFE0F", "U20E3"},
	"Keycap: 1":  {"U0031", "UFE0F", "U20E3"},
	"Keycap: 2":  {"U0032", "UFE0F", "U20E3"},
	"Keycap: 3":  {"U0033", "UFE0F", "U20E3"},
	"Keycap: 4":  {"U0034", "UFE0F", "U20E3"},
	"Keycap: 5":  {"U0035", "UFE0F", "U20E3"},
	"Keycap: 6":  {"U0036", "UFE0F", "U20E3"},
	"Keycap: 7":  {"U0037", "UFE0F", "U20E3"},
	"Keycap: 8":  {"U0038", "UFE0F", "U20E3"},
	"Keycap: 9":  {"U0039", "UFE0F", "U20E3"},
	"Keycap: 10": {"U1F51F"},
	// alphanum
	"Input Latin Uppercase":            {"U1F520"},
	"Input Latin Lowercase":            {"U1F521"},
	"Input Numbers":                    {"U1F522"},
	"Input Symbols":                    {"U1F523"},
	"Input Latin Letters":              {"U1F524"},
	"A Button (Blood Type)":            {"U1F170"},
	"AB Button (Blood Type)":           {"U1F18E"},
	"B Button (Blood Type)":            {"U1F171"},
	"CL Button":                        {"U1F191"},
	"COOL Button":                      {"U1F192"},
	"FREE Button":                      {"U1F193"},
	"Information":                      {"U2139"},
	"ID Button":                        {"U1F194"},
	"Circled M":                        {"U24C2"},
	"NEW Button":                       {"U1F195"},
	"NG Button":                        {"U1F196"},
	"O Button (Blood Type)":            {"U1F17E"},
	"OK Button":                        {"U1F197"},
	"P Button":                         {"U1F17F"},
	"SOS Button":                       {"U1F198"},
	"UP! Button":                       {"U1F199"},
	"VS Button":                        {"U1F19A"},
	"Japanese “here” Button":           {"U1F201"},
	"Japanese “service Charge” Button": {"U1F202"},
	"Japanese “monthly Amount” Button": {"U1F237"},
	"Japanese “not Free Of Charge” Button": {"U1F236"},
	"Japanese “reserved” Button":           {"U1F22F"},
	"Japanese “bargain” Button":            {"U1F250"},
	"Japanese “discount” Button":           {"U1F239"},
	"Japanese “free Of Charge” Button":     {"U1F21A"},
	"Japanese “prohibited” Button":         {"U1F232"},
	"Japanese “acceptable” Button":         {"U1F251"},
	"Japanese “application” Button":        {"U1F238"},
	"Japanese “passing Grade” Button":      {"U1F234"},
	"Japanese “vacancy” Button":            {"U1F233"},
	"Japanese “congratulations” Button":    {"U3297"},
	"Japanese “secret” Button":             {"U3299"},
	"Japanese “open For Business” Button":  {"U1F23A"},
	"Japanese “no Vacancy” Button":         {"U1F235"},
	// geometric
	"Red Circle":                {"U1F534"},
	"Orange Circle":             {"U1F7E0"},
	"Yellow Circle":             {"U1F7E1"},
	"Green Circle":              {"U1F7E2"},
	"Blue Circle":               {"U1F535"},
	"Purple Circle":             {"U1F7E3"},
	"Brown Circle":              {"U1F7E4"},
	"Black Circle":              {"U26AB"},
	"White Circle":              {"U26AA"},
	"Red Square":                {"U1F7E5"},
	"Orange Square":             {"U1F7E7"},
	"Yellow Square":             {"U1F7E8"},
	"Green Square":              {"U1F7E9"},
	"Blue Square":               {"U1F7E6"},
	"Purple Square":             {"U1F7EA"},
	"Brown Square":              {"U1F7EB"},
	"Black Large Square":        {"U2B1B"},
	"White Large Square":        {"U2B1C"},
	"Black Medium Square":       {"U25FC"},
	"White Medium Square":       {"U25FB"},
	"Black Medium-Small Square": {"U25FE"},
	"White Medium-Small Square": {"U25FD"},
	"Black Small Square":        {"U25AA"},
	"White Small Square":        {"U25AB"},
	"Large Orange Diamond":      {"U1F536"},
	"Large Blue Diamond":        {"U1F537"},
	"Small Orange Diamond":      {"U1F538"},
	"Small Blue Diamond":        {"U1F539"},
	"Red Triangle Pointed Up":   {"U1F53A"},
	"Red Triangle Pointed Down": {"U1F53B"},
	"Diamond With A Dot":        {"U1F4A0"},
	"Radio Button":              {"U1F518"},
	"White Square Button":       {"U1F533"},
	"Black Square Button":       {"U1F532"},

	// FLAGS
	// flag
	"Chequered Flag":  {"U1F3C1"},
	"Triangular Flag": {"U1F6A9"},
	"Crossed Flags":   {"U1F38C"},
	"Black Flag":      {"U1F3F4"},
	"White Flag":      {"U1F3F3"},
	"Rainbow Flag":    {"U1F3F3", "UFE0F", "U200D", "U1F308"},
	"Pirate Flag":     {"U1F3F4", "U200D", "U2620", "UFE0F"},
	// country-flag
	"Ascension Island":                       {"U1F1E6", "U1F1E8"},
	"Andorra":                                {"U1F1E6", "U1F1E9"},
	"United Arab Emirates":                   {"U1F1E6", "U1F1EA"},
	"Afghanistan":                            {"U1F1E6", "U1F1EB"},
	"Antigua & Barbuda":                      {"U1F1E6", "U1F1EC"},
	"Anguilla":                               {"U1F1E6", "U1F1EE"},
	"Albania":                                {"U1F1E6", "U1F1F1"},
	"Armenia":                                {"U1F1E6", "U1F1F2"},
	"Angola":                                 {"U1F1E6", "U1F1F4"},
	"Antarctica":                             {"U1F1E6", "U1F1F6"},
	"Argentina":                              {"U1F1E6", "U1F1F7"},
	"American Samoa":                         {"U1F1E6", "U1F1F8"},
	"Austria":                                {"U1F1E6", "U1F1F9"},
	"Australia":                              {"U1F1E6", "U1F1FA"},
	"Aruba":                                  {"U1F1E6", "U1F1FC"},
	"Åland Islands":                          {"U1F1E6", "U1F1FD"},
	"Azerbaijan":                             {"U1F1E6", "U1F1FF"},
	"Bosnia & Herzegovina":                   {"U1F1E7", "U1F1E6"},
	"Barbados":                               {"U1F1E7", "U1F1E7"},
	"Bangladesh":                             {"U1F1E7", "U1F1E9"},
	"Belgium":                                {"U1F1E7", "U1F1EA"},
	"Burkina Faso":                           {"U1F1E7", "U1F1EB"},
	"Bulgaria":                               {"U1F1E7", "U1F1EC"},
	"Bahrain":                                {"U1F1E7", "U1F1ED"},
	"Burundi":                                {"U1F1E7", "U1F1EE"},
	"Benin":                                  {"U1F1E7", "U1F1EF"},
	"St. Barthélemy":                         {"U1F1E7", "U1F1F1"},
	"Bermuda":                                {"U1F1E7", "U1F1F2"},
	"Brunei":                                 {"U1F1E7", "U1F1F3"},
	"Bolivia":                                {"U1F1E7", "U1F1F4"},
	"Caribbean Netherlands":                  {"U1F1E7", "U1F1F6"},
	"Brazil":                                 {"U1F1E7", "U1F1F7"},
	"Bahamas":                                {"U1F1E7", "U1F1F8"},
	"Bhutan":                                 {"U1F1E7", "U1F1F9"},
	"Bouvet Island":                          {"U1F1E7", "U1F1FB"},
	"Botswana":                               {"U1F1E7", "U1F1FC"},
	"Belarus":                                {"U1F1E7", "U1F1FE"},
	"Belize":                                 {"U1F1E7", "U1F1FF"},
	"Canada":                                 {"U1F1E8", "U1F1E6"},
	"Cocos (Keeling) Islands":                {"U1F1E8", "U1F1E8"},
	"Congo - Kinshasa":                       {"U1F1E8", "U1F1E9"},
	"Central African Republic":               {"U1F1E8", "U1F1EB"},
	"Congo - Brazzaville":                    {"U1F1E8", "U1F1EC"},
	"Switzerland":                            {"U1F1E8", "U1F1ED"},
	"Côte D’Ivoire":                          {"U1F1E8", "U1F1EE"},
	"Cook Islands":                           {"U1F1E8", "U1F1F0"},
	"Chile":                                  {"U1F1E8", "U1F1F1"},
	"Cameroon":                               {"U1F1E8", "U1F1F2"},
	"China":                                  {"U1F1E8", "U1F1F3"},
	"Colombia":                               {"U1F1E8", "U1F1F4"},
	"Clipperton Island":                      {"U1F1E8", "U1F1F5"},
	"Costa Rica":                             {"U1F1E8", "U1F1F7"},
	"Cuba":                                   {"U1F1E8", "U1F1FA"},
	"Cape Verde":                             {"U1F1E8", "U1F1FB"},
	"Curaçao":                                {"U1F1E8", "U1F1FC"},
	"Christmas Island":                       {"U1F1E8", "U1F1FD"},
	"Cyprus":                                 {"U1F1E8", "U1F1FE"},
	"Czechia":                                {"U1F1E8", "U1F1FF"},
	"Germany":                                {"U1F1E9", "U1F1EA"},
	"Diego Garcia":                           {"U1F1E9", "U1F1EC"},
	"Djibouti":                               {"U1F1E9", "U1F1EF"},
	"Denmark":                                {"U1F1E9", "U1F1F0"},
	"Dominica":                               {"U1F1E9", "U1F1F2"},
	"Dominican Republic":                     {"U1F1E9", "U1F1F4"},
	"Algeria":                                {"U1F1E9", "U1F1FF"},
	"Ceuta & Melilla":                        {"U1F1EA", "U1F1E6"},
	"Ecuador":                                {"U1F1EA", "U1F1E8"},
	"Estonia":                                {"U1F1EA", "U1F1EA"},
	"Egypt":                                  {"U1F1EA", "U1F1EC"},
	"Western Sahara":                         {"U1F1EA", "U1F1ED"},
	"Eritrea":                                {"U1F1EA", "U1F1F7"},
	"Spain":                                  {"U1F1EA", "U1F1F8"},
	"Ethiopia":                               {"U1F1EA", "U1F1F9"},
	"European Union":                         {"U1F1EA", "U1F1FA"},
	"Finland":                                {"U1F1EB", "U1F1EE"},
	"Fiji":                                   {"U1F1EB", "U1F1EF"},
	"Falkland Islands":                       {"U1F1EB", "U1F1F0"},
	"Micronesia":                             {"U1F1EB", "U1F1F2"},
	"Faroe Islands":                          {"U1F1EB", "U1F1F4"},
	"France":                                 {"U1F1EB", "U1F1F7"},
	"Gabon":                                  {"U1F1EC", "U1F1E6"},
	"United Kingdom":                         {"U1F1EC", "U1F1E7"},
	"Grenada":                                {"U1F1EC", "U1F1E9"},
	"Georgia":                                {"U1F1EC", "U1F1EA"},
	"French Guiana":                          {"U1F1EC", "U1F1EB"},
	"Guernsey":                               {"U1F1EC", "U1F1EC"},
	"Ghana":                                  {"U1F1EC", "U1F1ED"},
	"Gibraltar":                              {"U1F1EC", "U1F1EE"},
	"Greenland":                              {"U1F1EC", "U1F1F1"},
	"Gambia":                                 {"U1F1EC", "U1F1F2"},
	"Guinea":                                 {"U1F1EC", "U1F1F3"},
	"Guadeloupe":                             {"U1F1EC", "U1F1F5"},
	"Equatorial Guinea":                      {"U1F1EC", "U1F1F6"},
	"Greece":                                 {"U1F1EC", "U1F1F7"},
	"South Georgia & South Sandwich Islands": {"U1F1EC", "U1F1F8"},
	"Guatemala":                              {"U1F1EC", "U1F1F9"},
	"Guam":                                   {"U1F1EC", "U1F1FA"},
	"Guinea-Bissau":                          {"U1F1EC", "U1F1FC"},
	"Guyana":                                 {"U1F1EC", "U1F1FE"},
	"Hong Kong SAR China":                    {"U1F1ED", "U1F1F0"},
	"Heard & McDonald Islands":               {"U1F1ED", "U1F1F2"},
	"Honduras":                               {"U1F1ED", "U1F1F3"},
	"Croatia":                                {"U1F1ED", "U1F1F7"},
	"Haiti":                                  {"U1F1ED", "U1F1F9"},
	"Hungary":                                {"U1F1ED", "U1F1FA"},
	"Canary Islands":                         {"U1F1EE", "U1F1E8"},
	"Indonesia":                              {"U1F1EE", "U1F1E9"},
	"Ireland":                                {"U1F1EE", "U1F1EA"},
	"Israel":                                 {"U1F1EE", "U1F1F1"},
	"Isle Of Man":                            {"U1F1EE", "U1F1F2"},
	"India":                                  {"U1F1EE", "U1F1F3"},
	"British Indian Ocean Territory":         {"U1F1EE", "U1F1F4"},
	"Iraq":                                   {"U1F1EE", "U1F1F6"},
	"Iran":                                   {"U1F1EE", "U1F1F7"},
	"Iceland":                                {"U1F1EE", "U1F1F8"},
	"Italy":                                  {"U1F1EE", "U1F1F9"},
	"Jersey":                                 {"U1F1EF", "U1F1EA"},
	"Jamaica":                                {"U1F1EF", "U1F1F2"},
	"Jordan":                                 {"U1F1EF", "U1F1F4"},
	"Japan":                                  {"U1F1EF", "U1F1F5"},
	"Kenya":                                  {"U1F1F0", "U1F1EA"},
	"Kyrgyzstan":                             {"U1F1F0", "U1F1EC"},
	"Cambodia":                               {"U1F1F0", "U1F1ED"},
	"Kiribati":                               {"U1F1F0", "U1F1EE"},
	"Comoros":                                {"U1F1F0", "U1F1F2"},
	"St. Kitts & Nevis":                      {"U1F1F0", "U1F1F3"},
	"North Korea":                            {"U1F1F0", "U1F1F5"},
	"South Korea":                            {"U1F1F0", "U1F1F7"},
	"Kuwait":                                 {"U1F1F0", "U1F1FC"},
	"Cayman Islands":                         {"U1F1F0", "U1F1FE"},
	"Kazakhstan":                             {"U1F1F0", "U1F1FF"},
	"Laos":                                   {"U1F1F1", "U1F1E6"},
	"Lebanon":                                {"U1F1F1", "U1F1E7"},
	"St. Lucia":                              {"U1F1F1", "U1F1E8"},
	"Liechtenstein":                          {"U1F1F1", "U1F1EE"},
	"Sri Lanka":                              {"U1F1F1", "U1F1F0"},
	"Liberia":                                {"U1F1F1", "U1F1F7"},
	"Lesotho":                                {"U1F1F1", "U1F1F8"},
	"Lithuania":                              {"U1F1F1", "U1F1F9"},
	"Luxembourg":                             {"U1F1F1", "U1F1FA"},
	"Latvia":                                 {"U1F1F1", "U1F1FB"},
	"Libya":                                  {"U1F1F1", "U1F1FE"},
	"Morocco":                                {"U1F1F2", "U1F1E6"},
	"Monaco":                                 {"U1F1F2", "U1F1E8"},
	"Moldova":                                {"U1F1F2", "U1F1E9"},
	"Montenegro":                             {"U1F1F2", "U1F1EA"},
	"St. Martin":                             {"U1F1F2", "U1F1EB"},
	"Madagascar":                             {"U1F1F2", "U1F1EC"},
	"Marshall Islands":                       {"U1F1F2", "U1F1ED"},
	"North Macedonia":                        {"U1F1F2", "U1F1F0"},
	"Mali":                                   {"U1F1F2", "U1F1F1"},
	"Myanmar (Burma)":                        {"U1F1F2", "U1F1F2"},
	"Mongolia":                               {"U1F1F2", "U1F1F3"},
	"Macao SAR China":                        {"U1F1F2", "U1F1F4"},
	"Northern Mariana Islands":               {"U1F1F2", "U1F1F5"},
	"Martinique":                             {"U1F1F2", "U1F1F6"},
	"Mauritania":                             {"U1F1F2", "U1F1F7"},
	"Montserrat":                             {"U1F1F2", "U1F1F8"},
	"Malta":                                  {"U1F1F2", "U1F1F9"},
	"Mauritius":                              {"U1F1F2", "U1F1FA"},
	"Maldives":                               {"U1F1F2", "U1F1FB"},
	"Malawi":                                 {"U1F1F2", "U1F1FC"},
	"Mexico":                                 {"U1F1F2", "U1F1FD"},
	"Malaysia":                               {"U1F1F2", "U1F1FE"},
	"Mozambique":                             {"U1F1F2", "U1F1FF"},
	"Namibia":                                {"U1F1F3", "U1F1E6"},
	"New Caledonia":                          {"U1F1F3", "U1F1E8"},
	"Niger":                                  {"U1F1F3", "U1F1EA"},
	"Norfolk Island":                         {"U1F1F3", "U1F1EB"},
	"Nigeria":                                {"U1F1F3", "U1F1EC"},
	"Nicaragua":                              {"U1F1F3", "U1F1EE"},
	"Netherlands":                            {"U1F1F3", "U1F1F1"},
	"Norway":                                 {"U1F1F3", "U1F1F4"},
	"Nepal":                                  {"U1F1F3", "U1F1F5"},
	"Nauru":                                  {"U1F1F3", "U1F1F7"},
	"Niue":                                   {"U1F1F3", "U1F1FA"},
	"New Zealand":                            {"U1F1F3", "U1F1FF"},
	"Oman":                                   {"U1F1F4", "U1F1F2"},
	"Panama":                                 {"U1F1F5", "U1F1E6"},
	"Peru":                                   {"U1F1F5", "U1F1EA"},
	"French Polynesia":                       {"U1F1F5", "U1F1EB"},
	"Papua New Guinea":                       {"U1F1F5", "U1F1EC"},
	"Philippines":                            {"U1F1F5", "U1F1ED"},
	"Pakistan":                               {"U1F1F5", "U1F1F0"},
	"Poland":                                 {"U1F1F5", "U1F1F1"},
	"St. Pierre & Miquelon":                  {"U1F1F5", "U1F1F2"},
	"Pitcairn Islands":                       {"U1F1F5", "U1F1F3"},
	"Puerto Rico":                            {"U1F1F5", "U1F1F7"},
	"Palestinian Territories":                {"U1F1F5", "U1F1F8"},
	"Portugal":                               {"U1F1F5", "U1F1F9"},
	"Palau":                                  {"U1F1F5", "U1F1FC"},
	"Paraguay":                               {"U1F1F5", "U1F1FE"},
	"Qatar":                                  {"U1F1F6", "U1F1E6"},
	"Réunion":                                {"U1F1F7", "U1F1EA"},
	"Romania":                                {"U1F1F7", "U1F1F4"},
	"Serbia":                                 {"U1F1F7", "U1F1F8"},
	"Russia":                                 {"U1F1F7", "U1F1FA"},
	"Rwanda":                                 {"U1F1F7", "U1F1FC"},
	"Saudi Arabia":                           {"U1F1F8", "U1F1E6"},
	"Solomon Islands":                        {"U1F1F8", "U1F1E7"},
	"Seychelles":                             {"U1F1F8", "U1F1E8"},
	"Sudan":                                  {"U1F1F8", "U1F1E9"},
	"Sweden":                                 {"U1F1F8", "U1F1EA"},
	"Singapore":                              {"U1F1F8", "U1F1EC"},
	"St. Helena":                             {"U1F1F8", "U1F1ED"},
	"Slovenia":                               {"U1F1F8", "U1F1EE"},
	"Svalbard & Jan Mayen":                   {"U1F1F8", "U1F1EF"},
	"Slovakia":                               {"U1F1F8", "U1F1F0"},
	"Sierra Leone":                           {"U1F1F8", "U1F1F1"},
	"San Marino":                             {"U1F1F8", "U1F1F2"},
	"Senegal":                                {"U1F1F8", "U1F1F3"},
	"Somalia":                                {"U1F1F8", "U1F1F4"},
	"Suriname":                               {"U1F1F8", "U1F1F7"},
	"South Sudan":                            {"U1F1F8", "U1F1F8"},
	"São Tomé & Príncipe":                    {"U1F1F8", "U1F1F9"},
	"El Salvador":                            {"U1F1F8", "U1F1FB"},
	"Sint Maarten":                           {"U1F1F8", "U1F1FD"},
	"Syria":                                  {"U1F1F8", "U1F1FE"},
	"Eswatini":                               {"U1F1F8", "U1F1FF"},
	"Tristan Da Cunha":                       {"U1F1F9", "U1F1E6"},
	"Turks & Caicos Islands":                 {"U1F1F9", "U1F1E8"},
	"Chad":                                   {"U1F1F9", "U1F1E9"},
	"French Southern Territories":            {"U1F1F9", "U1F1EB"},
	"Togo":                                   {"U1F1F9", "U1F1EC"},
	"Thailand":                               {"U1F1F9", "U1F1ED"},
	"Tajikistan":                             {"U1F1F9", "U1F1EF"},
	"Tokelau":                                {"U1F1F9", "U1F1F0"},
	"Timor-Leste":                            {"U1F1F9", "U1F1F1"},
	"Turkmenistan":                           {"U1F1F9", "U1F1F2"},
	"Tunisia":                                {"U1F1F9", "U1F1F3"},
	"Tonga":                                  {"U1F1F9", "U1F1F4"},
	"Turkey [Flag]":                          {"U1F1F9", "U1F1F7"},
	"Trinidad & Tobago":                      {"U1F1F9", "U1F1F9"},
	"Tuvalu":                                 {"U1F1F9", "U1F1FB"},
	"Taiwan":                                 {"U1F1F9", "U1F1FC"},
	"Tanzania":                               {"U1F1F9", "U1F1FF"},
	"Ukraine":                                {"U1F1FA", "U1F1E6"},
	"Uganda":                                 {"U1F1FA", "U1F1EC"},
	"U.S. Outlying Islands":                  {"U1F1FA", "U1F1F2"},
	"United Nations":                         {"U1F1FA", "U1F1F3"},
	"United States":                          {"U1F1FA", "U1F1F8"},
	"Uruguay":                                {"U1F1FA", "U1F1FE"},
	"Uzbekistan":                             {"U1F1FA", "U1F1FF"},
	"Vatican City":                           {"U1F1FB", "U1F1E6"},
	"St. Vincent & Grenadines":               {"U1F1FB", "U1F1E8"},
	"Venezuela":                              {"U1F1FB", "U1F1EA"},
	"British Virgin Islands":                 {"U1F1FB", "U1F1EC"},
	"U.S. Virgin Islands":                    {"U1F1FB", "U1F1EE"},
	"Vietnam":                                {"U1F1FB", "U1F1F3"},
	"Vanuatu":                                {"U1F1FB", "U1F1FA"},
	"Wallis & Futuna":                        {"U1F1FC", "U1F1EB"},
	"Samoa":                                  {"U1F1FC", "U1F1F8"},
	"Kosovo":                                 {"U1F1FD", "U1F1F0"},
	"Yemen":                                  {"U1F1FE", "U1F1EA"},
	"Mayotte":                                {"U1F1FE", "U1F1F9"},
	"South Africa":                           {"U1F1FF", "U1F1E6"},
	"Zambia":                                 {"U1F1FF", "U1F1F2"},
	"Zimbabwe":                               {"U1F1FF", "U1F1FC"},
	"England":                                {"U1F3F4", "UE0067", "UE0062", "UE0065", "UE006E", "UE0067", "UE007F"},
	"Scotland":                               {"U1F3F4", "UE0067", "UE0062", "UE0073", "UE0063", "UE0074", "UE007F"},
	"Wales":                                  {"U1F3F4", "UE0067", "UE0062", "UE0077", "UE006C", "UE0073", "UE007F"},

	// SKIN TONES
	"Light Skin Tone":        {"U1F3FB"},
	"Medium-Light Skin Tone": {"U1F3FC"},
	"Medium Skin Tone":       {"U1F3FD"},
	"Medium-Dark Skin Tone":  {"U1F3FE"},
	"Dark Skin Tone":         {"U1F3FF"},

	// MODIFIERS
	"Zero-Width Joiner": {"U200D"},
	"Emoji Style":       {"UFE0F"},
	"Text Style":        {"UFE0E"},
}
